### ISSUE TITLE
[Bug]: EagleMistralLarge3Model crashes with AttributeError: 'use_mha' on vLLM 0.21.0

### ISSUE THREAD

**Issue by mareksimunek** [vllm-project/vllm#43298]
## Environment

- **vLLM version:** 0.21.0
- **Model:** `mistralai/Mistral-Large-3-675B-Instruct-2512` with Eagle speculative decoding
- **Hardware:** 8x H200 NVL, TP=8

```
(APIServer pid=1) INFO 05-21 08:22:26 [utils.py:240] non-default args: {'model_tag': 'mistralai/Mistral-Large-3-675B-Instruct-2512-NVFP4', 'enable_auto_tool_choice': True, 'tool_call_parser': 'mistral', 'model': 'mistralai/Mistral-Large-3-675B-Instruct-2512-NVFP4', 'tokenizer_mode': 'mistral', 'served_model_name': ['mistral-large-3-675b-instruct-2512'], 'config_format': 'mistral', 'load_format': 'mistral', 'tensor_parallel_size': 8, 'speculative_config': {'model': 'mistralai/Mistral-Large-3-675B-Instruct-2512-Eagle', 'num_speculative_tokens': 3, 'method': 'eagle', 'max_model_len': '16384'}}
```

## Description

`EagleMistralLarge3Model` fails during weight loading with:

```
File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 1355, in load_weights
    if self.use_mha:
       ^^^^^^^^^^^^
AttributeError: 'EagleMistralLarge3Model' object has no attribute 'use_mha'
```

This worked in vLLM 0.19.x / 0.20.2 and regressed in 0.21.0.

## Root Cause

PR #16383 moved `load_weights` from `DeepseekV2ForCausalLM` to `DeepseekV2Model`, which now references `self.use_mha`. `DeepseekV2Model.__init__` sets this attribute, but `EagleMistralLarge3Model.__init__` calls `nn.Module.__init__(self)` directly instead of `super().__init__()`, so `use_mha` is never initialized.

This is the same class of bug fixed in #37232 (missing `aux_hidden_state_layers`). The underlying fragility — bypassing the parent `__init__` — was flagged by reviewers at the time.

## How to Reproduce

```bash
vllm serve mistralai/Mistral-Large-3-675B-Instruct-2512 \
  --speculative-config '{"model": "mistralai/Mistral-Large-3-675B-Instruct-2512-Eagle", "num_speculative_tokens": 3, "method": "eagle"}'
```

## Suggested Fix

Add `self.use_mha = False` to `EagleMistralLarge3Model.__init__` in `vllm/model_executor/models/mistral_large_3_eagle.py`. Mistral Large 3 uses MLA, so this is always `False`.

Longer term, the bypassed `super().__init__()` pattern will keep causing these regressions whenever `DeepseekV2Model.__init__` gains new attributes.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jshaofa-ui** [comment]
## Proposed Solution: EagleMistralLarge3Model `use_mha` AttributeError

### Root Cause
PR #16383 moved `load_weights` to `DeepseekV2Model`, which references `self.use_mha`. `EagleMistralLarge3Model` inherits from `DeepseekV2Model` but calls `nn.Module.__init__(self)` directly, bypassing `DeepseekV2Model.__init__()` where `use_mha` is set. Same class of bug as #37232.

### Fix (Short-term, 1 line)
```python
class EagleMistralLarge3Model(DeepseekV2Model):
    def __init__(self, config):
        nn.Module.__init__(self)
        self.use_mha = False  # Mistral Large 3 uses MLA
```

### Long-term
Replace `nn.Module.__init__(self)` with `super().__init__(config)` to ensure all parent init runs.

Full solution: `solutions/vllm-43298-eagle-mistral-large-use-mha-fix.md`

**Comment by HumphreySun98** [comment]
Picking this up — will mirror the exact fix pattern from #37232 (`self.aux_hidden_state_layers = ()` was added to `EagleMistralLarge3Model.__init__` for the same class of bug). PR shortly.

**Comment by adhusch** [comment]
Hello,

is there any update on this? Speculative Decoding for the Mistral Models is now regression broken since 3 releases because of this issue. I can confirm that last working release was 0.20.2 as reported above (tested with Mistral Small 4), but that one has broken tool calling for that model which was fixed in 0.21 where the Eagle is broken, so.. dilemma 

@juliendenize ?

Thanks a lot!

**Comment by adhusch** [comment]
This should be fixed by #45217 but as now Mistral models are broken because of #44911 it's not directly testable 🙃 potentially without mmproj it's working now?

**Comment by juliendenize** [comment]
Hey could you try on main, both issues should be fixed now

**Comment by adhusch** [comment]
@juliendenize thank you very much! Looks good with current nightly :)

**Comment by dotmobo** [comment]
it worked in 0.25.1 but with 0.28.0 it's broken again :

```
AttributeError: 'EagleMistralLarge3ForCausalLM' object has no attribute '_embed_text_input_ids'.
```
