### PR TITLE
 [ROCm][Bugfix] Fix ROCm build failure

### LINKED ISSUE #14669: [Bug]: ROCm fail to build due to compilation error of `moe_wna16.cu`
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
INFO 03-12 09:10:06 [__init__.py:256] Automatically detected platform rocm.                                                                    
Collecting environment information...                                                                                                          
PyTorch version: 2.7.0a0+git6c0e746                                                                                                            
Is debug build: False                                                                                                                          
CUDA used to build PyTorch: N/A                                                                                                                
ROCM used to build PyTorch: 6.3.42133-1b9c17779                                                                                                
                                                                                                                                               
OS: Ubuntu 22.04.5 LTS (x86_64)                                                                                                                
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0                                                                                             
Clang version: 18.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.3.1 24491 1e0fda770a2079fbd71e4b70974d74f62fd3af10)          
CMake version: version 3.31.6                                                                                                                  
Libc version: glibc-2.35                                                                                                                       
                                                                                                                                               
Python version: 3.12.9 (main, Feb  5 2025, 08:49:00) [GCC 11.4.0] (64-bit runtime)                                                             
Python platform: Linux-5.15.0-116-generic-x86_64-with-glibc2.35        
GPU models and configuration: AMD Instinct MI300X (gfx942:sramecc+:xnack-)                                                                     
Nvidia driver version: Could not collect                                                                                                       
cuDNN version: Could not collect                                                                                                               
HIP runtime version: 6.3.42133                                                                                                                 
MIOpen runtime version: 3.3.0                                                                                                                  
Is XNNPACK available: True                                                                                                                     

PYTORCH_ROCM_ARCH=gfx942
LD_LIBRARY_PATH=/usr/local/lib/python3.12/dist-packages/cv2/../../lib64:/opt/rocm/lib:/usr/local/lib:
NCCL_CUMEM_ENABLE=0
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

</details>


### 🐛 Describe the bug

When compiling the latest vLLM commit on ROCm, it gives the following error.

![Image](https://github.com/user-attachments/assets/7e950073-9dae-4918-8e0f-ec7881ed76d0)

The error comes from the compilation of CUDA only kernels, introduced in https://github.com/vllm-project/vllm/commit/90e88ab75632745c137647bf710d63997529fb89.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by vllmellm**
This pull request addresses the compilation error encountered when building the latest vLLM commit on ROCm. The issue arises from the compilation of CUDA-only kernels introduced in commit 90e88ab. Specifically, the error occurs during the compilation of moe_wna16.cu.

Changes:
- Compile moe_wna16_gemm for non-ROCm architectures only.

FIX #14669

### CODE REVIEW

File: csrc/moe/torch_bindings.cpp [hunk 1]
```diff
@@ -31,28 +31,33 @@ TORCH_LIBRARY_EXPAND(TORCH_EXTENSION_NAME, m) {
...
+        " -> Tensor");
+    // conditionally compiled so impl registration is in source file
+
 #endif
 }
 
 REGISTER_EXTENSION(TORCH_EXTENSION_NAME)
+
+
+
```
Comment (DarkLight1337) [inline csrc/moe/torch_bindings.cpp:63]: I don't think these lines are necessary?

**Comment by tjtanaa** [comment]
@DarkLight1337  Please close this PR as it is resolved in https://github.com/vllm-project/vllm/pull/14629
