### ISSUE TITLE
ImportError: cannot import name 'MistralConfig' from 'transformers'

### ISSUE THREAD

**Issue by peter-ch** [vllm-project/vllm#1458]
I get this error trying to run a server with a llama-2 model. Also, is this the correct way to state I want the model quantized? Something else is that it refuses to work with the latest tokenizers. It only works with the exact version tokenizers==0.13.4rc3

peter@desktop:~$ python3 -m vllm.entrypoints.api_server -q awq --model lmsys/vicuna-13b-v1.3
Downloading (…)lve/main/config.json: 100%|██████████████████████████████████████████████████████████████████████████| 567/567 [00:00<00:00, 1.36MB/s]
INFO 10-24 13:09:39 llm_engine.py:72] Initializing an LLM engine with config: model='lmsys/vicuna-13b-v1.3', tokenizer='lmsys/vicuna-13b-v1.3', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=awq, seed=0)
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████| 727/727 [00:00<00:00, 2.12MB/s]
Downloading tokenizer.model: 100%|████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 1.63MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████| 435/435 [00:00<00:00, 1.28MB/s]
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/api_server.py", line 74, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 487, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 270, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 306, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 110, in __init__
    self._init_workers(distributed_init_method)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 128, in _init_workers
    from vllm.worker.worker import Worker  # pylint: disable=import-outside-toplevel
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 10, in <module>
    from vllm.model_executor import get_model, InputMetadata, set_random_seed
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/__init__.py", line 2, in <module>
    from vllm.model_executor.model_loader import get_model
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 10, in <module>
    from vllm.model_executor.models import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/__init__.py", line 12, in <module>
    from vllm.model_executor.models.mistral import MistralForCausalLM
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mistral.py", line 32, in <module>
    from transformers import MistralConfig
ImportError: cannot import name 'MistralConfig' from 'transformers' (/home/peter/.local/lib/python3.10/site-packages/transformers/__init__.py)

**Comment by Inquinim** [comment]
Hey Peter, sounds like you might be using a version of Transformers that doesn't support the Mistral model. It looks like you're asking for Vicuna though which is a bit weird -- it must be trying to load support for Mistral by default.

What version of Transformers are you using and can you try upgrading to the latest? (pip install --upgrade transformers)

**Comment by demegire** [comment]
Mistral is not in the stable branch. Try this:

`pip uninstall transformers`

then,

`pip install git+https://github.com/huggingface/transformers`

**Comment by peter-ch** [comment]
Thanks, it worked.

**Comment by BobCN2017** [comment]
For my situation, pip install transformers==4.34.1, It works.
