### ISSUE TITLE
[Bug][ROCm]: v0.30.0 release is missing #57252, so GLM-5.3 (GlmMoeDsa) can't start on AMD

### ISSUE THREAD

**Issue by JPedro2** [vllm-project/vllm#58575]
### Your current environment

<details>
<summary>collect_env highlights (full output available)</summary>

```
vLLM Version                 : 0.30.0
PyTorch version              : 2.12.0+git6bbd260
ROCM Version                 : 7.2.53211-c2d9476115
HIP runtime version          : 7.2.53211
amd-aiter                    : 0.1.21.post2
transformers                 : 5.17.0
GPU                          : 8x AMD Instinct MI325X (gfx942), driver 6.19.14.31400100
```

</details>

Image `vllm/vllm-openai-rocm:v0.30.0` as published, with no custom layers and no entrypoint override (the pod reports `docker.io/vllm/vllm-openai-rocm@sha256:2e7da1ad1c66836802072588adea75f9f4991da5f9545b4318e91d422c22ce6a`). Model `zai-org/GLM-5.3` at revision `aca966e4e02791568aa6a4ced368624b3d897f42`, native FP8, which resolves to `GlmMoeDsaForCausalLM` with `DeepseekV32MTPModel` as the drafter. One Kubernetes node, TP 8.

```
vllm serve zai-org/GLM-5.3 --port 8000 --tensor-parallel-size 8 --max-model-len 262144 \
  --gpu-memory-utilization 0.85 --revision aca966e4e02791568aa6a4ced368624b3d897f42 \
  --kv-cache-dtype fp8_e4m3 --speculative-config.method mtp --speculative-config.num_speculative_tokens 5 \
  --tool-call-parser glm47 --enable-auto-tool-choice --reasoning-parser glm45 \
  --max-num-batched-tokens 16384 --max-num-seqs 128 --safetensors-load-strategy prefetch \
  --enable-prefix-caching --linear-backend aiter --moe-backend aiter
```

Env: `VLLM_ROCM_USE_AITER=1`, `VLLM_ROCM_USE_AITER_FUSION_SHARED_EXPERTS=1`, `VLLM_EXECUTE_MODEL_TIMEOUT_SECONDS=1800`, `PYTHONHASHSEED=0`. These are the AMD flags from the GLM-5.3 recipe plus our sizing, and the same block runs on v0.29.0.

### 🐛 Describe the bug

The engine dies in `profile_run` about two minutes into init, on every start, and the pod crash-loops. We first hit it on our own build (the official image plus a tokenizer package), then reproduced it on the plain official image above on 2026-09-23. Every TP worker raises the same error while `torch.compile` traces the model:

```
File ".../vllm/v1/worker/gpu_worker.py", line 572, in determine_available_memory
  self.model_runner.profile_run()
File ".../vllm/v1/worker/gpu_model_runner.py", line 6524, in profile_run
File ".../vllm/model_executor/models/deepseek_v2.py", line 1968, in forward
File ".../vllm/model_executor/layers/mla.py", line 235, in forward
  self.mla_attn.impl.record_logical_topk_ready()
torch._dynamo.exc.ObservedAttributeError: ConstantVariable(str: "'ROCMAiterMLASparseImpl' object has no attribute 'record_logical_topk_ready'")
```

It's the regression from #57248, which was reported for GLM-5.3-Flash on a nightly and fixed on main by #57252. The fix didn't make it into v0.30.0: the tag's `rocm_aiter_mla_sparse.py` has no such method, and `releases/v0.30.0` last moved on 2026-09-21 without it. The `v0.30.1rc0` tag has the fix, but it's on main, so as far as we can tell nothing ships it before 0.31.0.

It isn't limited to Flash. The call at `mla.py:235` runs on every sparse MLA layer, and on ROCm the only sparse backend is `ROCM_AITER_MLA_SPARSE`, so no flag avoids it. #56604 notes the same crash on `GLM-5.2-FP8`, and the same call sits in `models/deepseek_v32/attention.py:496`, so DeepSeek-V3.2 on ROCm should fail too (we haven't run it). The GLM-5.3 and DeepSeek-V3.2 recipes both send AMD users to `vllm/vllm-openai-rocm:latest`, which is v0.30.0 today.

Could #57252 go into a v0.30.1? If a patch release isn't planned, a known-issues line on the v0.30.0 release would save the next AMD user some time.

### Workaround

Adding the #57252 method to the installed file before `vllm serve` starts gets it running:

```python
def record_logical_topk_ready(self) -> None:
    pass
```

With that one change, the block starts in about 6.5 minutes, passes a known-answer prompt, a tool call and a 4 of 4 needle recall at 50K tokens, and served a 3 hour agentic load test through our gateway (8,272 requests, 0 errors).

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
