### ISSUE TITLE
[CI Failure]: test_reward.py::test_prm_models - AttributeError: 'DynamicCache' object has no attribute 'get_usable_length'. Did you mean: 'get_seq_length'?

### ISSUE THREAD

**Issue by russellb** [vllm-project/vllm#22398]
### Name of failing test

models/language/pooling/test_reward.py::test_prm_models[True-half-Qwen/Qwen2.5-Math-PRM-7B]

### Basic information

- [ ] Flaky test
- [ ] Can reproduce locally
- [ ] Caused by external libraries (e.g. bug in `transformers`)

### 🧪 Describe the failing test

[2025-08-06T21:39:31Z] FAILED models/language/pooling/test_reward.py::test_prm_models[True-half-Qwen/Qwen2.5-Math-PRM-7B] - AttributeError: 'DynamicCache' object has no attribute 'get_usable_length'. Did you mean: 'get_seq_length'?
[2025-08-06T21:39:31Z] FAILED models/language/pooling/test_reward.py::test_prm_models[False-half-Qwen/Qwen2.5-Math-PRM-7B] - AttributeError: 'DynamicCache' object has no attribute 'get_usable_length'. Did you mean: 'get_seq_length'?

### 📝 History of failing test

https://buildkite.com/organizations/vllm/analytics/suites/ci-1/tests/600d233a-e9e7-8f9f-b750-17eede6e1172?branch=main&period=1day

broken by #22327

**Comment by noooop** [comment]
Qwen/Qwen2.5-Math-PRM-7B hf Implementation does not support v4.54.1

refer to https://github.com/vllm-project/vllm/pull/21931#issuecomment-3154000018
