### PR TITLE
[Bugfix][LoRA] Guard None group members in expand_packed_lora (partial LoRA on Qwen3.5/3.6 GatedDeltaNet)

### LINKED ISSUE #47639: [Bug]: Partial LoRA on Qwen3.5/Qwen3.6 GatedDeltaNet (in_proj_qkv without in_proj_z) crashes in expand_packed_lora — regression from #37912
### Your current environment

<details>
<summary>Environment</summary>

```
vLLM version:      0.24.0   (latest; also reproduced on current main)
Model:             Qwen/Qwen3.6-27B (runs through the shared Qwen3.5 code path ->
                   Qwen3_5ForConditionalGeneration; multimodal GDN hybrid)
OS:                Ubuntu 24.04.4 LTS (x86_64)
Python:            3.12.3
torch:             2.11.0+cu130
CUDA:              13.0 (runtime 13.0.88), driver 570.124.06
GPU:               1x NVIDIA H200 (Hopper, SM 9.0)
FlashInfer:        0.6.12
transformers:      5.13.0
```

Serve command that triggers it:
```bash
vllm serve Qwen/Qwen3.6-27B --reasoning-parser qwen3 --enable-lora \
  --lora-modules my_lora=<adapter targeting q_proj,k_proj,v_proj,in_proj_qkv> \
  --mm-processor-kwargs '{"max_pixels": 262144}' --enforce-eager
```

Known-good: v0.20.0 loads this adapter (verified on the same H200 box, torch 2.11.0+cu130,
FlashInfer 0.6.8.post1). Crash starts at v0.21.0 — the release that first contains #37912
(commit `48698b1b9`) — and persists through v0.24.0 and current `main`.
</details>

### 🐛 Describe the bug

Loading a LoRA adapter that targets **only a subset** of a GatedDeltaNet packed projection
group on Qwen3.5/Qwen3.6 crashes at adapter-activation time. Concretely: an adapter that
adapts `in_proj_qkv` but **not** `in_proj_z`.

**Traceback (vLLM 0.24.0, trimmed to the relevant frames):**

```
(EngineCore) ERROR [core.py:1449] Invocation of add_lora method failed
(EngineCore) ERROR [core.py:1449] Traceback (most recent call last):
(EngineCore) ERROR [core.py:1449]   File ".../vllm/v1/engine/core.py", line 825, in add_lora
(EngineCore) ERROR [core.py:1449]     return self.model_executor.add_lora(lora_request)
(EngineCore) ERROR [core.py:1449]   File ".../vllm/v1/worker/lora_model_runner_mixin.py", line 276, in add_lora
(EngineCore) ERROR [core.py:1449]     return self.lora_manager.add_adapter(lora_request)
(EngineCore) ERROR [core.py:1449]   File ".../vllm/lora/worker_manager.py", line 314, in add_adapter
(EngineCore) ERROR [core.py:1449]     self._adapter_manager.activate_adapter(lora_request.lora_int_id)
(EngineCore) ERROR [core.py:1449]   File ".../vllm/lora/model_manager.py", line 325, in activate_adapter
(EngineCore) ERROR [core.py:1449]     module.set_lora(
(EngineCore) ERROR [core.py:1449]   File ".../vllm/lora/layers/column_parallel_linear.py", line 314, in set_lora
(EngineCore) ERROR [core.py:1449]     lora_a, lora_b = self.expand_packed_lora(lora_a, lora_b)
(EngineCore) ERROR [core.py:1449]   File ".../vllm/lora/layers/column_parallel_linear.py", line 280, in expand_packed_lora
(EngineCore) ERROR [core.py:1449]     b_rows, cu_rows, covered = b_i.shape[0], 0, 0
(EngineCore) ERROR [core.py:1449] AttributeError: 'NoneType' object has no attribute 'shape'
```

Surfaces to the API server as:
```
ValueError: Call to add_lora method failed: 'NoneType' object has no attribute 'shape'
```

### Root cause

`packed_modules_mapping` for Qwen3.5 declares the GDN input projection as a 2-member group
mapped onto a 4-slice fused `MergedColumnParallelLinear`:

```python
# vllm/model_executor/models/qwen3_5.py
"in_proj_qkvz": ["in_proj_qkv", "in_proj_z"],  # in_proj_qkv -> slices (0,1,2), in_proj_z -> slice 3
"in_proj_ba":   ["in_proj_b", "in_proj_a"],
```

When an adapter provides fewer group members than there are slices, `set_lora` routes
through `expand_packed_lora`, which dereferences each entry unconditionally:

```python
for a_i, b_i in zip(lora_a, lora_b):
    b_rows, cu_rows, covered = b_i.shape[0], 0, 0  # crashes when b_i is None
```

If a group member is absent from the adapter (here `in_proj_z`), its entry is `None`, and
`b_i.shape[0]` raises.

The rest of the packed-LoRA pipeline already tolerates unadapted slices: the sibling method
`slice_lora_b` and the downstream stacking loop in `set_lora` both guard `None`.
`expand_packed_lora` is the only step missing the guard. A `None` entry should mean "this
group member is not adapted; leave its slice(s) at base weights."

### Regression: introduced by #37912

This worked on v0.20.0, which built `in_proj_qkv` and `in_proj_z` as **separate modules**
under LoRA (`create_in_proj_qkvz`) so they could be adapted independently.

PR #37912 ("[Bugfix] Fuse Qwen3.5 in_qkvz_proj forwarding with LoRA enabled") unified them
back into the fused `in_proj_qkvz` layer and added the `expand_packed_lora` helper — a
reasonable simplification — but the new helper didn't carry over the `None`-tolerance, so
partial groups now crash instead of being supported.

### Minimal repro

PEFT adapter targeting GDN qkv (and full-attention q/k/v) but **not** z:

```json
{ "target_modules": "model\\.language_model\\..*\\.(q_proj|k_proj|v_proj|in_proj_qkv)" }
```

Per-layer keys present: `linear_attn.in_proj_qkv.lora_A/lora_B`
Per-layer keys **absent**: `linear_attn.in_proj_z.lora_A/lora_B`

```bash
vllm serve <Qwen3.5-or-3.6-model> --enable-lora --lora-modules my=/path/to/adapter
# -> crashes in expand_packed_lora on first adapter activation
```

### Proposed fix

Make `expand_packed_lora` skip `None` group members, emitting `None` placeholders for the
slice(s) they cover so subsequent groups stay aligned and those slices are left at base
weights — matching the `None`-tolerance already in `slice_lora_b` and the `set_lora`
stacking loop. This restores partial-group support inside the current fused architecture
without reverting the #37912 split.

`expand_packed_lora` is only reached for the `in_proj_qkvz` group (2 members → 4 slices);
every other packed group (`qkv_proj`, `gate_up_proj`, `in_proj_ba`) has
`len(lora_b) == n_slices` and takes the normal, already-`None`-tolerant path. In
`in_proj_qkvz` the only multi-slice member (`in_proj_qkv`, Q+K+V) leads and the only optional
member (`in_proj_z`) trails, so a `None` member covers exactly the remaining slices.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by eilamc14**
## Purpose

Fix a crash when loading a LoRA adapter that targets only some members of a GatedDeltaNet
packed projection group on Qwen3.5/Qwen3.6 (e.g. `in_proj_qkv` without `in_proj_z`).
`expand_packed_lora` dereferenced `b_i.shape[0]` on a `None` group member, raising
`AttributeError: 'NoneType' object has no attribute 'shape'`.

This is a regression introduced by #37912, which unified the GDN input projections into a
fused packed layer and added `expand_packed_lora` — but the new helper didn't carry over the
`None`-tolerance that its sibling `slice_lora_b` and the `set_lora` stacking loop already
have. Partial groups worked in v0.20.0 (which built the projections as separate modules under
LoRA via `create_in_proj_qkvz`).

Fixes #47639

## Fix

Make `expand_packed_lora` skip `None` group members, emitting `None` placeholders for the
slice(s) they cover so subsequent groups stay aligned, leaving those slices at base weights.
This restores partial-group support inside the current fused architecture without reverting
the #37912 split.

`expand_packed_lora` is only reached for the `in_proj_qkvz` group (2 members → 4 slices);
every other packed group has `len(lora_b) == n_slices` and takes the normal,
already-`None`-tolerant path. In `in_proj_qkvz` the multi-slice member (`in_proj_qkv`) leads
and the optional member (`in_proj_z`) trails, so a `None` member covers exactly the remaining
slices (documented in a code comment).

## Test Plan

End-to-end on 1x H200, vLLM 0.24.0, torch 2.11.0+cu130, with a real Qwen3.6-27B LoRA adapter
targeting `q_proj,k_proj,v_proj,in_proj_qkv` (i.e. `in_proj_z` absent):

- **Before the fix:** `add_lora` fails during adapter activation with
  `AttributeError: 'NoneType' object has no attribute 'shape'` in `expand_packed_lora`
  (server exits with `ValueError: Call to add_lora method failed: ...`).
- **After the fix:** the same `vllm serve ... --enable-lora --lora-modules my_lora=<adapter>`
  starts and applies the adapter successfully.

## Notes

- AI assistance was used to author this change; I have reviewed every changed line, understand
  the fix, and ran the tests above.
- Not a duplicate: checked open PRs/issues for `expand_packed_lora` / partial LoRA on Qwen3.5
  GDN before filing — see #47639.

@Isotr0py
@jeejeelee

### CODE REVIEW

**Comment by eilamc14** [comment]
Update : not fixed in vllm v0.25.0 , pr still relevant

**Comment by eilamc14** [comment]
Update: not fixed in vllm 0.25.1
@jeejeelee @Isotr0py

**Comment by eilamc14** [comment]
Update : not fixed in vllm 0.26.0 , pr still relevant

I removed the test from the pr, may not be necessary, only 1 file (though a very important one) change.

1st time contributer, would love if my pr can be marked as ready for tests. though its a niche I need this fix and rather be on main vllm then my own fork.

Love your work and will happy to be a part of it!

@jeejeelee @Isotr0py

**Comment by eilamc14** [comment]
still not fixed in vllm0.27.1
tagging some other code owners this may be relevant to
@tdoublep @ZJY0516 @vadiklyutiy
Would love to get a ready for the github action or requested fixes/ other implementation of this problem

**Comment by linitra24** [comment]
LGTM

**Review by linitra24 — APPROVED** [review]

**Review by jeejeelee — APPROVED** [review]

**Comment by eilamc14** [comment]
[buildkite/ci/pr](https://buildkite.com/vllm/ci/builds/84349) failed, i think unrelated? @jeejeelee @linitra24
