### PR TITLE
[Spec Decode] DFlash/DSpark draft support under decode context parallelism

### PR DESCRIPTION
**Pull request by drakosha**
### What

Make dense (GQA/MHA) DFlash/DSpark drafts work under `decode_context_parallel_size > 1`
by caching the whole DCP group's KV heads on every rank.

Rebased on `main` after #52188. That PR landed the DCP-aware draft slot mapping this
branch used to carry (`cp_local_slot` / `prepare_dcp_local_seq_lens` in
`vllm/v1/worker/gpu/cp_utils.py`), and its version is strictly better: it also handles
the null block and the rejected context suffix. That commit is dropped here in favour
of upstream's, leaving the part #52188 does not cover.

#52188 enables the MLA draft path (Kimi-K3, one latent KV head, no head-gather). This
PR enables the dense path, where the head-gather is exactly what breaks.

### Why (root cause)

Reported by @Leoyzen in #46514: DFlash/DSpark acceptance collapses to ~0% under DCP.

The dense flash DCP path (`_forward_with_dcp`: all-gather query heads across the DCP
group, attend against the rank-local KV shard, LSE-merge) is only correct when a rank's
KV shard holds the KV heads for all gathered query heads, i.e. KV heads replicated
across the DCP group. `verify_with_parallel_config` enforces this for dense *targets*;
nothing checked the *draft*. The GLM-5.2 DSpark draft is MHA (64q/64kv), so under TP4
each rank has a 16-head shard and the gathered 64 query heads are GQA-remapped 4:1 onto
the wrong KV heads.

### How

Cache the whole DCP group's KV heads on every rank (replicated) for that rank's
interleaved positions:

- `cache_num_kv_heads` decouples the KV-cache spec from the impl's head count
  (`Attention.__init__`, defaults to `num_kv_heads`, only larger for this case).
- The draft precompute all-gathers K/V across the DCP group in the same rank order the
  query gather uses, so MHA maps 1:1 and GQA stays contiguous.
- The query block's K/V is not slotted into such a cache: the DCP path attends it
  against the freshly computed K/V, and at input-prep time the rank holds only its
  local heads, so writing them would corrupt the replicated layout.
- `vllm/config/vllm.py` fails fast on the layouts that are still wrong (partial
  replication, a dense draft whose architecture does not implement the replication, a
  quantized draft cache where the per-head descale is not wired for the decoupled head
  count).

Per-rank memory stays at the DCP=1 level because `AttentionSpec` already divides
blocks-per-request by the DCP size.

Behaviour change against the previous revision of this PR, worth calling out for
reviewers who saw it before: query slots used to be forced to PAD for *every* DCP run.
That is now conditional on the draft cache actually being head-replicated
(`PAD_QUERY_SLOTS_UNDER_CP`, derived from the draft attention layers). The
unconditional form would have broken the Kimi-K3 path from #52188, which writes real
query slots under DCP.

### Not a duplicate / related

No open PR implements DCP KV-head replication for the draft cache (checked
`gh pr list --search`). #52188 is complementary, not overlapping, after this rebase:
MLA draft there, dense draft here, sharing upstream's slot mapping.

The DCP change itself is independent of target/KV-cache dtype. Reproducing the GLM-5.2
numbers below (an `fp8_ds_mla` MLA target) also needs the draft-cache-dtype fallback
from #48381: without it the dense draft inherits the MLA-only `fp8_ds_mla` layout and
fails to load (bug #48380), before DCP is reached. DCP support for non-MLA targets does
not depend on #48381.

### Tests

The DCP slot-mapping tests this branch added are gone with the commit they covered.
The two behaviours specific to a head-replicated cache, plus a cross-rank partition
check, now extend upstream's suite:

```
pytest tests/v1/spec_decode/test_dflash_prepare_inputs.py -v
```

### Model evaluation (acceptance, the metric this change affects)

GLM-5.2-NVFP4 + `RedHatAI/GLM-5.2-speculator.dspark`, TP4/DCP4, 4xH200,
`vllm:spec_decode_num_*_total`:

| config | mean acceptance length |
|---|---|
| DCP=1 (baseline) | 2.40 |
| DCP=4, before this change | 1.10 (collapse) |
| **DCP=4, this change** | **2.63** |
| DCP=4, this change + CPU KV offload | 2.54 |

Per-position acceptance is a healthy monotone curve (pos0 54% to pos6 8%). Starts
cleanly under FULL-decode CUDA graphs; the OffloadingConnector draft-group exclude
(#47891) still fires correctly with the larger draft page.

A second run on the same hardware, GLM-5.2-NVFP4 + DSpark k=7, TP4 + EP, `fp8_ds_mla`,
`max_model_len` 131072, `max_num_seqs` 8:

| | GPU KV cache | N=1 | N=8 | mean accepted length |
|---|---|---|---|---|
| **DCP=4** (this PR) | 449,792 tok | 94 tok/s | 318 tok/s | **2.75 / 2.91** |
| DCP=1 (baseline) | 205,312 tok | 135 tok/s | 395 tok/s | 3.01 / 2.89 |
| DCP=4 before this PR | | | | **1.10** |

DCP=4 is slower than DCP=1 on short contexts, which is the expected DCP overhead, and
it buys ~2.2x the KV cache (450k vs 205k tokens), which is the point of enabling DCP.

Both runs predate the rebase and were measured on the revision that carried its own
slot mapping. The mechanism under test (KV-head replication) is unchanged by the
rebase, but the numbers have not been re-measured on top of #52188 yet.

### AI assistance

AI assistance (Claude) was used for this change. The submitting human reviewed every
changed line and ran the tests/benchmarks above.

### CODE REVIEW

**Comment by drakosha** [comment]
Validated on 4×H200 — this is the hardware check the PR was waiting on.

GLM-5.2-NVFP4 target + `RedHatAI/GLM-5.2-speculator.dspark` (k=7), TP4 + EP, `fp8_ds_mla`, `max_model_len` 131072, `max_num_seqs` 8:

| | GPU KV cache | N=1 | N=8 | mean accepted length |
|---|---|---|---|---|
| **DCP=4** (this PR) | 449,792 tok | 94 tok/s | 318 tok/s | **2.75 / 2.91** |
| DCP=1 (baseline) | 205,312 tok | 135 tok/s | 395 tok/s | 3.01 / 2.89 |
| DCP=4 before this PR | — | — | — | **1.10** |

Acceptance under DCP=4 is at parity with DCP=1 — the collapse to ~1.10 (the ~0% acceptance @Leoyzen reported in #46514) is gone, i.e. the draft now reads its own KV shard instead of another rank's blocks.

DCP=4 is slower than DCP=1 on short contexts (94 vs 135 tok/s at N=1) — that is the expected DCP overhead, and it buys ~2.2× the KV cache (450k vs 205k tokens), which is the point of enabling DCP in the first place.

Prebuilt image used for this run, if anyone wants to reproduce:

```
ghcr.io/drakosha/vllm-openai:allfixes-20260714
```

(official `vllm/vllm-openai:cu129-nightly-94c0ef3` + this PR + #48381 + the #47327 regression fixes from #48612; Python-only overlay, no kernel rebuild)

AI assistance (Claude) was used to run this validation; the numbers are from real runs on our hardware and the submitter reviewed every claim.

**Comment by voipmonitor** [comment]
I have a materially different implementation available for the same draft-cache
correctness problem:

https://github.com/voipmonitor/vllm/tree/fix/dcp-cache-topology-contract-20260821

PR #48392 keeps token positions DCP-sharded, replicates KV heads across the DCP
group, and retains the DCP attention/LSE collectives. The linked implementation
keeps the ordinary tensor-parallel KV-head partition, replicates draft token
positions, and executes draft attention locally on each rank. Both layouts have
the same asymptotic draft KV storage per rank:

```text
#48392: local TP KV heads * DCP * positions / DCP
alternative: local TP KV heads * all positions
```

The position-replicated design requires a per-cache topology contract because a
single model can contain DCP-sharded target attention, rank-local recurrent
state, and position-replicated draft attention. The contract is carried through
cache sizing, scheduler alignment, block-table widths, slot mapping, attention
metadata, and CUDA Graph capture.

Validation of the equivalent Infernal Invocation implementation used the
official Kimi-K3 MXFP4 target on 16 RTX PRO 6000 Blackwell GPUs with TP16/DCP16:

- DSpark: 31.416 target cycles/s and 1,016,293 physical target KV tokens;
- DFlash: 29.160 target cycles/s and 1,048,576 physical target KV tokens;
- target-only control: 55.719 tok/s and 1,458,823 physical KV tokens;
- 500,224-token DFlash prefill plus decode completed with finite log
  probabilities.

The branch is rebased on `main@e85d1b69cf2`, all pre-commit hooks pass, 98
cache/block-table tests pass with five device skips, 21 DFlash semantic tests
pass, and 47 prefix-cache tests pass. AI assistance was used to implement and
validate the branch.

Would maintainers prefer the position-replicated/local-attention design as a
separate PR, or should it be proposed as an alternative revision of #48392?

**Comment by drakosha** [comment]
Rebased on `main`, conflicts gone.

#52188 landed the DCP-aware draft slot mapping this branch carried, and handles more
cases than mine did (null block, rejected context suffix), so I dropped my commit for
upstream's. What remains is the part #52188 does not cover: it enables the MLA draft
path (Kimi-K3, one latent KV head, no head-gather), this PR enables the dense GQA/MHA
path, where the head-gather across the DCP group is what corrupts the KV mapping. The
two are complementary; the diff here is now ~300 lines over six files.

@voipmonitor, could you post mean accepted length with and without your fix? Target
cycles/s and finite log probabilities do not separate a draft reading its own KV shard
from one reading another rank's: the broken case runs at full speed and accepts almost
nothing (1.10 vs 2.63 fixed vs 2.40 at DCP=1 in my runs). Without it the two designs
are not on comparable evidence.

AI assistance (Claude) was used for this rebase.
