### PR TITLE
[CI][Bugfix] Fix test_models_fse_init deepseek_v4 mock

### PR DESCRIPTION
**Pull request by tdoublep**
## Purpose

`test_models_fse_init[*-deepseek_v4]` is currently red on `main`. It's a semantic conflict between two PRs that were each green on their own:

- #52401 made `DeepseekV4Attention.__init__` read `vllm_config.use_v2_model_runner`, which needs `model_config.runner_type` and `model_config.is_moe`.
- #51695 added this test with a `SimpleNamespace` mock that doesn't set those, so construction dies with `AttributeError: ... has no attribute 'runner_type'`.

Fix: add both attributes to the mock. Test-only, no runtime change.

## Test Plan

Run the affected test: `pytest tests/model_executor/layers/test_fused_shared_expert.py -k deepseek_v4`

## Test Result

Fix verified by tracing the `use_v2_model_runner` path; needs a GPU lane (model-executor / amd) to run the full test. Not a duplicate — no open PR touches this. AI assistance was used.

### CODE REVIEW

**Review by khluu — APPROVED** [review]

**Comment by khluu** [comment]
Buildkite CI #84493 shows this patch clears the original `runner_type` failure, but the MI300 Model Executor lane now reaches the next missing field in the same fixture:

```
test_models_fse_init[True-exclude1-deepseek_v4]
AttributeError: 'types.SimpleNamespace' object has no attribute 'method'
vllm/config/vllm.py:630 (VllmConfig.use_v2_model_runner)
```

The failing test later replaces `vllm_config.speculative_config` with a partial mock that only has `draft_model_config` (around `test_fused_shared_expert.py:537`). Suggested follow-up:

```diff
 vllm_config.speculative_config = SimpleNamespace(
-    draft_model_config=SimpleNamespace(hf_config=config)
+    draft_model_config=SimpleNamespace(hf_config=config),
+    method="mtp",
 )
```

I initially suggested `None`; after tracing the complete fixture semantics, `"mtp"` is the better contract value because this block explicitly constructs `DeepSeekV4MTP` and mirrors the resolved production `SpeculativeConfig`. It handles both the DSpark and DFlash branch checks while remaining valid if later validation paths inspect `.method`.

Please rerun all DeepSeek-V4 FSE parametrizations after the edit so we catch the complete mock contract in one pass:

```
pytest tests/model_executor/layers/test_fused_shared_expert.py -k 'fse_init and deepseek_v4'
```

The PR's AMD auto-retry and H200 lane are still running, but this failure shape is deterministic rather than an infra flake.

**Comment by khluu** [comment]
Follow-up: at Kevin's request I opened #52842 as the replacement that includes this PR's exact commit `038d308c4` plus the `method="mtp"` fixture completion. Your original commit and authorship are preserved as the first commit, and the new PR explicitly credits this work. Thank you for the original fix.
