### ISSUE TITLE
[Feature]: Expose option to load new model weights from disk

### ISSUE THREAD

**Issue by edbeeching** [vllm-project/vllm#12774]
### 🚀 The feature, motivation and pitch

In an async RL setting, we often want to perform fast generation with a vllm endpoint on a separate node and occasionally sync model weights from disk. It would be good if this option was available on the vllm endpoint. 

### Alternatives

SGLang already exposes this option: https://docs.sglang.ai/backend/native_api.html#Update-Weights-From-Disk

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by mgoin** [comment]
Hi @edbeeching can you see if this feature achieves what you need? https://github.com/vllm-project/vllm/pull/12084

We have been actively working on adding new features to better support RL workflows

**Comment by lewtun** [comment]
@mgoin thanks for the pointer to https://github.com/vllm-project/vllm/pull/12084 ! 

What Ed is referring to is whether this collective can be exposed in the OpenAI-compatible server as a dedicated endpoint. For context, we'd like to spin up a `vllm` server on N nodes and run training on M nodes. At each training step, we'd like to synchronise the weights so that the `vllm` server is generating from the current policy. 

We did look at https://github.com/vllm-project/vllm/pull/12084, but it seems to require us to adopt `ray` which adds a rather high amount of complexity to `trl`

**Comment by michaelnny** [comment]
To add some context, in vLLM version 0.7.x, without using tensor parallel, we can update the weights using this hacking code, but it no longer works with 0.8.x


```python

    def _sync_vllm_weights(self, llm: LLM, state_dict: dict) -> None:
        # only works with vLLM 0.7.*
        model = llm.llm_engine.model_executor.driver_worker.model_runner.model
        model.load_weights(state_dict.items())

```

**Comment by mgoin** [comment]
@youkaichao could you look at this? I remember there might be a new way to access the model

**Comment by youkaichao** [comment]
> AttributeError: 'LLMEngine' object has no attribute 'model_executor'

`llm.llm_engine.model_executor` only works in v1 when you set `VLLM_ENABLE_V1_MULTIPROCESSING=0` environment variable.

for more future-proof and stable interface, i think you should use `LLM.collective_rpc`, which is available in v1 after https://github.com/vllm-project/vllm/pull/15444 (0.8.3 i think).
