### ISSUE TITLE
[Bug] v0.20.2 empty build incompatible with V1 engine (missing vllm._C)

### ISSUE THREAD

**Issue by Al2O3Al2O3** [vllm-project/vllm#55856]
## Environment

- **vLLM Version**: v0.20.2
- **Build Type**: empty (`VLLM_TARGET_DEVICE=empty`)
- **Hardware**: Kunlunxin P800 × 8
- **Python**: 3.10
- **PyTorch**: 2.9.0

## Description

vLLM v0.20.2 with `VLLM_TARGET_DEVICE=empty` fails to initialize when the V1 engine is active (which is the default in v0.20.2). The V1 engine's model initialization code path depends on C++ extensions (`vllm._C`) that are not compiled in the empty build.

## Symptoms

When starting vLLM server or using `LLM()` API with empty build:

```python
AttributeError: '_OpNamespace' '_C' object has no attribute 'silu_and_mul'
```

Log shows:
```
WARNING: Failed to import from vllm._C: ModuleNotFoundError("No module named 'vllm._C'")
...
(EngineCore) self.act_fn = SiluAndMul()
(EngineCore) self.op = torch.ops._C.silu_and_mul
(EngineCore) AttributeError: '_OpNamespace' '_C' object has no attribute 'silu_and_mul'
```

## Root Cause

1. vLLM v0.20.2 **defaults to V1 engine** (`vllm.v1.engine.async_llm.AsyncLLM`)
2. Empty build **does not compile C++ extensions** (`vllm._C` module)
3. V1 engine model initialization **depends on C++ ops** like `torch.ops._C.silu_and_mul`

This creates an incompatibility:
- v0.20.2 = V1 engine by default
- empty build = no C++ extensions
- V1 engine = requires C++ extensions
- **Result: cannot use empty build with v0.20.2**

## Call Stack

```
api_server.py:136 AsyncLLM.from_vllm_config()
  → v1/engine/async_llm.py:146 EngineCoreClient.make_async_mp_client()
    → v1/engine/core.py:118 executor_class(vllm_config)
      → v1/executor/uniproc_executor.py:52 driver_worker.load_model()
        → model_loader/base_loader.py:55 initialize_model()
          → models/qwen3.py:290 Qwen3ForCausalLM.__init__()
            → models/qwen2.py:111 Qwen3MLP.__init__()
              → layers/activation.py:133 SiluAndMul.__init__()
                → self.op = torch.ops._C.silu_and_mul ❌
```

## Reproduction

```bash
# Install vLLM v0.20.2 with empty build
VLLM_TARGET_DEVICE=empty pip install vllm==0.20.2

# Try to start server
python -m vllm.entrypoints.openai.api_server \
  --model <any-model> \
  --trust-remote-code

# Or use LLM API
from vllm import LLM
llm = LLM(model="<any-model>")  # Fails with AttributeError
```

## Questions

1. Is empty build intended to work with V1 engine in v0.20.2?
2. If not, is there a way to force V0 engine in v0.20.2? (No env var or parameter found)
3. Should empty builds disable V1 engine automatically?

## Expected Behavior

One of:
- Empty build should work with V1 engine (ops should fall back to non-C++ implementations)
- Or, v0.20.2 should auto-detect missing `vllm._C` and fall back to V0 engine
- Or, documentation should clearly state that empty builds require older vLLM versions

## Workaround

None found. Users must either:
- Use a full build (not empty) with C++ extensions compiled
- Or downgrade to vLLM version before V1 became default

## Additional Context

This issue blocks vLLM plugin users (e.g., vllm-plugin-FL for multi-vendor hardware) who rely on empty builds to avoid vendor-specific C++ compilation requirements.

**Comment by aman-singh315** [comment]
hey! @Al2O3Al2O3 I'd like to give this a try

**Comment by aman-singh315** [comment]
Tried to reproduce this on current main (well past v0.20.2) using an empty build (VLLM_TARGET_DEVICE=empty) in an environment where current_platform resolves to UnspecifiedPlatform (no CUDA/ROCm/CPU/XPU detected).

Directly instantiating SiluAndMul under a manually-set vllm_config context no longer raises AttributeError on torch.ops._C.silu_and_mul. dispatch_forward now correctly falls back to forward_native when the op isn't enabled() for the current platform, rather than defaulting to forward_cuda.

This looks like it was resolved by unrelated CustomOp dispatch changes possibly #32806 or #30547 rather than a targeted fix for this issue. Can someone confirm this is no longer reproducible on main and close if so?
Happy to provide full repro script if useful.
