### ISSUE TITLE
[Bug, V1]: Service launch failed with v1 code and custom models

### ISSUE THREAD

**Issue by PYNing** [vllm-project/vllm#11055]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-125-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090
GPU 2: NVIDIA GeForce RTX 4090
GPU 3: NVIDIA GeForce RTX 4090
GPU 4: NVIDIA GeForce RTX 4090
GPU 5: NVIDIA GeForce RTX 4090
GPU 6: NVIDIA GeForce RTX 4090
GPU 7: NVIDIA GeForce RTX 4090

Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          96
On-line CPU(s) list:             0-95
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 5318Y CPU @ 2.10GHz
CPU family:                      6
Model:                           106
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
Stepping:                        6
Frequency boost:                 enabled
CPU max MHz:                     2101.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       2.3 MiB (48 instances)
L1i cache:                       1.5 MiB (48 instances)
L2 cache:                        60 MiB (48 instances)
L3 cache:                        72 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pyzmq==26.2.0
[pip3] torch==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.46.3
[pip3] triton==3.1.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.4.post2.dev237+g2a56e126
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PXB     PXB     PXB     SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     0-23,48-71      0               N/A
GPU1    PXB      X      PXB     PXB     SYS     SYS     SYS     SYS     PIX     PIX     SYS     SYS     0-23,48-71      0               N/A
GPU2    PXB     PXB      X      PIX     SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     0-23,48-71      0               N/A
GPU3    PXB     PXB     PIX      X      SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     0-23,48-71      0               N/A
GPU4    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    SYS     SYS     NODE    NODE    24-47,72-95     1               N/A
GPU5    SYS     SYS     SYS     SYS     NODE     X      PXB     PXB     SYS     SYS     PXB     PXB     24-47,72-95     1               N/A
GPU6    SYS     SYS     SYS     SYS     NODE    PXB      X      PXB     SYS     SYS     PIX     PIX     24-47,72-95     1               N/A
GPU7    SYS     SYS     SYS     SYS     NODE    PXB     PXB      X      SYS     SYS     PXB     PXB     24-47,72-95     1               N/A
NIC0    PXB     PIX     PXB     PXB     SYS     SYS     SYS     SYS      X      PIX     SYS     SYS
NIC1    PXB     PIX     PXB     PXB     SYS     SYS     SYS     SYS     PIX      X      SYS     SYS
NIC2    SYS     SYS     SYS     SYS     NODE    PXB     PIX     PXB     SYS     SYS      X      PIX
NIC3    SYS     SYS     SYS     SYS     NODE    PXB     PIX     PXB     SYS     SYS     PIX      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3

NVIDIA_VISIBLE_DEVICES=all
NVIDIA_REQUIRE_CUDA=cuda>=12.1 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526
NCCL_VERSION=2.17.1-1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_PRODUCT_NAME=CUDA
CUDA_VERSION=12.1.1
CUDA_VISIBLE_DEVICES=4
CUDA_VISIBLE_DEVICES=4
LD_LIBRARY_PATH=/usr/local/lib/python3.10/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
VLLM_USE_V1=1
CUDA_MODULE_LOADING=LAZY
```

</details>

### 🐛 Describe the bug

Version：0.6.4.post2.dev237+g2a56e126

I start service for my custom models with the code following（Work fine with V0.5.4 & V0 code）：
```Python
from vllm import ModelRegistry
import runpy
import argparse


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=str)
    args, unknow = parser.parse_known_args()
    return args

def model_registry(model_path):
    import sys
    sys.path.append(model_path)
    from modeling_llava_xx import XXCausalLM
    ModelRegistry.register_model("XXCausalLM", XXCausalLM)


if __name__ == "__main__":
    args = parse_args()
    model_registry(args.model)
    runpy.run_module('vllm.entrypoints.openai.api_server', run_name="__main__")
```
For V1，I got an error, which occur at **starting the engine process**：
```Text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 128, in _main
    self = reduction.pickle.load(from_parent)
TypeError: _LazyConfigMapping.__init__() missing 1 required positional argument: 'mapping'
ERROR 12-10 06:48:11 core.py:199] EngineCoreProc failed to start.
ERROR 12-10 06:48:11 core.py:199] Traceback (most recent call last):
ERROR 12-10 06:48:11 core.py:199]   File "/usr/local/lib/python3.10/dist-packages/vllm/v1/engine/core.py", line 193, in wait_for_startup
ERROR 12-10 06:48:11 core.py:199]     raise RuntimeError("EngineCoreProc failed to start.")
ERROR 12-10 06:48:11 core.py:199] RuntimeError: EngineCoreProc failed to start.
Traceback (most recent call last):
  File "/models/online_infer.py", line 24, in <module>
    runpy.run_module('vllm.entrypoints.openai.api_server', run_name="__main__")
  File "/usr/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 693, in <module>
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 659, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 116, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 149, in build_async_engine_client_from_engine_args
    engine_client = build_engine()
  File "/usr/local/lib/python3.10/dist-packages/vllm/v1/engine/async_llm.py", line 104, in from_engine_args
    return cls(
  File "/usr/local/lib/python3.10/dist-packages/vllm/v1/engine/async_llm.py", line 71, in __init__
    self.engine_core = EngineCoreClient.make_client(
  File "/usr/local/lib/python3.10/dist-packages/vllm/v1/engine/core_client.py", line 46, in make_client
    return AsyncMPClient(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/v1/engine/core_client.py", line 211, in __init__
    super().__init__(*args, asyncio_mode=True, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/v1/engine/core_client.py", line 147, in __init__
    self.proc = EngineCoreProc.make_engine_core_process(
  File "/usr/local/lib/python3.10/dist-packages/vllm/v1/engine/core.py", line 241, in make_engine_core_process
    EngineCoreProc.wait_for_startup(proc, ready_path)
  File "/usr/local/lib/python3.10/dist-packages/vllm/v1/engine/core.py", line 200, in wait_for_startup
    raise e
  File "/usr/local/lib/python3.10/dist-packages/vllm/v1/engine/core.py", line 193, in wait_for_startup
    raise RuntimeError("EngineCoreProc failed to start.")
RuntimeError: EngineCoreProc failed to start.
Exception ignored in: <function AsyncLLM.__del__ at 0x7f39b2d6e4d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/vllm/v1/engine/async_llm.py", line 82, in __del__
    self.shutdown()
  File "/usr/local/lib/python3.10/dist-packages/vllm/v1/engine/async_llm.py", line 117, in shutdown
    self.engine_core.shutdown()
AttributeError: 'AsyncLLM' object has no attribute 'engine_core'
```

Here is my debug info：
（1）I sure my custom model works fine with offline inference & V1 Code
（2）I try run `EngineCoreProc.run_engine_core()`, and the custom model can be loaded successfully（maybe it was introduced 
 by the feature `frontend_multiprocessing`）
（3）To be precise, the crash occurred when the child process was deserializing parameters, and `_LazyConfigMapping` was missing its initialization parameter mapping. But I don’t know the deserialization mechanism here.
（4）Now I have to add model_registry code in `run_engine_core()` in VLLM for registing custom model in new process，and hack `transformers` lib for allowing init `_LazyConfigMapping` with no mapping, then the service can be launched successfully.

Sorry, it is not convenient for me to provide specific reproduction code. I suggest you add unit tests in this scene to find problems.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by ltcs11** [comment]
Why is this issue closed? Did you solved it yet？
I have also encountered this problem. Currently i'm using vllm==0.6.4.post1 from  pip and try to get a llama3 serving.

**Comment by levulinh** [comment]
The issue still persists in v0.7.1 with phi-4 model.

**Comment by kcz358** [comment]
This issue still persists in the latest main on my custom model when `-tp` > 1. The temporary solution is to hack the transformers _LazyConfigMapping. Anyone knows how to solve it without hacking?

**Comment by surak** [comment]
This is happening now with any model on 0.8.1

**Comment by fclearner** [comment]
> > This issue still persists in the latest main on my custom model when `-tp` > 1. The temporary solution is to hack the transformers _LazyConfigMapping. Anyone knows how to solve it without hacking?
> 
> +1, so sad

+1, hope it can be fixed!

**Comment by youkaichao** [comment]
> This issue still persists in the latest main on my custom model when `-tp` > 1. The temporary solution is to hack the transformers _LazyConfigMapping. Anyone knows how to solve it without hacking?

please check https://docs.vllm.ai/en/latest/contributing/model/registration.html#out-of-tree-models . registering custom models should be done via plugin now.

**Comment by youkaichao** [comment]
> _LazyConfigMapping was missing its initialization parameter mapping. But I don’t know the deserialization mechanism here.

usually this is because the `config.py` in your model repo contains `CONFIG_MAPPING`.

If you have `from transformers import CONFIG_MAPPING` at the top of your file, and reference `CONFIG_MAPPING` in some functions, this error can happen.

the solution might be, move `from transformers import CONFIG_MAPPING` inside the function using it.

**Comment by youkaichao** [comment]
cc @njhill this is another example of the problems when we try to serialize the huggingface config.

**Comment by long8v** [comment]
> the solution might be, move from transformers import CONFIG_MAPPING inside the function using it.

this works! thanks
