### PR TITLE
[Bugfix][Core] Restore constructor-only custom encoder cache manager support

### PR DESCRIPTION
**Pull request by waizuichougou**
## Purpose

[PR #51251](https://github.com/vllm-project/vllm/pull/51251) exposed custom encoder cache manager configuration through `EngineArgs` for online and offline inference and changed Scheduler to call `create_manager()` unconditionally. The underlying custom manager extension hooks were introduced by [PR #48218](https://github.com/vllm-project/vllm/pull/48218).

However, the same PR explicitly promised compatibility with custom managers that only implement:

```python
__init__(cache_size)
```

and optionally support:

```python
from_vllm_config(...)
```

Those managers currently cause EngineCore initialization to fail with:

```text
AttributeError:
type object 'CustomEncoderCacheManager'
has no attribute 'create_manager'
```

This change centralizes manager construction and supports all three construction paths:

- `from_vllm_config`;
- `create_manager`;
- the legacy `cache_size` constructor.

The default built-in encoder cache manager behavior is unchanged.

## Test Plan

```bash
pytest -q \
  tests/v1/core/test_encoder_cache_manager.py \
  tests/v1/core/test_scheduler.py \
  --disable-warnings

pre-commit run --files \
  vllm/v1/core/encoder_cache_manager.py \
  vllm/v1/core/sched/scheduler.py \
  tests/v1/core/test_encoder_cache_manager.py
```

## Reproduction

The custom manager must be importable in the serving environment and implement
the legacy constructor interface, for example `__init__(cache_size)`, without
implementing `create_manager`. Other scheduler-consumed manager methods are
omitted from this example for brevity:

```bash
vllm serve <MODEL_ID_OR_PATH> \
  --ec-manager-config \
  '{"encoder_cache_manager_cls":"your_package.ConstructorOnlyManager"}' \
  --tensor-parallel-size 1 \
  --enforce-eager \
  --max-model-len 128 \
  --max-num-seqs 1 \
  --max-num-batched-tokens 128 \
  --gpu-memory-utilization 0.2
```

Before this change, the command fails during EngineCore initialization with:

```text
AttributeError: type object 'ConstructorOnlyManager' has no attribute 'create_manager'
```

After this change, the server starts successfully and accepts health checks and
completion requests.

Validation environment:

- a single-GPU serving instance;
- a supported decoder-only model;
- online `vllm serve`;
- an external constructor-only encoder cache manager;
- `/health`;
- `/v1/completions`.

## Test Result

```text
170 passed, 15 warnings
pre-commit: all hooks passed
```

Before the change, the same online configuration failed during EngineCore/Scheduler initialization with `AttributeError: ... has no attribute 'create_manager'`.

After the change, the server started successfully and a completion request returned HTTP 200.

No model evaluation is required because this change only affects encoder cache manager construction and does not change model computation, sampling, or output semantics.

## Duplicate-work check

No open vLLM PR was found addressing this construction compatibility regression.

- [PR #51228](https://github.com/vllm-project/vllm/pull/51228) fixes encoder-cache slot release accounting, not manager construction.
- [PR #48218](https://github.com/vllm-project/vllm/pull/48218) introduced the extension hooks but does not fix this regression.

## AI Assistance

AI assistance was used for code implementation and test orchestration.

### CODE REVIEW

**Comment by waizuichougou** [comment]
Hi @njhill, this PR fixes a deterministic compatibility regression introduced by #51251. That PR documented support for constructor-only custom encoder cache managers, but the Scheduler unconditionally calls `create_manager()`, causing initialization to fail with `AttributeError` for managers that only implement `__init__(cache_size)`.
This change restores the documented construction paths while preserving the existing built-in behavior. Could you please take a look when you have time? Thank you!
