### PR TITLE
[Bugfix] Restore portable all2all backend default

### PR DESCRIPTION
**Pull request by vllm-agent**
Fixes the post-merge regression introduced by #53311 by restoring `allgather_reducescatter` as the portable default. Users can still opt into `flashinfer_nvlink_one_sided` explicitly.

Post-merge evidence:
- [main #85642 L4 distributed](https://buildkite.com/vllm/ci/builds/85642#01a03df5-c395-4c24-83d2-cae35569ecb0): `No Unquantized MoE backend supports the deployment configuration`
- [main #85646 L4 LoRA TP](https://buildkite.com/vllm/ci/builds/85646#01a03e0a-5b76-4bb7-84e1-d4f65e6dbd0e): `Fused MoE LoRA with EP currently only supports allgather_reducescatter, got flashinfer_nvlink_one_sided`
- [main #85651 MI300 DP](https://buildkite.com/vllm/ci/builds/85651#01a03e5c-e4b3-40a6-9f75-4da44eb07211): repeated PowerMoE engine initialization failures because the one-sided backend is unavailable
- [main #85674 L4 PP+DP](https://buildkite.com/vllm/ci/builds/85674#01a03efc-8fe1-464f-91bb-faaf01de575b): the default one-sided manager does not implement the PP dispatch path

The source PR's selected CI covered four H200 jobs only; no L4 or MI300 job exercised the changed default.

A unit test now pins the portable default.

Testing:
- `python3 -m py_compile vllm/config/parallel.py tests/test_config.py`
- `git diff --check`
- Full pytest collection was unavailable locally because the checkout has no test dependencies (`numpy` missing).

### CODE REVIEW

**Comment by khluu** [comment]
Targeted validation at exact head `4848ea8ada68c335e3bccfe141cbc9f632674bc4`:

- [#85699](https://buildkite.com/vllm/ci/builds/85699) is invalid evidence: bootstrap rejected derived AMD mirror keys before any test ran.
- [#85700](https://buildkite.com/vllm/ci/builds/85700) passed bootstrap and rendered six exact NVIDIA lanes, but a later full `/ci` run superseded/canceled them before tests.
- [#85703](https://buildkite.com/vllm/ci/builds/85703) was likewise superseded/canceled at bootstrap before tests.
- [#85705](https://buildkite.com/vllm/ci/builds/85705) is the active full exact-head run. It has rendered all affected NVIDIA and MI300 lanes, including H200 DSv4, L4/MI300 Nixl + DP Basic/LoRA/Model Runner, L4 2-node/Torchrun, B200 PCP, and B200/MI300 spec-decode.

Merge recommendation remains gated on terminal exact passes; resolution additionally requires exact post-merge main confirmation.

— Sherlock, Kevin Luu’s CI-monitoring agent

**Comment by AndreasKaratzas** [comment]
@khluu Can we merge this?
