### PR TITLE
[Bugfix] Set use_mha=False in EagleMistralLarge3Model.__init__

### LINKED ISSUE #43298: [Bug]: EagleMistralLarge3Model crashes with AttributeError: 'use_mha' on vLLM 0.21.0
## Environment

- **vLLM version:** 0.21.0
- **Model:** `mistralai/Mistral-Large-3-675B-Instruct-2512` with Eagle speculative decoding
- **Hardware:** 8x H200 NVL, TP=8

```
(APIServer pid=1) INFO 05-21 08:22:26 [utils.py:240] non-default args: {'model_tag': 'mistralai/Mistral-Large-3-675B-Instruct-2512-NVFP4', 'enable_auto_tool_choice': True, 'tool_call_parser': 'mistral', 'model': 'mistralai/Mistral-Large-3-675B-Instruct-2512-NVFP4', 'tokenizer_mode': 'mistral', 'served_model_name': ['mistral-large-3-675b-instruct-2512'], 'config_format': 'mistral', 'load_format': 'mistral', 'tensor_parallel_size': 8, 'speculative_config': {'model': 'mistralai/Mistral-Large-3-675B-Instruct-2512-Eagle', 'num_speculative_tokens': 3, 'method': 'eagle', 'max_model_len': '16384'}}
```

## Description

`EagleMistralLarge3Model` fails during weight loading with:

```
File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 1355, in load_weights
    if self.use_mha:
       ^^^^^^^^^^^^
AttributeError: 'EagleMistralLarge3Model' object has no attribute 'use_mha'
```

This worked in vLLM 0.19.x / 0.20.2 and regressed in 0.21.0.

## Root Cause

PR #16383 moved `load_weights` from `DeepseekV2ForCausalLM` to `DeepseekV2Model`, which now references `self.use_mha`. `DeepseekV2Model.__init__` sets this attribute, but `EagleMistralLarge3Model.__init__` calls `nn.Module.__init__(self)` directly instead of `super().__init__()`, so `use_mha` is never initialized.

This is the same class of bug fixed in #37232 (missing `aux_hidden_state_layers`). The underlying fragility — bypassing the parent `__init__` — was flagged by reviewers at the time.

## How to Reproduce

```bash
vllm serve mistralai/Mistral-Large-3-675B-Instruct-2512 \
  --speculative-config '{"model": "mistralai/Mistral-Large-3-675B-Instruct-2512-Eagle", "num_speculative_tokens": 3, "method": "eagle"}'
```

## Suggested Fix

Add `self.use_mha = False` to `EagleMistralLarge3Model.__init__` in `vllm/model_executor/models/mistral_large_3_eagle.py`. Mistral Large 3 uses MLA, so this is always `False`.

Longer term, the bypassed `super().__init__()` pattern will keep causing these regressions whenever `DeepseekV2Model.__init__` gains new attributes.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by HumphreySun98**
## Purpose

Fixes #43298.

\`EagleMistralLarge3Model\` (in \`vllm/model_executor/models/mistral_large_3_eagle.py\`) calls \`nn.Module.__init__(self)\` directly to bypass \`DeepseekV2Model.__init__\` and customize layer construction. PR #16383 then moved \`load_weights\` from \`DeepseekV2ForCausalLM\` to \`DeepseekV2Model\`; the moved \`load_weights\` reads \`self.use_mha\`, which \`DeepseekV2Model.__init__\` would set but \`EagleMistralLarge3Model.__init__\` never does. Result on vLLM 0.21.0:

\`\`\`
File "vllm/model_executor/models/deepseek_v2.py", line 1355, in load_weights
    if self.use_mha:
       ^^^^^^^^^^^^
AttributeError: 'EagleMistralLarge3Model' object has no attribute 'use_mha'
\`\`\`

Mistral Large 3 uses MLA, so the value should always be \`False\`. This PR sets \`self.use_mha = False\` explicitly in \`EagleMistralLarge3Model.__init__\`, right next to the existing \`self.aux_hidden_state_layers = ()\` line.

This mirrors the exact pattern of #37232, which previously added \`self.aux_hidden_state_layers\` to the same \`__init__\` for the same class of bug (parent-init bypass causing a missing attribute that inherited \`load_weights\` reads).

### Duplicate-work check

Per \`AGENTS.md\`:

\`\`\`
gh issue view 43298 --repo vllm-project/vllm --comments
gh pr list --repo vllm-project/vllm --state open --search "43298 in:body"
gh pr list --repo vllm-project/vllm --state open --search "EagleMistralLarge3"
gh pr list --repo vllm-project/vllm --state open --search "use_mha mistral"
\`\`\`

No other open PR addresses #43298. The lone issue comment was an AI-generated proposal with no PR opened.

### Why a 1-line constant rather than mirroring DeepseekV2Model's runtime check

\`DeepseekV2Model.__init__\` computes \`use_mha\` from the head dims:

\`\`\`python
self.use_mha = config.model_type == "deepseek" or all(
    dim == 0 for dim in (qk_nope_head_dim, qk_rope_head_dim)
)
\`\`\`

For Mistral Large 3 Eagle, the draft model's config has non-zero \`qk_nope_head_dim\` / \`qk_rope_head_dim\` (it is an MLA head) and is not \`model_type == "deepseek"\`, so this evaluates to \`False\` deterministically. Hard-coding \`False\` is consistent with the surrounding constants in this Eagle-specific subclass and matches the minimal-fix shape that #37232 established for the same file.

## Test Plan

The reporter (in #43298) has the only known SM-class hardware to run the model end-to-end (8×H200, Mistral-Large-3-675B with Eagle draft, TP=8). On any environment without that:

1. Static check that \`use_mha\` is now assigned in \`EagleMistralLarge3Model.__init__\`:

\`\`\`bash
python -c "import inspect; from vllm.model_executor.models.mistral_large_3_eagle import EagleMistralLarge3Model; assert 'self.use_mha' in inspect.getsource(EagleMistralLarge3Model.__init__)"
\`\`\`

2. Lint:

\`\`\`bash
ruff check vllm/model_executor/models/mistral_large_3_eagle.py
ruff format --check vllm/model_executor/models/mistral_large_3_eagle.py
\`\`\`

3. End-to-end (asked the reporter to verify on the original repro; will update if they report back before merge):

\`\`\`bash
vllm serve mistralai/Mistral-Large-3-675B-Instruct-2512 \\
  --speculative-config '{"model": "mistralai/Mistral-Large-3-675B-Instruct-2512-Eagle", "num_speculative_tokens": 3, "method": "eagle"}'
\`\`\`

No new automated test is added: \`EagleMistralLarge3ForCausalLM\` is marked \`is_available_online=False\` in \`tests/models/registry.py\` (with the comment \"TODO: revert once figuring out OOM in CI\"), so existing \`test_initialization.py\` parametrization already skips this arch. Adding a dedicated mocked-init test for one attribute assignment seemed lower-value than matching the precedent in #37232, which fixed the same class of bug in the same file and merged with no new test. Happy to add a guarded mocked test if a maintainer prefers.

## Test Result

\`\`\`
$ ruff check vllm/model_executor/models/mistral_large_3_eagle.py
All checks passed!
$ ruff format --check vllm/model_executor/models/mistral_large_3_eagle.py
1 file already formatted
$ python -c "import inspect; from vllm.model_executor.models.mistral_large_3_eagle import EagleMistralLarge3Model; assert 'self.use_mha' in inspect.getsource(EagleMistralLarge3Model.__init__); print('use_mha assigned: OK')"
use_mha assigned: OK
\`\`\`

Diff:

\`\`\`diff
@@ -75,6 +75,9 @@ class EagleMistralLarge3Model(DeepseekV2Model):
         )
         self.norm = RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
         self.aux_hidden_state_layers: tuple[int, ...] = ()
+        # Mistral Large 3 uses MLA, not MHA. Set explicitly because __init__
+        # bypasses DeepseekV2Model.__init__, whose load_weights reads self.use_mha.
+        self.use_mha = False
         self.make_empty_intermediate_tensors = make_empty_intermediate_tensors_factory(
             ["hidden_states", "residual"], config.hidden_size
         )
\`\`\`

---

## AI assistance disclosure

This change was AI-assisted (Claude). I (the submitter) reviewed every line, ran the static checks above, and stand behind the change end-to-end.

### CODE REVIEW

**Comment by HumphreySun98** [comment]
Good catch — confirmed: `DeepseekV2Model.load_weights` reads both `self.use_mha` (line 1355) and `self.num_redundant_experts` (line 1373). Pushed [aebd4e0](https://github.com/vllm-project/vllm/pull/43621/commits/aebd4e0) initializing `self.num_redundant_experts` from `vllm_config.parallel_config.eplb_config.num_redundant_experts`, mirroring the parent's `__init__` (`deepseek_v2.py:1264-1266`).

I also re-grepped the full `load_weights` body — those two plus `self.config` and `self.named_parameters()` (inherited from nn.Module) are the only `self.X` it touches; nothing else missing.

Local `pre-commit run --files vllm/model_executor/models/mistral_large_3_eagle.py` is clean (ruff, ruff format, mypy, SPDX, typos all passed).

For the failing checks: `pre-run-check` is gated on a `ready`/`verified` label or ≥4 merged PRs by the author, and the failing readthedocs build polls that same check via `docs/pre_run_check.sh` — not a code issue. Waiting on a maintainer to trigger CI.

**Comment by HumphreySun98** [comment]
Friendly bump — this is a 3-line regression fix (mirrors PR #37232's exact pattern in the same file/init) and has been open a week without triage. Happy to address any feedback. CI is gated on `pre-run-check` (label policy), so until a maintainer adds `ready` the buildkite suite can't run, but local pre-commit and the static check both pass.

**Comment by mamorett** [comment]
Guys, is there any way to get this merged ? Many thanks :)

**Comment by HumphreySun98** [comment]
Thanks for the +1, @mamorett — confirms there's real downstream demand beyond the original reporter.

PR is ready and has been for 2 weeks: 3-line regression fix that mirrors #37232's exact pattern in the same file/`__init__` (parent-init-bypass + missing attribute that inherited `load_weights` reads). Local `pre-commit` (ruff / ruff format / mypy / SPDX / typos) all pass; only failing CI is `pre-run-check`, which is the label-policy gate, not a code issue.

@ywang96 — would you be willing to take a quick look? You merged the most-similar predecessor #43482 (Eagle/Deepseek bugfix shape) and this PR follows the same pattern exactly. Adding the `ready` label would let buildkite actually run on the change.

**Comment by HumphreySun98** [comment]
Bumping again — @ywang96 since you merged the most-similar precedent #43482 (Eagle/Deepseek bugfix), this PR follows the exact same shape: a missing parent-init attribute that inherited `load_weights` reads.

Patch is 3 lines in `vllm/model_executor/models/mistral_large_3_eagle.py` (`use_mha = False` + `num_redundant_experts = ...`), mirroring the pattern of merged predecessor #37232 in the same file. Local pre-commit (ruff/mypy/SPDX/typos) all clean. Only failing CI is `pre-run-check` which is the label gate, not a code issue.

External user @mamorett also asked for this above — there's real downstream demand. Would appreciate a quick look or the `ready` label.

**Comment by ywang96** [comment]
I turned on ready label - also tagging folks from Mistral to take a look @juliendenize, thanks!

**Comment by HumphreySun98** [comment]
> I turned on ready label - also tagging folks from Mistral to take a look @juliendenize, thanks!

Thank you @ywang96, much appreciated. 

@juliendenize — for context, this is a 3-line init fix mirroring PR #37232's pattern in the same file. The `use_mha = False` and `num_redundant_experts` setup are needed because 、`EagleMistralLarge3Model.__init__` calls `nn.Module.__init__(self)` directly (bypassing `DeepseekV2Model.__init__`) but inherits `load_weights` from that parent, which reads both attributes. 

Happy to provide more context or run any verification on the change.

**Review by juliendenize — APPROVED** [review]
The implem looks good to me thanks for the contribution !

We should find a way to avoid this regression that keeps coming back, I noticed that you mentioned the current test is disabled, have you tried enabling it to see if the OOM issue is still here ?

Would be nice to have :smile:

**Comment by HumphreySun98** [comment]
> The implem looks good to me thanks for the contribution !
> 
> We should find a way to avoid this regression that keeps coming back, I noticed that you mentioned the current test is disabled, have you tried enabling it to see if the OOM issue is still here ?
> 
> Would be nice to have 😄

Thanks @juliendenize! On the regression guard — I dug into the OOM and wrote a test:

**Why the existing test OOMs**: `test_initialization.py`'s `dummy_hf_overrides` shrink only reaches the *target* model. The Eagle *draft* `ModelConfig` is built internally in `SpeculativeConfig` with its own `hf_overrides` (speculative.py:692), so the draft instantiates at full 675B dims and OOMs even small CI GPUs. Flipping `is_available_online=True` alone won't fix it.

**What I wrote instead**: a CPU-only regression guard (`tests/models/test_eagle_mistral_large_3_init.py`, `@pytest.mark.cpu_test`) that constructs `EagleMistralLarge3Model` with all heavy submodules mocked (no GPU, no distributed, no download — runs in ~8s) and asserts `use_mha` and `num_redundant_experts` are set after `__init__`. 

Verified locally: passes as-is, and I confirmed via negative control that removing either assignment makes it fail — so it genuinely catches this regression class (the one that recurred in #37232 and here).

Happy to push it into this PR (will re-request your review) or land it as a follow-up right after this merges — whichever you prefer. 😄

**Comment by juliendenize** [comment]
@HumphreySun98 
Think it would be a nice follow-up to see how to test that but not sure mocking the model is the right way to go. I'd say that having this one merged would already be nice to fix instantiation on main !

**Comment by HumphreySun98** [comment]
> @HumphreySun98 Think it would be a nice follow-up to see how to test that but not sure mocking the model is the right way to go. I'd say that having this one merged would already be nice to fix instantiation on main !

Sounds good — let's get this one in to fix instantiation on main, and I'll open a follow-up for the regression test. Fair point on mocking; I'll explore a non-mocked approach there (e.g. shrinking the draft config so the real `test_initialization.py` path can cover it, per the speculative.py:692 finding) and we can iterate on the right shape in that PR.

Thanks again for the review! Wish you a wonderful day!🙏

**Comment by HumphreySun98** [comment]
@ywang96 — juliendenize (Mistral) has approved the implementation and is happy to merge this now with the test tracked as a follow-up. The only remaining gate is a write-access approval. The 3 red CI jobs are unrelated (AMD api-server infra, a 
cpu-gen timeout/exit-124 flake, and a stale readthedocs build — pre-run-check itself now passes); happy to retry or rebase if useful. Could you give the final approval when you have a moment?

Thank you so much and wish you a wonderful day!

**Comment by HumphreySun98** [comment]
Closing — #45217 landed the same fix (both `use_mha` and `num_redundant_experts`, same parent-init-bypass root cause) along with a regression test, so main is fixed and the follow-up test discussed above is largely covered as well. After rebasing, the only remaining delta here would be downgrading main's dynamic `use_mha` computation to a hardcoded constant — not worth merging.

Note for triage: #44846 was a duplicate of #43298, so #43298 can now be closed too.

One thing #45217 did *not* address: the registry still has `is_available_online=False` with `TODO: revert once figuring out OOM in CI` for this arch. Root cause (from the investigation above): `dummy_hf_overrides`' shrink only reaches the target model — the draft `ModelConfig` is built internally in `SpeculativeConfig` with its own `hf_overrides` (speculative.py:692), so the Eagle draft instantiates at full 675B dims. I'll open a follow-up PR threading the shrink into the draft config so the real `test_initialization.py` path can cover spec-decode archs — the non-mocked test @juliendenize asked for.

Thanks @juliendenize and @ywang96 for the reviews — see you on the next one. 🙂
