### PR TITLE
[Misc] [CI] Fix CI failure caught after merge

### PR DESCRIPTION
**Pull request by cadedaniel**
```
FAILED spec_decode/e2e/test_correctness.py::test_spec_decode_e2e_logical_flow[1-1-test_llm_kwargs0-per_test_common_llm_kwargs0-common_llm_kwargs0] - TypeError: Worker.__init__() missing 1 required positional argument: 'load_config'

FAILED spec_decode/e2e/test_correctness.py::test_spec_decode_e2e_logical_flow[1-1-test_llm_kwargs0-per_test_common_llm_kwargs1-common_llm_kwargs0] - TypeError: Worker.__init__() missing 1 required positional argument: 'load_config'
```

Caused by merge race between https://github.com/vllm-project/vllm/pull/4097 and https://github.com/vllm-project/vllm/pull/3894

### CODE REVIEW

**Comment by cadedaniel** [comment]
the AMD test agent is hung for some reason; I used this CI run to discover this https://buildkite.com/vllm/ci/builds/4916#_

**Review by youkaichao — APPROVED** [review]
