### PR TITLE
[Bugfix] Don't crash EngineCore when structured output grammar compilation fails

### LINKED ISSUE #43920: [Bug]: V1 structured outputs: a malformed grammar request after a valid one crashes EngineCore
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
PyTorch version: 2.4+ (any)
Is debug build: False

OS: Linux (any)
Python version: 
.12

vLLM Version: confirmed on v0.20.0, v0.20.1, v0.21.0
xgrammar version: 0.2.0
Structured outputs backend (CLI): default `auto`
Engine: V1 (default)
```

</details>

### 🐛 Describe the bug

The V1 `StructuredOutputManager` initializes its backend (`XgrammarBackend` / `GuidanceBackend` / etc.) exactly once per engine process, on the first grammar request that reaches the scheduler, based on that request's `_backend` field. See the explicit comment in `vllm/v1/structured_output/__init__.py`:

```python
# NOTE: We only support a single backend. We do NOT support different
# backends on a per-request basis in V1 (for now, anyway...).
# _backend is set in Processor._validate_structured_output
if self.backend is None:
    backend = request.sampling_params.structured_outputs._backend
    if backend == "xgrammar":
        self.backend = XgrammarBackend(...)
    elif backend == "guidance":
        self.backend = GuidanceBackend(...)
    ...
```

The per-request auto-fallback in `SamplingParams._validate_structured_outputs` runs only on submission of *that* request. If the **first** grammar request has a grammar xgrammar accepts, the fallback chooses xgrammar and `XgrammarBackend` is cached for the lifetime of the engine. **All subsequent** grammar requests then go through `XgrammarBackend.compile_grammar` regardless of what their own auto-fallback would have chosen.

Combined with the fact that `XgrammarBackend.compile_grammar` (`vllm/v1/structured_output/backend_xgrammar.py:89`) has no exception handling around `self.compiler.compile_grammar(...)`, this means: once xgrammar is latched, any later request whose grammar xgrammar rejects at compile time will raise out of the background grammar-compile future, propagate through `_try_promote_blocked_waiting_request` → `EngineCore.run_busy_loop` → `EngineDeadError`, and kill the engine process. All TP workers shut down; the pod restarts.

The TODO comment in `_create_grammar` is aware of this gap:

> *"we still need to handle xgrammar compilation failures, though it should be unlikely as we test that up front as well."*

The "tested up front" claim holds only on the first request through a fresh engine; once the backend is latched, subsequent requests bypass that protection.

#### Reproducer

Server (any V1 + chat model works; small public one used here so the full repro is ~2 minutes including model download and engine init):

```bash
vllm serve Qwen/Qwen2.5-0.5B-Instruct --port 8000 --enforce-eager
# default --structured-outputs-config backend=auto
```

Step 1 — valid grammar (latches `XgrammarBackend` into the engine):

```bash
curl -X POST http://localhost:8000/v1/chat/completions \
  -H 'Content-Type: application/json' \
  -d '{
    "model": "Qwen/Qwen2.5-0.5B-Instruct",
    "messages": [{"role": "user", "content": "x"}],
    "max_tokens": 4,
    "stream": false,
    "structured_outputs": {"grammar": "root ::= \"a\" | \"b\""}
  }'
# expected: HTTP 200
```

Step 2 — malformed EBNF (xgrammar rejects at compile time, kills the engine):

```bash
curl -X POST http://localhost:8000/v1/chat/completions \
  -H 'Content-Type: application/json' \
  -d '{
    "model": "Qwen/Qwen2.5-0.5B-Instruct",
    "messages": [{"role": "user", "content": "x"}],
    "max_tokens": 4,
    "stream": false,
    "structured_outputs": {"grammar": "root ::= \"a\"\nroot ::= \"b\""}
  }'
```

Observed:

```
HTTP 500: {"error":{"message":"EngineCore encountered an issue. See stack trace (above) for the root cause.",...}}
```

Server log:

```
(EngineCore pid=...) ERROR [core.py] EngineCore encountered a fatal error.
  ...
  File ".../vllm/v1/structured_output/__init__.py", line 183, in _create_grammar
    return self.backend.compile_grammar(request_type, grammar_spec)
  File ".../vllm/v1/structured_output/backend_xgrammar.py", line 89, in compile_grammar
    ctx = self.compiler.compile_grammar(grammar_spec)
  File ".../xgrammar/compiler.py", line 320, in compile_grammar
    self._handle.compile_grammar_from_strings(grammar, root_rule_name)
RuntimeError: [...] /project/cpp/grammar_parser.cc:564: EBNF parser error at line 2, column 1: Rule "root" is defined multiple times
EngineDeadError: EngineCore encountered an issue.
```

Any EBNF that xgrammar rejects works; duplicate-root is the shortest. Pod readiness drops and the engine process exits.

#### Ordering matters

If both requests in the reproducer are the malformed one (i.e. you skip Step 1), the bug does **not** fire — the first request's auto-fallback raises `ValueError` in xgrammar's pre-compile check, the fallback latches `_backend="guidance"`, `GuidanceBackend` is cached for the engine lifetime, and the malformed EBNF compiles leniently afterwards. The bug requires (1) a first grammar that xgrammar accepts, then (2) a later grammar that xgrammar rejects.

This ordering subtlety is likely why this failure mode has been intermittent in production-traffic-only reports and difficult to reproduce locally with a single curl.

Both the deprecated `guided_grammar` top-level field (where still accepted) and the current `structured_outputs.grammar` field converge on the same engine path, so the surface used to submit the grammar doesn't matter.

#### Affected versions

Reproduced cleanly on fresh single-instance stock `vllm/vllm-openai` builds:

- `v0.20.0`
- `v0.20.1`
- `v0.21.0`

The relevant source lines in `vllm/v1/structured_output/__init__.py` (the backend lock-in) and `vllm/v1/structured_output/backend_xgrammar.py:89` (the unguarded `compile_grammar` call) are identical across these versions; `xgrammar` is `0.2.0` in all three.

#### Related work

Existing open PRs that target this exact class of bug:

- `#37642` — `[Bugfix] Fix engine crash when structured output grammar compilation fails with auto backend`. Catches the exception in `_try_promote_blocked_waiting_request`, introduces a `FinishReason.VALIDATION` to surface the failure as 400. Status `needs-rebase`. **One concern:** the PR catches only `except ValueError`, but the xgrammar `compile_grammar_from_strings` binding raises `RuntimeError` (verified with `xgr.Grammar.from_ebnf("root ::= \"a\"\nroot ::= \"b\"")` and in the trace above). The unwrapped `Future.result()` re-raises that `RuntimeError` unchanged, so `except ValueError` would not catch the EBNF case shown here. Broadening to `except Exception` (or at least `except (ValueError, RuntimeError)`) would make it cover the full bug class.

- `#30346` — `[Core] Major fix catch backend grammar exceptions (xgrammar, outlines, etc.) in scheduler`. Broader scope, also addresses outlines. Code review flagged correctness issues with how aborted-request info is propagated.

Earlier closely-related fixes that addressed adjacent failure modes but didn't close the latched-backend hole:

- `#28209` — engine crash when `structured_outputs.grammar` is empty string
- `#19270` — `guided_regex` parsing error crashes the server
- `#17313` — clients can crash the openai server with invalid regex
- `#20584` — Handle grammar compilation exceptions gracefully

#### Suggested fix surface

Either:

1. `vllm/v1/structured_output/backend_xgrammar.py:77-122` — wrap `compile_grammar` in `try/except Exception` and either return a sentinel grammar that fails the single request as 400, or fall back to the guidance backend just for that request. This is the most localized fix.

2. `vllm/v1/structured_output/__init__.py` — drop the single-backend-per-engine constraint and instantiate the requested backend per request, so per-request auto-fallback isn't bypassed. Larger architectural change.

Happy to test any patch against the reproducer above.

### PR DESCRIPTION
**Pull request by KKothuri**
## Purpose

Fixes #43920.

A structured-output grammar that fails to compile **after** a valid one has
latched the backend crashes the entire `EngineCore` process, killing all
in-flight requests and restarting the pod.

### Root cause

`StructuredOutputManager` compiles grammars on a background thread and stores a
`Future` on the request. The scheduler resolves it lazily via the
`StructuredOutputRequest.grammar` property, which calls
`Future.result()` inside `_check_grammar_completion()`. That method only catches
`TimeoutError`:

```python
try:
    self._grammar = self._grammar.result(timeout=0.0001)
    self.status = RequestStatus.WAITING
except TimeoutError:
    return False
```

When the backend (e.g. xgrammar) rejects a grammar at compile time it raises a
bare `RuntimeError`, which escapes this method, propagates through
`Scheduler.schedule()` → `EngineCore.run_busy_loop()`, and kills the engine.

The ordering requirement from the issue (a first grammar that xgrammar
*accepts*, then a later one it *rejects*) is exactly why this only shows up
under production traffic: the first request latches `XgrammarBackend` for the
lifetime of the engine, so the per-request auto-fallback that would otherwise
pick a lenient backend is bypassed.

## Changes

**Engine side — stop the crash, fail just the offending request**

- `vllm/v1/structured_output/request.py`: `_check_grammar_completion()` now
  catches compilation exceptions (not only `TimeoutError`) and re-raises them as
  `ValueError`, normalizing the many backend exception types into one.
- `vllm/v1/engine/__init__.py`: add `FinishReason.VALIDATION`. A malformed
  grammar is a client error, not a retryable internal error, so it must not
  reuse `ERROR` (whose documented invariant is "retryable request-level internal
  error … always converted to 500").
- `vllm/v1/core/sched/scheduler.py`: `_try_promote_blocked_waiting_request()`
  catches the `ValueError`, finishes the request as `FINISHED_ERROR`, frees it,
  and buffers an `EngineCoreOutput` carrying `FinishReason.VALIDATION`. The
  buffer is drained in `update_from_output()`. This mirrors the existing
  `failed_kv_load_req_ids` error-emission pattern. The promotion helper keeps its
  `bool` signature; the call site simply checks `request.is_finished()` to avoid
  re-queueing a request that was already failed.

**Serving side — surface a 400 instead of a 500**

- `vllm/entrypoints/openai/engine/protocol.py`: `GenerationError` accepts an
  optional `status_code` (defaults to 500 — fully backward compatible).
- `vllm/entrypoints/utils.py`: `create_error_response()` maps a 400-coded
  `GenerationError` to `BadRequestError`.
- `vllm/entrypoints/openai/engine/serving.py`: `_raise_if_error()` turns
  `finish_reason == "validation"` into a 400 `GenerationError`. `GenerationError`
  is reused rather than introducing a new exception type because it is the one
  error class every serving path (chat / completion / responses / batch / disagg,
  streaming and non-streaming) already catches uniformly.

Result: the offending request returns **400 Bad Request** with a clear message;
the engine stays alive and continues serving other requests.

## Why this is not a duplicate

- **#37642** (open, `needs-rebase`, last updated 2026-05-07) takes the same
  general approach but catches only `except ValueError` in the scheduler. The
  EBNF failures in #43920 surface as `RuntimeError` from xgrammar's
  `compile_grammar_from_strings` binding, which `except ValueError` does **not**
  catch — so that PR would not close this bug class. It also predates the
  `WAITING_FOR_FSM` → `WAITING_FOR_STRUCTURED_OUTPUT_GRAMMAR` rename. This PR
  catches the full exception set at the source (in `_check_grammar_completion`)
  and targets the current status name.
- **#30346** has broader scope (outlines, etc.) and review flagged correctness
  issues with aborted-request propagation. This PR is intentionally narrow:
  it closes the latched-backend hole described in #43920 without touching the
  single-backend-per-engine architecture.

No open PR references #43920.

## Test plan

```bash
# New regression test + adjacent structured-output scheduler tests
.venv/bin/python -m pytest tests/v1/core/test_scheduler.py \
    -k "grammar or structured_output_fsm" -v

# Full suites for the touched areas
.venv/bin/python -m pytest tests/v1/core/test_scheduler.py tests/v1/test_request.py
.venv/bin/python -m pytest tests/v1/structured_output/

# Lint / types as in CI
pre-commit run --files \
  vllm/v1/structured_output/request.py vllm/v1/engine/__init__.py \
  vllm/v1/core/sched/scheduler.py vllm/entrypoints/openai/engine/protocol.py \
  vllm/entrypoints/utils.py vllm/entrypoints/openai/engine/serving.py \
  tests/v1/core/test_scheduler.py
```

New test: `tests/v1/core/test_scheduler.py::test_grammar_compilation_failure_does_not_crash_engine`
drives the real `schedule()` → `update_from_output()` path with a grammar whose
property raises, and asserts the engine does not crash, the request is finished
and freed, and an `EngineCoreOutput` with `FinishReason.VALIDATION` is emitted.

### Results

- `-k "grammar or structured_output_fsm"`: **3 passed**.
- `tests/v1/core/test_scheduler.py` + `tests/v1/test_request.py`: **all pass**
  except one **pre-existing, unrelated** failure
  (`test_async_scheduling_pp_allows_rescheduling_with_output_placeholders`),
  confirmed to fail identically on a clean checkout (a config `ValidationError`
  during model resolution, independent of this change).
- `tests/v1/structured_output/`: **21 passed**.
- `pre-commit` (ruff, ruff-format, mypy, SPDX, etc.): **all hooks pass**.

### Live reproduction (before vs. after)

The two-request server reproducer from the issue was run end-to-end on real
hardware (RTX 5080 / Blackwell SM 12.0, `Qwen/Qwen2.5-0.5B-Instruct`,
`--enforce-eager`, structured-outputs backend `auto`). The **same** reproducer
script was run against the parent commit (`87f12e5c7`, pre-fix) and the fix
commit (`4d2481b1d`); vLLM is an editable install, so the checked-out source is
exactly what the engine runs.

| | Pre-fix (`87f12e5c7`) | Post-fix (`4d2481b1d`) |
|---|---|---|
| Step 1 — valid grammar `root ::= "a" \| "b"` | HTTP 200 (latches `XgrammarBackend`) | HTTP 200 |
| Step 2 — malformed EBNF (duplicate `root`) | **HTTP 500** `InternalServerError` | **HTTP 400** `BadRequestError` |
| `/health` after Step 2 | **no connection — engine dead** | HTTP 200 — engine alive |
| `EngineDeadError` markers in server log | **2** | **0** |
| Step 3 — follow-up valid chat request | **HTTP 000** (server gone) | HTTP 200, normal completion |

Pre-fix crash (root cause, abridged from the engine log):

```
EngineCore encountered a fatal error.
Traceback (most recent call last):
  ) and not self._try_promote_blocked_waiting_request(request):
  File ".../vllm/v1/core/sched/scheduler.py", in _try_promote_blocked_waiting_request
    completed = self._check_grammar_completion()
  File ".../vllm/v1/structured_output/request.py", line 49, in _check_grammar_completion
  File ".../vllm/v1/structured_output/__init__.py", in _create_grammar
    return self.backend.compile_grammar(request_type, grammar_spec)
  File ".../vllm/v1/structured_output/backend_xgrammar.py", line 89, in compile_grammar
    ctx = self.compiler.compile_grammar(grammar_spec)
  File ".../xgrammar/compiler.py", in compile_grammar
    self._handle.compile_grammar_from_strings(grammar, root_rule_name)
RuntimeError: .../grammar_parser.cc:564: EBNF parser error at line 2, column 1: Rule "root" is defined multiple times
...
vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue.
```

Note the escaping exception is a **`RuntimeError`** from xgrammar's C++ binding,
not a `ValueError` — concrete confirmation of why an `except ValueError`-only
approach does not close this bug class.

Post-fix, Step 2 returns:

```json
{"error":{"message":"Structured output grammar compilation failed. Check your grammar, regex, or JSON schema for syntax errors.","type":"BadRequestError","param":null,"code":400}}
```

and the engine stays alive and serves the subsequent valid request (Step 3 → 200).

## Notes

AI assistance (Claude) was used to help investigate and implement this change.
The submitter has reviewed every changed line and is able to defend the change
end-to-end.

### CODE REVIEW

**Comment by KKothuri** [comment]
@russellb — this overlaps with your PR #37642 . The key difference: the EBNF failures in #43920 surface as a RuntimeError from xgrammar, not a ValueError, so catching only ValueError isn't enough. This PR catches the full exception set at the source in _check_grammar_completion and surfaces it as a 400.

I ran the issue's two-request reproducer against both the main branch and this fix. Pre-fix: HTTP 500 + EngineDeadError (engine dies); post-fix: HTTP 400 BadRequestError, engine stays alive and keeps serving. More details are in the PR description.

Could you also add the ready label so the full CI suite runs?
