### ISSUE TITLE
[CI Failure]: async-engine-inputs-utils-worker-config-cpu - multimodal/test_video.py collection error

### ISSUE THREAD

**Issue by Change72** [vllm-project/vllm#50310]
### Name of failing test

`tests/multimodal/test_video.py` — collection error, so none of the 169 selected tests in the shard run.

### Basic information

- [ ] Flaky test
- [X] Can reproduce locally
- [ ] Caused by external libraries (e.g. bug in `transformers`)

### 🧪 Describe the failing test

Buildkite step `Async Engine, Inputs, Utils, Worker, Config (CPU)` fails at its `pytest -v -s -m 'cpu_test' multimodal` command. The failure is at collection time, not in a test body (`site-packages` path prefixes trimmed; full log below):

```text
==================================== ERRORS ====================================
__________________ ERROR collecting multimodal/test_video.py ___________________
multimodal/test_video.py:17: in <module>
    from vllm.models.minimax_m3.common.mm_preprocess import MiniMaxM3VideoBackend
vllm/models/minimax_m3/__init__.py:17: in <module>
    from .nvidia.model import (
vllm/models/minimax_m3/nvidia/model.py:30: in <module>
    from vllm.model_executor.layers.fused_allreduce_gemma_rms_norm import (
vllm/model_executor/layers/fused_allreduce_gemma_rms_norm.py:33: in <module>
    from vllm.compilation.passes.fusion.allreduce_rms_fusion import (
vllm/compilation/passes/fusion/allreduce_rms_fusion.py:16: in <module>
    from vllm.compilation.passes.fusion.rms_quant_fusion import (
vllm/compilation/passes/fusion/rms_quant_fusion.py:121: in <module>
    ): torch.ops._C.rms_norm_static_fp8_quant.default,  # noqa: E501
torch/_ops.py:1392: in __getattr__
    raise AttributeError(
E   AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm_static_fp8_quant'
=========================== short test summary info ============================
ERROR multimodal/test_video.py - AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm_static_fp8_quant'
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
================ 253 deselected, 26 warnings, 1 error in 2.70s =================
```

All references below are against `main` @ `93477454f9`.

**Why the import fails.** `rms_quant_fusion.py:118-131` builds `FUSED_OPS` by dereferencing `torch.ops._C.rms_norm_static_fp8_quant`, `torch.ops._C.fused_add_rms_norm_static_fp8_quant` and `torch.ops._C.rms_norm_dynamic_per_token_quant` at module scope with no availability check, while the entries immediately below and above it are guarded (`rms_norm_per_block_quant` at `:133`, `per_token_group_fp8_quant` at `:94`, `scaled_fp4_quant` at `:97`). Those three ops are registered only in `csrc/libtorch_stable/torch_bindings.cpp:382,388,394`, and that extension is built only when `VLLM_GPU_LANG` is `CUDA` or `HIP` (`CMakeLists.txt:394`), so the ops are present on CUDA and ROCm but absent from the CPU extension. `csrc/cpu/torch_bindings.cpp:601-604` already registers the three ops that `QUANT_OPS` needs against the `placeholder_op` stub defined at `:190` ("Note: just for avoiding importing errors"), but there are no equivalent registrations for the `FUSED_OPS` ones — so this module has never been importable on a CPU build.

Note that `fused_allreduce_gemma_rms_norm.py:32-49` already wraps this import in `try: ... except ImportError:` precisely so the flashinfer fusion path stays optional. The guard does not fire here because the failure is an `AttributeError`, not an `ImportError`.

**Why it surfaced now.** #50092 added the `vllm.models.minimax_m3.common.mm_preprocess` import at `tests/multimodal/test_video.py:17`. That file is marked `pytest.mark.cpu_test` (`:40`), and importing the submodule executes `vllm/models/minimax_m3/__init__.py`, which on non-ROCm platforms imports `.nvidia.model` (`:16-17`) and pulls the whole chain above into a CPU-only job.

**Local reproduction.** On a CPU build, `python -c "import vllm.models.minimax_m3.common.mm_preprocess"` reproduces it: the CPU extension registers `rotary_embedding` and `silu_and_mul`, so import walks the chain above and stops at `rms_quant_fusion.py:121`. On a build with no compiled `_C` at all the chain is the same but it aborts one step earlier, at `matcher_utils.py:32` (`AttributeError: ... has no attribute 'rotary_embedding'`).

**Note on the fix shape.** `rms_quant_fusion.py:155` and `act_quant_fusion.py:65` already assert `key in FUSED_OPS` at pattern-construction time, so populating these entries conditionally (matching `:133`) turns an import-time crash into the existing "unsupported fused rmsnorm+quant op" assertion on platforms that cannot fuse anyway, with no change on CUDA. Adding three more `placeholder_op` defs to `csrc/cpu/torch_bindings.cpp` would also unblock CI but only for the CPU platform, and requires a C++ rebuild.

### 📝 History of failing test

Introduced by df2735ea2e (#50092), merged 2026-07-29 08:24 UTC. Still failing on `main` as of commit `93477454f9`.

The step's `source_file_dependencies` in `.buildkite/test_areas/misc.yaml:340-380` include `tests/multimodal`, so #50092 was in scope for it. The head commit of #50092 carries only `pre-run-check`, `pre-commit`, `DCO`, `Meta Internal-Only Changes Check`, `Summary` and `docs/readthedocs.org:vllm` — there is no `buildkite/ci/pr` status on it — so the step never ran there.

Because the step is gated on those dependencies, it does not run on every PR. Observed instance: build 81106 on #48408, which touches only `vllm/v1/kv_offload/` and `vllm/distributed/kv_transfer/` files and matches the step through the `vllm/v1/` dependency.

<details>
<summary>Logs (build 81106, step <code>async-engine-inputs-utils-worker-config-cpu</code>):</summary>

```text
+++ :test_tube: Command (8/15): pytest -v -s -m cpu_test multimodal
INFO 07-29 18:16:33 [importing.py:53] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
WARNING 07-29 18:16:33 [importing.py:65] Triton is installed, but doesn't include CPU backend. Disabling Triton.
INFO 07-29 18:16:33 [importing.py:88] Triton not installed or not compatible; certain GPU-related functions will not be available.
platform linux -- Python 3.12.13, pytest-9.1.0, pluggy-1.5.0
collected 422 items / 1 error / 253 deselected / 169 selected
==================================== ERRORS ====================================
__________________ ERROR collecting multimodal/test_video.py ___________________
multimodal/test_video.py:17: in <module>
    from vllm.models.minimax_m3.common.mm_preprocess import MiniMaxM3VideoBackend
/opt/venv/lib/python3.12/site-packages/vllm/models/minimax_m3/__init__.py:17: in <module>
    from .nvidia.model import (
/opt/venv/lib/python3.12/site-packages/vllm/models/minimax_m3/nvidia/model.py:30: in <module>
    from vllm.model_executor.layers.fused_allreduce_gemma_rms_norm import (
/opt/venv/lib/python3.12/site-packages/vllm/model_executor/layers/fused_allreduce_gemma_rms_norm.py:33: in <module>
    from vllm.compilation.passes.fusion.allreduce_rms_fusion import (
/opt/venv/lib/python3.12/site-packages/vllm/compilation/passes/fusion/allreduce_rms_fusion.py:16: in <module>
    from vllm.compilation.passes.fusion.rms_quant_fusion import (
/opt/venv/lib/python3.12/site-packages/vllm/compilation/passes/fusion/rms_quant_fusion.py:121: in <module>
    ): torch.ops._C.rms_norm_static_fp8_quant.default,  # noqa: E501
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/opt/venv/lib/python3.12/site-packages/torch/_ops.py:1392: in __getattr__
    raise AttributeError(
E   AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm_static_fp8_quant'
=========================== short test summary info ============================
ERROR multimodal/test_video.py - AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm_static_fp8_quant'
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
================ 253 deselected, 26 warnings, 1 error in 2.70s =================
🚨 Error: The command exited with status 2
```

</details>

### CC List.

@lengrongfu @DarkLight1337 @ProExpertProg @bigPYJ1151 @zou3519

**Comment by njhill** [comment]
Reverting the culprit PR for now in https://github.com/vllm-project/vllm/pull/50313.

**Comment by Change72** [comment]
Permanent fix (guard `FUSED_OPS` behind `hasattr` so the module stays importable on CPU, independent of #50313's revert): https://github.com/vllm-project/vllm/pull/50316

**Comment by njhill** [comment]
Closing since the CI breakage is fixed with the revert
