### PR TITLE
[CI] Initialize ubatch runner in cudagraph unit test

### PR DESCRIPTION
**Pull request by khluu**
## Summary

PR #51700 added `CudaGraphManager.ubatch_runner` and made `capture()` read it, but `test_piecewise_capture_builds_fresh_metadata_for_both_passes` constructs the manager with `__new__` and manually initializes only the state it exercises. The first nightly H200 CUDAGraph run after merge therefore failed before capture with:

```text
AttributeError: 'CudaGraphManager' object has no attribute 'ubatch_runner'
```

Initialize the test double's new dependency to `None`, matching the non-DBO constructor default.

Evidence:

- main/nightly #88743 exact H200 CUDAGraph failure: https://buildkite.com/vllm/ci/builds/88743#01a09f3f-e24f-4da4-9c78-2268343936d6
- culprit PR #51700 exact PR job was blocked and never ran: https://buildkite.com/vllm/ci/builds/88703#01a09db2-6192-4ad4-af3a-f21a1d95db8e

## Duplicate check

I searched open vLLM PR titles/bodies for `ubatch_runner` and `breakable cudagraph`; no existing PR addresses this test failure. This is the narrow repair for a current hard main-CI regression, not a standalone cleanup.

## Validation

- `uv run ... python -m pytest tests/v1/cudagraph/test_breakable_cudagraph.py::test_piecewise_capture_builds_fresh_metadata_for_both_passes -q` — 1 passed
- applicable pre-commit hooks for the changed file — passed
- `git diff --check` — passed

No CUDA device is available locally. The exact H200 CUDAGraph lane must validate the full module on this head.

## AI assistance

AI-assisted. A human maintainer must review the changed line and understand the failure/fix before promotion.

### CODE REVIEW

**Review by njhill — APPROVED** [review]

**Review by tlrmchlsmth — APPROVED** [review]

**Comment by khluu** [comment]
Exact machine validation is terminal green at head `c2a04b4449fc4507b9446d464f6362a3d2c6e82d`:

- Full Buildkite CI #88885 passed.
- H200 CUDAGraph passed all four commands (15 + 16 + 20 + 51 tests). The formerly failing `test_piecewise_capture_builds_fresh_metadata_for_both_passes` passed directly.
- MI250 CUDAGraph also passed.
- Bootstrap, GitHub pre-commit gate, and image passed.

Validation: https://buildkite.com/vllm/ci/builds/88885

The H200 job finished in 29m50s, close to its existing 30-minute budget; #56775 separately owns the CUDAGraph timeout-headroom change. This PR's regression fix itself is exact-green and remains human merge-gated.
