### PR TITLE
[Bugfix] Fix DeepseekV4FP8 Quark MXFP4 crash on list-valued weight

### PR DESCRIPTION
**Pull request by ColinZ22**
## Purpose

Fix an `AttributeError` crash in `DeepseekV4FP8Config._is_quark_mxfp4_ocp` that breaks loading of Quark-quantized checkpoint whose `global_quant_config.weight` is a list.

Per the Quark schema, `weight` is `Optional[Union[QTensorConfig, List[QTensorConfig]]]`, so it can be a dict, a **list** (multiple specs, e.g. NVFP4 with 2-level scale), or `None`. The original code assumed a dict, crashing on the list form:

> vllm/models/deepseek_v4/quant_config.py:125: AttributeError
> E   AttributeError: 'list' object has no attribute 'get'

## Test Plan

Verified against `amd-quark/Qwen3-30B-A3B-nvfp4-quark`, which has a list for `global_quant_config.weight`. `_is_quark_mxfp4_ocp` properly returns False and does not crash. 

---
<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [ ] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [ ] The test plan, such as providing test command.
- [ ] The test results, such as pasting the results comparison before and after, or e2e results
- [ ] (Optional) The necessary documentation update, such as updating `supported_models.md` and `examples` for a new model.
</details>

### CODE REVIEW

**Review by BowenBao — APPROVED** [review]

**Review by fxmarty-amd — APPROVED** [review]
LGTM

@ColinZ22 In the future, please share the PR that introduces such bugs and which test it broke, which test was fixed specifically - it helps with understanding

In this case, this issue was introduced in https://github.com/vllm-project/vllm/pull/48044 that broke `tests/quantization/test_quark.py::[1mtest_nvfp4_wikitext_correctness` that uses `amd-quark/Qwen3-30B-A3B-nvfp4-quark`

**Review by AndreasKaratzas — APPROVED** [review]
LGTM
