### PR TITLE
Update transformers to `v4.55`

### PR DESCRIPTION
**Pull request by hmellor**
Updates to the latest version of Transformers.

Notable changes:
- Transformers backend:
  - Get the `tp_plan` from the config of the base model because it is no longer added to the base model itself post init
  - Add a default mapping from `nn.Linear` to `ReplicatedLinear` to enable weight loaders like `BitsAndBytesModelLoader` to work with models that do not support TP if TP is disabled
  - Decoder modules no longer return `tuple` as of https://github.com/huggingface/transformers/pull/39120 so `return_tuple` has been removed from `PPMissingLayer.forward()`

Enables the proper type hinting introduced by https://github.com/vllm-project/vllm/pull/21913

### CODE REVIEW

**Comment by DarkLight1337** [comment]
What failures are introduced by that PR? From my understanding those test failures also happen on main.

**Comment by hmellor** [comment]
I wasn't aware they were also on main. I assumed they were from that PR because many of them refer to the same configs that were modified.

**Comment by DarkLight1337** [comment]
Well in any case, it's great to fix them anyway

**Comment by DarkLight1337** [comment]
Ok I figured out that some of the failures in that PR are caused by missing `trust_remote_code=True` (because we previously loaded those configs from vLLM directly), let me open a separate PR.

**Comment by hmellor** [comment]
Ok, happy to review once it's open

**Comment by DarkLight1337** [comment]
Opened https://github.com/vllm-project/vllm/pull/21934

**Comment by DarkLight1337** [comment]
Hope this passes now

**Comment by noooop** [comment]
gte-Qwen2-1.5B-instruct hf Implementation does not support v4.54.1

**Comment by hmellor** [comment]
@noooop are you suggesting that we upper bound this model in tests to 4.53.2?

**Comment by noooop** [comment]
> @noooop are you suggesting that we upper bound this model in tests to 4.53.2?

I think we can use transformers==4.53.2 in Language Models Test (Extended Pooling) (Reinstall transformers==4.53.2 in Language Models Test (Extended Pooling)

**Comment by noooop** [comment]
Qwen/Qwen2.5-Math-PRM-7B hf Implementation does not support v4.54.1

suggest rm  marks=[pytest.mark.core_model, pytest.mark.cpu_model]

https://github.com/vllm-project/vllm/blob/28b18cc741e596ea6f9981b8365c4819523fc24b/tests/models/language/pooling/test_reward.py#L73-L79

**Comment by DarkLight1337** [comment]
We should just set max_transformers_version

**Comment by hmellor** [comment]
I'm going to make fixes and push them in batches to minimise the number of times we have to wait for CI. 

- I have fixed the `basic-models-test` locally
- `samplers-test` fixed by https://github.com/huggingface/transformers/pull/39503 will be in Transformers release expected tomorrow
- I have fixed `pipeline-parellelism-test` locally

**Comment by hmellor** [comment]
- I have fixed `pipeline-parellelism-test` locally

**Comment by hmellor** [comment]
@noooop do you know if the Qwen model should work in Transformers 4.55?

**Comment by hmellor** [comment]
As of https://github.com/huggingface/transformers/pull/39339 `PreTrainedModel`s have an `EmbeddingAccessMixin` with the method `set_input_embeddings`.

`Plamo2`, the only model in all of vLLM which actually inherits from `PreTrainedModel`, is failing in multiple tests because `PlamoModel.get_input_embeddings` (takes the `input_ids` and returns the output) clashes with `PreTrainedModel.get_input_embeddings` (takes nothing and returns the layer).

@DarkLight1337 should we cap this model at Transformers 4.53?

**Comment by DarkLight1337** [comment]
Sure

**Comment by DarkLight1337** [comment]
Make sure to update hybrid model tests to check transformers version if needed

**Comment by noooop** [comment]
> @noooop do you know if the Qwen model should work in Transformers 4.55?

Language Models Test (Standard)

FAILED models/language/pooling/test_reward.py::test_prm_models[True-half-Qwen/Qwen2.5-Math-PRM-7B] - AttributeError: 'DynamicCache' object has no attribute 'get_usable_length'. Did you mean: 'get_seq_length'?

**Comment by hmellor** [comment]
I see the error, I was wondering if there had been a fix made in Transformers for this particular model. However it looks like the HF impl is a custom code model so the Qwen team need to update their checkpoint if they want it to work with newer Transformers versions. I've capped the version for this model in our CI.

**Comment by noooop** [comment]
> @noooop do you know if the Qwen model should work in Transformers 4.55?

I have no idea

> gte-Qwen2-1.5B-instruct hf Implementation does not support v4.54.1 <- in Language Models Test (Extended Pooling)

> > @noooop are you suggesting that we upper bound this model in tests to 4.53.2?
> 
> I think we can use transformers==4.53.2 in Language Models Test (Extended Pooling) (Reinstall transformers==4.53.2 in Language Models Test (Extended Pooling)


> Qwen/Qwen2.5-Math-PRM-7B hf Implementation does not support v4.54.1 <- in Language Models Test (Standard)
> 
> suggest rm marks=[pytest.mark.core_model, pytest.mark.cpu_model]
> 
> https://github.com/vllm-project/vllm/blob/28b18cc741e596ea6f9981b8365c4819523fc24b/tests/models/language/pooling/test_reward.py#L73-L79


Why not temporarily move Qwen/Qwen2.5-Math-PRM-7B from Language Models Test (Standard) to Language Models Test (Extended Pooling) and using  transformers==4.53.2 in Language Models Test (Extended Pooling)

**Comment by hmellor** [comment]
We will not be using multiple Transformers versions for testing.

If model vendors choose to use custom models instead of upstreaming them into Transformers it is their responsibility to ensure compatibility with the latest Transformers.

**Comment by hmellor** [comment]
Just pushed a batch of fixes, only expecting the hybrid tests to be failing now

File: tests/models/registry.py [hunk 1]
```diff
@@ -326,8 +325,12 @@ def check_available_online(
...
                                                trust_remote_code=True, v0_only=True),  # noqa: E501
     "Qwen2Model": _HfExamplesInfo("ssmits/Qwen2-7B-Instruct-embed-base"),
-    "Qwen2ForRewardModel": _HfExamplesInfo("Qwen/Qwen2.5-Math-RM-72B"),
-    "Qwen2ForProcessRewardModel": _HfExamplesInfo("Qwen/Qwen2.5-Math-PRM-7B"),
+    "Qwen2ForRewardModel": _HfExamplesInfo("Qwen/Qwen2.5-Math-RM-72B",
+                                           max_transformers_version="4.53",
+                                           transformers_version_reason="HF model uses remote code that is not compatible with latest Transformers"),  # noqa: E501
+    "Qwen2ForProcessRewardModel": _HfExamplesInfo("Qwen/Qwen2.5-Math-PRM-7B",
+                                                  max_transformers_version="4.53",
+                                                  transformers_version_reason="HF model uses remote code that is not compatible with latest Transformers"),  # noqa: E501
```
Comment (noooop) [inline tests/models/registry.py:336]: My point is that vllm correctly loads and executes these models, but when performing accuracy tests compared to hf, it requires hf Implementation 4.53

Comment (hmellor) [reply tests/models/registry.py:336]: I understand, but vLLM's CI is not set up to arbitrarily change dependency versions at test time for reference models which are unmaintained.

The best course of action would be to make PRs in `Qwen/Qwen2.5-Math-RM-72B` and `Qwen/Qwen2.5-Math-PRM-7B` to fix them, but we're not going to block upgrading the Transformers pin waiting for those.

File: tests/models/registry.py [hunk 2]
```diff
@@ -456,7 +459,7 @@ def check_available_online(
                                                       extras={"chat": "Qwen/Qwen-VL-Chat"},  # noqa: E501
                                                       trust_remote_code=True,
                                                       hf_overrides={"architectures": ["QwenVLForConditionalGeneration"]}),  # noqa: E501
-    "Qwen2AudioForConditionalGeneration": _HfExamplesInfo("Qwen/Qwen2-Audio-7B-Instruct"),  # noqa: E501
+    "Qwen2AudioForConditionalGeneration": _HfExamplesInfo("Qwen/Qwen2-Audio-7B-Instruct", min_transformers_version=4.55, transformers_version_reason="HF impl is broken in 4.54"),  # noqa: E501
```
Comment (DarkLight1337) [inline tests/models/registry.py]:
```suggestion
    "Qwen2AudioForConditionalGeneration": _HfExamplesInfo("Qwen/Qwen2-Audio-7B-Instruct", min_transformers_version="4.55", transformers_version_reason="HF impl is broken in 4.54"),  # noqa: E501
```

**Comment by hmellor** [comment]
The hybrid tests should be fixed by https://github.com/huggingface/transformers/pull/39797 (which will hopefully be in a release soon)

**Comment by hmellor** [comment]
The Ernie 4.5 checkpoint contains the old name for the class `Ernie4_5_ForCausalLM` (new name is `Ernie4_5ForCausalLM`) so this test is failing

**Comment by DarkLight1337** [comment]
Let's keep `min_transformers_veresion="4.55"` in case some developers haven't upgraded yet

**Comment by hmellor** [comment]
Ok, I'll make that change in the next batch of commits (I'll let the tests run to completion)

**Comment by zyongye** [comment]
How long can we land this? Need this first before merging gpt-oss changes (#22259)

**Comment by DarkLight1337** [comment]
We just need to get CI to pass

**Review by WoosukKwon — APPROVED** [review]

**Comment by hmellor** [comment]
I understand this was a priority for gpt-oss, I'll work on hotfixiing anything that wasn't fully resolved in CI
