### PR TITLE
Fix AttributeError in Qwen3.5 GDN layers with quantized models

### PR DESCRIPTION
**Pull request by jhsmith409**
## Summary
- Replace `self.in_proj_qkvz.weight.shape[0]` and `self.in_proj_ba.weight.shape[0]` with `sum(self.in_proj_qkvz.output_sizes)` and `sum(self.in_proj_ba.output_sizes)` in both `qwen3_5.py` and `qwen3_next.py`
- `MergedColumnParallelLinear` does not expose a `.weight` attribute when using quantization methods like compressed-tensors/AWQ, causing an `AttributeError` during the forward pass
- The `output_sizes` attribute is always available on `MergedColumnParallelLinear` and provides the same total output dimension needed by the `gdn_in_proj` custom op for shape tracing

## Motivation
This fixes a regression introduced in #36795 where the new `gdn_in_proj` custom op accesses `self.in_proj_qkvz.weight.shape[0]` and `self.in_proj_ba.weight.shape[0]`. With quantized models (e.g., `cyankiwi/Qwen3.5-9B-AWQ-4bit` using compressed-tensors), the `MergedColumnParallelLinear` layer does not have a `.weight` attribute — the weight is managed by the quantization kernel. This causes:

```
AttributeError: 'MergedColumnParallelLinear' object has no attribute 'weight'
```

Fixes #37444

## Test plan
- [ ] Verify `cyankiwi/Qwen3.5-9B-AWQ-4bit` loads and runs inference without error
- [ ] Verify non-quantized Qwen3.5 models still work (no regression from this change)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by xyang16** [comment]
Thanks for the fix!

File: .github/workflows/bc-lint.yml [hunk 1]
```diff
@@ -0,0 +1,29 @@
+name: BC Lint
```
Comment (xyang16) [inline .github/workflows/bc-lint.yml]: Is this workflow needed for this fix?

**Comment by xyang16** [comment]
> > @JaheimLee I don't see an error to run fp8 model. Which model did you run? Thanks!
> > ```
> > vllm serve Qwen/Qwen3.5-35B-A3B-FP8 \
> >     --tensor-parallel-size 1 \
> >     --max-num-seqs 8 \
> >     --no-enable-prefix-caching
> > ```
> 
> I use the official 27B fp8 model. `CUDA_VISIBLE_DEVICES=0,1 vllm serve /data/pretrained_models/Qwen3.5-27B-FP8 --tensor-parallel-size 2 --max-num-seqs 8 --no-enable-prefix-caching`

@JaheimLee I tried the 27B fp8 model, it was running fine. Maybe clean the torch.compile cache would help? `rm -r /root/.cache/vllm/torch_compile_cache`

```
CUDA_VISIBLE_DEVICES=0,1 vllm serve Qwen/Qwen3.5-27B-FP8 \
    --tensor-parallel-size 2 \
    --max-num-seqs 8 \
    --no-enable-prefix-caching
```

File: .github/workflows/bc-lint.yml (hunk 1 above)
Comment (mgoin) [reply .github/workflows/bc-lint.yml]: @jhsmith409 please remove this change

**Review by mgoin — APPROVED** [review]

File: vllm/model_executor/models/qwen3_5.py [hunk 2]
```diff
@@ -182,8 +182,8 @@ def forward(
         # ============================================================
         mixed_qkvz, ba = torch.ops.vllm.gdn_in_proj(
             hidden_states,
-            self.in_proj_qkvz.weight.shape[0],
-            self.in_proj_ba.weight.shape[0],
+            sum(self.in_proj_qkvz.output_sizes),
```
Comment (xyang16) [inline vllm/model_executor/models/qwen3_5.py]:
```suggestion
            sum(self.in_proj_qkvz.output_sizes) // self.tp_size,
```

File: vllm/model_executor/models/qwen3_5.py [hunk 3]
```diff
@@ -182,8 +182,8 @@ def forward(
...
+            sum(self.in_proj_ba.output_sizes),
```
Comment (xyang16) [inline vllm/model_executor/models/qwen3_5.py]:
```suggestion
            sum(self.in_proj_ba.output_sizes) // self.tp_size,
```

File: vllm/model_executor/models/qwen3_next.py [hunk 4]
```diff
@@ -660,8 +660,8 @@ def forward(
         # ============================================================
         projected_states_qkvz, projected_states_ba = torch.ops.vllm.gdn_in_proj(
             hidden_states,
-            self.in_proj_qkvz.weight.shape[0],
-            self.in_proj_ba.weight.shape[0],
+            sum(self.in_proj_qkvz.output_sizes),
```
Comment (xyang16) [inline vllm/model_executor/models/qwen3_next.py]:
```suggestion
            sum(self.in_proj_qkvz.output_sizes) // self.tp_size,
```

File: vllm/model_executor/models/qwen3_next.py [hunk 5]
```diff
@@ -660,8 +660,8 @@ def forward(
...
+            sum(self.in_proj_ba.output_sizes),
```
Comment (xyang16) [inline vllm/model_executor/models/qwen3_next.py]:
```suggestion
            sum(self.in_proj_ba.output_sizes) // self.tp_size,
```

File: vllm/model_executor/models/qwen3_5.py (hunk 2 above)
Comment (xyang16) [reply vllm/model_executor/models/qwen3_5.py]: @jhsmith409 @mgoin Actually the sum of output_sizes need to be divided by tp_size to avoid shape mismatch, similarly like https://github.com/vllm-project/vllm/blob/v0.18.0/vllm/model_executor/models/qwen3_next.py#L621-L623
