### PR TITLE
[Bugfix] Add missing activation attr to RMSNormGated

### PR DESCRIPTION
**Pull request by Tib-Gridello**
## Purpose

Fix `AttributeError: 'RMSNormGated' object has no attribute 'activation'` introduced in #35102.

#35102 added `activation=self.activation` to `RMSNormGated.forward_cuda()` in `layernorm.py` but did not add the `activation` parameter or `self.activation` attribute to `__init__()`. The sibling class in `fla/ops/layernorm_guard.py` was correctly updated.

Affects any model using `RMSNormGated` from `layernorm.py` — specifically Qwen3.5 GatedDeltaNet layers via `qwen3_next.py`.

## Changes

Add `activation: str = "swish"` parameter and `self.activation = activation` to `RMSNormGated.__init__()`, matching the implementation in `fla/ops/layernorm_guard.py`.

## Test plan

- Confirmed fix on 4x RTX PRO 6000 Blackwell serving Qwen3.5-122B-A10B (vLLM `0.16.1rc1.dev12+g111d86906`)
- Model loads and serves successfully after patch

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by jikunshang — APPROVED** [review]
thanks for fixing. 
I will trigger `LM Eval Small Models (B200)` in ci which failed due to #35102. eg https://buildkite.com/vllm/ci/builds/53374#019c9a0e-79ad-4d18-b585-e09d94934e3d
