### PR TITLE
[CPU][Bugfix] Fix CPU Profiler issue

### LINKED ISSUE #29259: [Bug]: `simple_profiling.py` fails on CPU target
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 24.04.3 LTS (x86_64)
GCC version                  : (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version                : Could not collect
CMake version                : version 4.2.0
Libc version                 : glibc-2.39

==============================
       PyTorch Info
==============================
PyTorch version              : 2.8.0+cpu
Is debug build               : False
CUDA used to build PyTorch   : None
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.3 (main, Aug 14 2025, 17:47:21) [GCC 13.3.0] (64-bit runtime)
Python platform              : Linux-6.14.0-36-generic-x86_64-with-glibc2.39

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : False
CUDA runtime version         : No CUDA
CUDA_MODULE_LOADING set to   : N/A
GPU models and configuration : No CUDA
Nvidia driver version        : No CUDA
cuDNN version                : No CUDA
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                            x86_64
CPU op-mode(s):                          32-bit, 64-bit
Address sizes:                           39 bits physical, 48 bits virtual
Byte Order:                              Little Endian
CPU(s):                                  4
On-line CPU(s) list:                     0-3
Vendor ID:                               GenuineIntel
Model name:                              Intel(R) N100
CPU family:                              6
Model:                                   190
Thread(s) per core:                      1
Core(s) per socket:                      4
Socket(s):                               1
Stepping:                                0
CPU(s) scaling MHz:                      90%
CPU max MHz:                             3400.0000
CPU min MHz:                             700.0000
BogoMIPS:                                1612.80
Flags:                                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect user_shstk avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                          VT-x
L1d cache:                               128 KiB (4 instances)
L1i cache:                               256 KiB (4 instances)
L2 cache:                                2 MiB (1 instance)
L3 cache:                                6 MiB (1 instance)
NUMA node(s):                            1
NUMA node0 CPU(s):                       0-3
Vulnerability Gather data sampling:      Not affected
Vulnerability Ghostwrite:                Not affected
Vulnerability Indirect target selection: Not affected
Vulnerability Itlb multihit:             Not affected
Vulnerability L1tf:                      Not affected
Vulnerability Mds:                       Not affected
Vulnerability Meltdown:                  Not affected
Vulnerability Mmio stale data:           Not affected
Vulnerability Reg file data sampling:    Mitigation; Clear Register File
Vulnerability Retbleed:                  Not affected
Vulnerability Spec rstack overflow:      Not affected
Vulnerability Spec store bypass:         Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:                Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:                Mitigation; Enhanced / Automatic IBRS; IBPB conditional; PBRSB-eIBRS Not affected; BHI BHI_DIS_S
Vulnerability Srbds:                     Not affected
Vulnerability Tsa:                       Not affected
Vulnerability Tsx async abort:           Not affected
Vulnerability Vmscape:                   Mitigation; IBPB before exit to userspace

==============================
Versions of relevant libraries
==============================
[pip3] numpy==2.1.2
[pip3] pyzmq==27.1.0
[pip3] torch==2.8.0+cpu
[pip3] torchaudio==2.8.0+cpu
[pip3] torchvision==0.23.0+cpu
[pip3] transformers==4.57.1
[pip3] triton==3.2.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.11.2.dev200+g3999442f1 (git sha: 3999442f1)
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled
GPU Topology:
  Could not collect

==============================
     Environment Variables
==============================
VLLM_LOGGING_LEVEL=DEBUG
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
```

</details>

## Description
When executing the `examples\offline_inference\simple_profiling.py` script on a CPU, an error occurs.
```bash
(EngineCore_DP0 pid=367027) ERROR 11-23 14:03:28 [v1/engine/core.py:844]   File "/home/____/vllm_cpu/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 520, in annotate_profile
(EngineCore_DP0 pid=367027) ERROR 11-23 14:03:28 [v1/engine/core.py:844]     return self.profiler.annotate_context_manager(
(EngineCore_DP0 pid=367027) ERROR 11-23 14:03:28 [v1/engine/core.py:844]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=367027) ERROR 11-23 14:03:28 [v1/engine/core.py:844] AttributeError: 'profile' object has no attribute 'annotate_context_manager'
```

full log: [full_log.txt](https://github.com/user-attachments/files/23693710/full_log.txt)

## Environment
- Target Device: CPU (x86)
- Build from source

## Details
The root cause appears to be incomplete application of changes introduced by Pull Request #28987 .
This conclusion was drawn by bisecting the commits:
| Commit | SHA | Status |
|---|---|---|
| Previous Commit | 3168285fcaaee09bc93dce7bc9ae6ee823c71652 | No Error |
| Failing Commit | fcbcba6c70a3308705aa21adebb443bf9015b486 | Error Occurs

It seems the necessary modifications were only applied to gpu_worker.py, and the corresponding support is missing in `vllm\v1\worker\cpu_worker.py`.

The profiler member of the Worker class must be a subclass derived from WorkerProfiler.

Reference for `WorkerProfiler`: https://github.com/vllm-project/vllm/blob/20ee418adc279f29e76e7770c4f688c4fc070274/vllm/profiler/gpu_profiler.py#L16
Reference for `gpu_worker.py`: https://github.com/vllm-project/vllm/blob/20ee418adc279f29e76e7770c4f688c4fc070274/vllm/v1/worker/gpu_worker.py

However, in `CPUWorker`, `torch.profiler.profile` is currently specified:

Reference for `cpu_worker.py`: https://github.com/vllm-project/vllm/blob/20ee418adc279f29e76e7770c4f688c4fc070274/vllm/v1/worker/cpu_worker.py#L51

Similarly, `XPUWorker` also requires modification:
Reference for xpu_worker.py: https://github.com/vllm-project/vllm/blob/20ee418adc279f29e76e7770c4f688c4fc070274/vllm/v1/worker/xpu_worker.py#L57

Additionally, `tpu_worker.py` should also be reviewed for similar necessary changes.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by zhili03**
## Purpose
Fix CPU profiler issue as described at [issue 29259](https://github.com/vllm-project/vllm/issues/29259) 
resolve #29259 
### Configurations
Tested on `aws c7g16xlarge instance with Ubuntu 22.04.01, Python 3.12, PyTorch 2.10`; However, should be reproduced successfully on other supported platforms.
### Example script
Running `python examples\offline_inference\simple_profiling.py` on aarch64 CPU backend, no issues would happen.
## Test Result
Profiler information output with expected results.
```Profiler stopped successfully.
--------------------------------------------------
Prompt: 'Hello, my name is'
Generated text: " Shane and I live in the South Bay. I'm very happy to see you"
--------------------------------------------------
Prompt: 'The president of the United States is'
Generated text: ' calling for a “normal” election, but lawmakers are not ready to'
--------------------------------------------------
Prompt: 'The capital of France is'
Generated text: ' a country of great diversity and a powerful nation with many different cultures. On the'
--------------------------------------------------
Prompt: 'The future of AI is'
Generated text: ' being fueled by consciousness\n\nA new study from the University of Texas at Austin'```
---
<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [ ] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [ ] The test plan, such as providing test command.
- [ ] The test results, such as pasting the results comparison before and after, or e2e results
- [ ] (Optional) The necessary documentation update, such as updating `supported_models.md` and `examples` for a new model.
- [ ] (Optional) Release notes update. If your change is user facing, please update the release notes draft in the [Google Doc](https://docs.google.com/document/d/1YyVqrgX4gHTtrstbq8oWUImOyPCKSGnJ7xtTpmXzlRs/edit?tab=t.0).
</details>

### CODE REVIEW

File: vllm/v1/worker/cpu_worker.py [hunk 1]
```diff
@@ -48,17 +49,8 @@ def __init__(
                 "Profiling enabled. Traces will be saved to: %s",
```
Comment (bigPYJ1151) [inline vllm/v1/worker/cpu_worker.py]: Looks like this log can be removed too as it is included in ```__init__``` of ```TorchProfilerWrapper```.

**Review by aditew01 — APPROVED** [review]

**Review by bigPYJ1151 — APPROVED** [review]
Thanks for the fix! Please reslove the conflict.
