### ISSUE TITLE
[CI Failure]:

### ISSUE THREAD

**Issue by russellb** [vllm-project/vllm#22397]
### Name of failing test

models/multimodal/processing/test_common.py::test_processing_correctness[1.0-32-0.3-internlm/Intern-S1]

### Basic information

- [ ] Flaky test
- [ ] Can reproduce locally
- [ ] Caused by external libraries (e.g. bug in `transformers`)

### 🧪 Describe the failing test

Test failure introduced by a GPT-OSS PR

[2025-08-06T21:09:08Z] FAILED models/multimodal/processing/test_common.py::test_processing_correctness[1.0-32-0.3-internlm/Intern-S1] - AttributeError: 'GotOcr2ImageProcessorFast' object has no attribute 'get_number_of_image_tokens'. Did you mean: 'get_number_of_image_patches'?

### 📝 History of failing test

https://buildkite.com/organizations/vllm/analytics/suites/ci-1/tests/396bc3d2-b2a6-8b15-b051-5a341f82961c?branch=main&period=14days

appears to have been introduced by #223278

[test run history](https://buildkite.com/organizations/vllm/analytics/suites/ci-1/runs/e7f09665-d87e-8618-a7a1-fb8055c9fd40)
