### PR TITLE
Correcting the mock classes for MM GC tests

### PR DESCRIPTION
**Pull request by wdhongtw**
## Purpose

Add postprocess_encoder_output to the testing mock classes, addressing the change introduced by #42224

cc @JisoLya

## Test Plan

```sh
pytest tests/v1/cudagraph/test_encoder_cudagraph.py
```

## Test Result

Before

```text
FAILED tests/v1/cudagraph/test_encoder_cudagraph.py::TestEncoderCudaGraphCaptureReplay::test_execute_returns_one_tensor_per_image - AttributeError: 'SimpleMockViTModel' object has no attribute 'postprocess_encoder_output'
FAILED tests/v1/cudagraph/test_encoder_cudagraph.py::TestEncoderCudaGraphCaptureReplay::test_execute_output_tokens_per_image - AttributeError: 'SimpleMockViTModel' object has no attribute 'postprocess_encoder_output'
FAILED tests/v1/cudagraph/test_encoder_cudagraph.py::TestEncoderCudaGraphCaptureReplay::test_hit_counter_increments_by_num_images - AttributeError: 'SimpleMockViTModel' object has no attribute 'postprocess_encoder_output'
FAILED tests/v1/cudagraph/test_encoder_cudagraph.py::TestEncoderCudaGraphCaptureReplay::test_chunking_when_images_exceed_max_batch - AttributeError: 'SimpleMockViTModel' object has no attribute 'postprocess_encoder_output'
FAILED tests/v1/cudagraph/test_encoder_cudagraph.py::TestEncoderCudaGraphVideoReplay::test_video_execute_returns_one_tensor_per_video - AttributeError: 'SimpleMockViTVideoModel' object has no attribute 'postprocess_encoder_output'
FAILED tests/v1/cudagraph/test_encoder_cudagraph.py::TestEncoderCudaGraphVideoReplay::test_video_output_tokens_per_item - AttributeError: 'SimpleMockViTVideoModel' object has no attribute 'postprocess_encoder_output'
FAILED tests/v1/cudagraph/test_encoder_cudagraph.py::TestEncoderCudaGraphVideoReplay::test_video_hit_counter_increments_by_num_videos - AttributeError: 'SimpleMockViTVideoModel' object has no attribute 'postprocess_encoder_output'
FAILED tests/v1/cudagraph/test_encoder_cudagraph.py::TestEncoderCudaGraphVideoReplay::test_image_and_video_share_manager - AttributeError: 'SimpleMockViTVideoModel' object has no attribute 'postprocess_encoder_output'
================================================================== 8 failed, 41 passed, 16 warnings in 21.41s ==================================================================
```

After

```text
======================================================================= 49 passed, 16 warnings in 20.84s =======================================================================
```

---
<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [x] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [x] The test plan, such as providing test command.
- [x] The test results, such as pasting the results comparison before and after, or e2e results
- [ ] (Optional) The necessary documentation update, such as updating `supported_models.md` and `examples` for a new model.
</details>

### CODE REVIEW

**Comment by wdhongtw** [comment]
cc @shen-shanshan @Isotr0py

**Review by shen-shanshan — APPROVED** [review]
LGTM.

**Comment by wdhongtw** [comment]
CI fails due to assertion based on timing.

```shell
pytest tests/v1/cudagraph/test_cudagraph_mode.py::'test_backend_and_cudagraph_mode_combo[FlashInfer-FULL_AND_PIECEWISE-True]'
```

```text
ValueError: Memory of devices devices=[0] not free after dur_s=120.01 (threshold='0.10')
```

Can not re-produced locally, force push again to re-run the CI pipeline.

**Comment by wdhongtw** [comment]
All good now, can be merged. 🙂‍↕️

**Review by Isotr0py — APPROVED** [review]
