### PR TITLE
[Model] Initialize deepseek-vl support

### LINKED ISSUE #3356: DeepSeek VL support
Hi, it would be awesome if [DeepSeek VL](https://huggingface.co/deepseek-ai/deepseek-vl-1.3b-chat) will be supported for all the serving goodies!

### LINKED ISSUE #4982: [New Model]: DeepSeek VL
### The model to consider.

https://huggingface.co/deepseek-ai/deepseek-vl-7b-chat

### The closest model vllm already supports.

Llava

### PR DESCRIPTION
**Pull request by liuyancong-enflame-tech**
## Test On NVIDIA L40S
- Test Example
```
from vllm import LLM
from PIL import Image


from vllm import SamplingParams

sample_params = SamplingParams(temperature=0, max_tokens=1024)

model_path = "/pretrained_models/deepseek-vl-7b-chat"


llm = LLM(
    model=model_path,
    max_model_len=3072,
)
print("model load finish")
prompt = f"You are a helpful language and vision assistant. You are able to understand the visual content that the user provides, and assist the user with a variety of tasks using natural language.\n User: <image_placeholder> Describe each stage of this image detail.\nAssistant:"

image = Image.open("/opt/TV/VLM01/tests/images/cherry_blossom.jpg")
image = image.convert("RGB")
outputs = llm.generate(
    {
        "prompt": prompt,
        "multi_modal_data": {"image": image},
    },
    sample_params,
)
for o in outputs:
    generated_text = o.outputs[0].text
    print(generated_text)

```
- Output 
```
The image captures a scene where a tall tower, which appears to be a communication or observation tower, is partially obscured by cherry blossom trees in full bloom. The tower is situated in the background, and the sky behind it is a clear blue.

The cherry blossom trees, which are in the foreground, are in various stages of bloom. Some branches are densely packed with pink blossoms, while others have fewer or no flowers at all. The blossoms are in various shades of pink, ranging from light to deep, indicating the progression of the bloom cycle.

The perspective of the image is from below, looking upwards towards the tower, which gives a sense of scale and grandeur to the tower. The branches of the cherry blossom trees frame the tower, creating a natural border that draws the viewer's eye towards the tower.

There are no discernible texts or other objects in the image. The focus is solely on the tower and the cherry blossom trees, with the blue sky providing a contrasting backdrop. The image does not contain any people or moving elements, suggesting a still, serene moment captured in time.
```

FIX #3356
FIX #4982

### CODE REVIEW

**Comment by liuyancong** [comment]
Contributed by enflame-tech

File: vllm/transformers_utils/configs/deepseek_vl.py [hunk 1]
```diff
@@ -0,0 +1,89 @@
+# Copyright (c) 2023-2024 DeepSeek.
```
Comment (DarkLight1337) [inline vllm/transformers_utils/configs/deepseek_vl.py:1]: Could you explain in more detail why we need to patch `collections` module as well as the config?

File: vllm/model_executor/models/deepseek_vl.py [hunk 2]
```diff
@@ -0,0 +1,1901 @@
...
+            forward_kwargs = dict()
+
+        elif self.model_name.startswith("sam"):
+            vision_tower = create_sam_vit(**vision_tower_params)
+            forward_kwargs = dict()
+
+        else:  # huggingface
+            from transformers import CLIPVisionModel
+
+            vision_tower = CLIPVisionModel.from_pretrained(**vision_tower_params)
```
Comment (DarkLight1337) [inline vllm/model_executor/models/deepseek_vl.py:1576]: To optimize performance (and avoid code duplication), can you use vLLM's `CLIPVisionModel` that was introduced in #5591?

File: vllm/model_executor/models/deepseek_vl.py [hunk 3]
```diff
@@ -0,0 +1,1901 @@
...
+        tensor.copy_(tensor_dtype)
+
+
+def init_weights(self):
+    if self.pos_embed is not None:
+        trunc_normal_(self.pos_embed, std=self.pos_embed.shape[1] ** -0.5)
+    trunc_normal_(self.latent, std=self.latent_dim**-0.5)
+
+
+def init_weights_vit_timm(module: nn.Module, name: str = "") -> None:
```
Comment (DarkLight1337) [inline vllm/model_executor/models/deepseek_vl.py:394]: Since we're loading in the weights anyways, I think we can skip this initialization.

**Review by DarkLight1337 — COMMENTED** [review]
Thanks for the contribution! I have a few initial comments.

Apart from that, can you add a test case (similar to `test_llava.py`) to test the correctness of the model in CI?

File: vllm/transformers_utils/configs/deepseek_vl.py (hunk 1 above)
Comment (liuyancong-enflame-tech) [reply vllm/transformers_utils/configs/deepseek_vl.py:1]: This model introduces the attrdict module, which will report an error（from collections import Mapping --》ImportError: cannot import name 'Mapping' from 'collections'） in Python 3.10 and above. I will try to remove this dependency.

File: vllm/model_executor/models/deepseek_vl.py (hunk 2 above)
Comment (liuyancong-enflame-tech) [reply vllm/model_executor/models/deepseek_vl.py:1576]: OK

File: vllm/model_executor/models/deepseek_vl.py (hunk 3 above)
Comment (liuyancong-enflame-tech) [reply vllm/model_executor/models/deepseek_vl.py:394]: OK, I will delete it

**Comment by liuyancong-enflame-tech** [comment]
now support deepseek-ai/deepseek-vl-7b-chat  deepseek-ai/deepseek-vl-1.3b-chat

**Comment by liuyancong-enflame-tech** [comment]
This model depends on timm>=0.9.16, which depends on torch, but it will conflict with the dependencies of other third-party components and cause the pipeline to fail. Therefore, running this model requires additional installation. I don’t know if this is appropriate. In addition, it depends on many modules of timm, which is difficult to remove.

**Comment by DarkLight1337** [comment]
> This model depends on timm>=0.9.16, which depends on torch, but it will conflict with the dependencies of other third-party components and cause the pipeline to fail. Therefore, running this model requires additional installation. I don’t know if this is appropriate. In addition, it depends on many modules of timm, which is difficult to remove.

Can you implement the individual timm modules inside vLLM? (where possible, you should use vLLM-specific layers to improve the performance anyway)

**Comment by liuyancong-enflame-tech** [comment]
> > This model depends on timm>=0.9.16, which depends on torch, but it will conflict with the dependencies of other third-party components and cause the pipeline to fail. Therefore, running this model requires additional installation. I don’t know if this is appropriate. In addition, it depends on many modules of timm, which is difficult to remove.
> 
> Can you implement the individual timm modules inside vLLM? (where possible, you should use vLLM-specific layers to improve the performance anyway)

OK，I will try to do this and  I think it will take some time

**Comment by DarkLight1337** [comment]
> > > This model depends on timm>=0.9.16, which depends on torch, but it will conflict with the dependencies of other third-party components and cause the pipeline to fail. Therefore, running this model requires additional installation. I don’t know if this is appropriate. In addition, it depends on many modules of timm, which is difficult to remove.
> > 
> > 
> > Can you implement the individual timm modules inside vLLM? (where possible, you should use vLLM-specific layers to improve the performance anyway)
> 
> OK，I will try to do this and I think it will take some time

You can make use of our implementation of `CLIPVisionModel` to save some effort.

**Comment by DarkLight1337** [comment]
To speed up the CI queue for #5905, I've cancelled the distributed tests for the latest CI run in this PR since they won't pass anyway until #5905 has been merged. Please merge `main` into your branch after that happens so that the CI can pass once again.

**Comment by liuyancong-enflame-tech** [comment]
This test [tests/models/test_deepseek_vl.py] case depends on the project https://github.com/deepseek-ai/DeepSeek-VL, and it seems that pip installation will fail.I think it is possible not to add this test case

And The [examples/deepseek_vl_example.py]  can run successfully.

**Comment by DarkLight1337** [comment]
> This test [tests/models/test_deepseek_vl.py] case depends on the project https://github.com/deepseek-ai/DeepSeek-VL, and it seems that pip installation will fail when build the docker .I think it is possible not to add this test case

In this case it won't function for users of vLLM either since they can't install it. Can you figure out which dependency is causing the issue?

**Comment by liuyancong-enflame-tech** [comment]
> > This test [tests/models/test_deepseek_vl.py] case depends on the project https://github.com/deepseek-ai/DeepSeek-VL, and it seems that pip installation will fail when build the docker .I think it is possible not to add this test case
> 
> In this case it won't function for users of vLLM either since they can't install it (so you should still keep the tests). Can you figure out which dependency is causing the issue?
In the tests/models/test_deepseek_vl.py test, when hf runner loads the model, if we do not import deepseek_vl, an error will occur
(ValueError: The checkpoint you are trying to load has model type `multi_modality` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.)
This is because the model part of the code is not in the hf repository, but in the github repository. In the code: https://github.com/deepseek-ai/DeepSeek-VL/blob/main/deepseek_vl/models/modeling_vlm.py, we can see some registration codes:
AutoConfig.register("multi_modality", MultiModalityConfig)
AutoModelForCausalLM.register(MultiModalityConfig, MultiModalityCausalLM)
If I add the dependency in vllm\requirements-test.txt:
deepseek_vl@git+https://github.com/deepseek-ai/DeepSeek-VL.git@main
Then, docker will report an error when building the image. The error is that metadata is None and cannot be recognized. The package can be packaged into whl, but it will not be found when it is installed.

**Comment by DarkLight1337** [comment]
You can manually registry the model to HuggingFace inside the test case.

**Comment by liuyancong-enflame-tech** [comment]
> You can manually register the model to HuggingFace inside the test case.

Ok, I'll try it

**Comment by DarkLight1337** [comment]
Heads up, since #6121 has been merged, you have to register the maximum number of image tokens (in your case it's probably 576) to `MULTIMODAL_REGISTRY` as well. (See LLaVA models for an example)

Also, you may wish to follow Phi-3-Vision's example and create a dummy CLIP config to contain variables such as the image size and number of image tokens.

**Comment by liuyancong-enflame-tech** [comment]
> Heads up: since #6121 has been merged, you have to register the maximum number of image tokens (in your case it's probably 576) to `MULTIMODAL_REGISTRY` as well. (See LLaVA models for an example)
> 
> Also, you may wish to follow Phi-3-Vision's example and create a dummy CLIP config to contain variables such as the image size and number of image tokens if you cannot extract them from DeepSeek-VL's config.

OK,

File: docs/source/models/supported_models.rst [hunk 4]
```diff
@@ -161,6 +161,10 @@ Decoder-only Language Models
     - Xverse
     - :code:`xverse/XVERSE-7B-Chat`, :code:`xverse/XVERSE-13B-Chat`, :code:`xverse/XVERSE-65B-Chat`, etc.
     -
+  * - :code:`DeepSeekMultiModalityCausalLM`
```
Comment (DarkLight1337) [inline docs/source/models/supported_models.rst:164]: We have added a new list to this page specifically for VLMs. Please move your entry to the new list.

Comment (liuyancong-enflame-tech) [reply docs/source/models/supported_models.rst]: OK，It has been modified

**Comment by liuyancong-enflame-tech** [comment]
The Test models/test_deepseek_vl.py failed, but no exception stack was thrown. I don’t know what happened. The program seems to be terminated. Have you encountered similar problems?

**Comment by DarkLight1337** [comment]
The stack trace is shown near the end of the CI logs:

https://buildkite.com/vllm/ci-aws/builds/4404#0190956c-f526-40a4-b2af-232d40ffbd0c

**Comment by liuyancong-enflame-tech** [comment]
buildkite/fastcheck/pr/tensorizer-metrics-tracing-test — Failed (exit status 1) 
 What functionality does this test case test?

**Comment by DarkLight1337** [comment]
It's unrelated to this PR.

File: examples/deepseek_vl_example.py [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+    "User: <image_placeholder> Describe the content of this image.\nAssistant:"
+
+
+def run_deepseek_vl():
+    llm = LLM(model=model,
+              max_model_len=3072,
+              enforce_eager=True,
+              dtype=torch.bfloat16)
+
+    image = Image.open("images/stop_sign.jpg")
```
Comment (DarkLight1337) [inline examples/deepseek_vl_example.py:26]: Please note that images can now be downloaded automatically when accessed via `vllm.assets.image.ImageAsset`.

Comment (liuyancong-enflame-tech) [reply examples/deepseek_vl_example.py]: OK, the changes have been made

**Comment by SinanAkkoyun** [comment]
Will this PR get merged?

**Comment by SinanAkkoyun** [comment]
Or rather where could I help, what is missing or needs work, only the `models/test_deepseek_vl.py`?

**Comment by DarkLight1337** [comment]
> Or rather where could I help, what is missing or needs work, only the `models/test_deepseek_vl.py`?

Sorry for forgetting about this! I think we need to fix the merge conflicts and update the tests. Afterwards we can work on removing redundant code in the model file.

**Comment by SinanAkkoyun** [comment]
> Sorry for forgetting about this!
No problem at all! I am sorry to prematurely have commented here, as Qwen2 VL architecturally fits my usecase way better.
Although I am having problems with the OpenAI endpoint, as Qwen2 VL is the only model that generates junk, I opened an issue for that https://github.com/vllm-project/vllm/issues/9732
