### PR TITLE
[ROCm][CI] Handle missing vision_config in Isaac model attention patch

### PR DESCRIPTION
**Pull request by AndreasKaratzas**
Follow-up to #32233. Adds error handling to `isaac_patch_hf_runner` for models that don't have the expected `vision_config` attribute in their attention layers.

## Problem

Isaac-0.1 (`PerceptronAI/Isaac-0.1`) uses `Siglip2VariableLengthAttention` which doesn't have a `vision_config` attribute, causing test failures:
```
AttributeError: 'Siglip2VariableLengthAttention' object has no attribute 'vision_config'
```

The newer Isaac-0.2-2B-Preview has this attribute, but Isaac-0.1 does not.

## Solution

Wrap the `patch_hf_vision_attn_for_rocm` call in a try-except block that:
- Catches `AttributeError` when `vision_config` is missing
- Logs a warning instead of failing silently
- Allows the test to proceed (the patch may not be needed for all model variants)

This follows the "fail informatively, not silently" principle discussed in #32233, while still allowing tests to run for models with different attention implementations.

## Related

I have also posted an issue on ISAAC repo, so that their code becomes more transformers API compliant and such "hacks" are not necessary: https://github.com/perceptron-ai-inc/perceptron/issues/43

### CODE REVIEW

File: tests/models/multimodal/generation/vlm_utils/model_utils.py [hunk 1]
```diff
@@ -580,9 +580,19 @@ def patched_generate(*args, **kwargs):
...
-    patch_hf_vision_attn_for_rocm(hf_model.model)
+    try:
+        patch_hf_vision_attn_for_rocm(hf_model.model)
+    except AttributeError as e:
+        warnings.warn(
+            f"Skipping ROCm vision attention patch for Isaac model: {e}. "
+            "This may be expected for models without vision_config in "
+            "attention layers.",
+            stacklevel=2,
+        )
```
[the remark this answers is not in the document]
Comment (AndreasKaratzas) [reply tests/models/multimodal/generation/vlm_utils/model_utils.py]: Done :)

**Comment by AndreasKaratzas** [comment]
cc @tjtanaa

**Review by tjtanaa — APPROVED** [review]
LGTM, the Multi-Modal Extended Test (2) now passed.
The Multi-Modal Extended Test (1) is also failing in main, so it is fine.
