### PR TITLE
[API Server] Add port number range validation

### PR DESCRIPTION
**Pull request by terrytangyuan**
This PR adds validation on the range of the specified port number in API Server.

### CODE REVIEW

**Review by NickLucche — APPROVED** [review]

**Review by njhill — APPROVED** [review]
Thanks @terrytangyuan!

**Comment by WangErXiao** [comment]
I found it doesn't work in Python 3.10

python3.10/argparse.py", line 1430, in add_argument
    action = action_class(**kwargs)
TypeError: _StoreAction.__init__() got an unexpected keyword argument 'ge'

**Comment by terrytangyuan** [comment]
I am reverting this in https://github.com/vllm-project/vllm/pull/13670 for now since Python 3.10 is gonna be around for a while: https://endoflife.date/python

**Comment by WangErXiao** [comment]
> I am reverting this in #13670 for now since Python 3.10 is gonna be around for a while: https://endoflife.date/python

OK,  I just commit a pr https://github.com/vllm-project/vllm/pull/13672

**Comment by terrytangyuan** [comment]
I already sent it https://github.com/vllm-project/vllm/pull/13670

**Comment by terrytangyuan** [comment]
Thanks. Closed mine.
