### PR TITLE
[Feature] Detect all2all peer fault with fault tolerance backend and prevent corrupted output

### PR DESCRIPTION
**Pull request by fangyuchu**
## Purpose

Some all2all backends (nixl_ep, deepep_low_latency) support fault-tolerant communication: when a peer rank fails, instead of hanging indefinitely like traditional collectives, the healthy rank sets a mask to exclude the failed rank after a configurable timeout and continues running. However, the ongoing forward pass that triggered the timeout already produced a corrupted token (computed with one rank missing during MoE dispatch/combine). Currently, under the nixl_ep backend, this corrupted token is returned to EngineCore and ultimately to the end user.

This PR prevents corrupted tokens from reaching users by detecting all2all faults at the output boundary. Specifically:

1. **All2AllManagerBase** (`base_device_communicator.py`) gains three new abstract methods — `query_active_mask()`, `clean_mask()`, and `query_fault()` — plus a `support_fault_tolerance` property that backends override to declare FT capability.

2. **DeepEPLLAll2AllManager** and **NixlEPAll2AllManager** (`all2all.py`) implement these methods by querying the kernel's internal mask buffer:
   - `query_active_mask()` returns the current mask tensor (which ranks are alive).
   - `query_fault()` diffs the current mask against the last known mask; returns `(has_fault: bool, current_mask: Tensor)`.
   - `clean_mask()` resets the mask and clears the tracked last-mask state.

3. **AsyncGPUModelRunnerOutput** (`gpu_model_runner.py`) queries `query_fault()` during the async GPU→CPU copy phase (`_start_async_copy`). If `has_fault` is true when `get_output()` is called, a `RuntimeError` is raised — preventing the corrupted token from ever reaching the caller.

**Why now:**

1. **nixl_ep has FT enabled by default.** This means that today, when a rank times out, vLLM silently produces a corrupted token after the kernel timeout and returns it to the user. This PR stops that from happening — the output is intercepted and an exception is raised instead.

2. **Building block for the broader fault tolerance system.** Once corrupted tokens are reliably intercepted, the orchestrator can apply recovery policies (retry for transient network flaps, scale-down for permanent GPU failures) on top of this foundation. This PR is intentionally scoped to a single, reviewable concern: detect → raise.

## Test Plan

DP=4, TP=1, EP enabled with Qwen3-30B-A3B.

**Backends tested:** Both `nixl_ep` and `deepep_low_latency`. (DeepEP LL requires manually enabling shrink mode since it is off by default.)

**Fault injection:** Patch `_run_ar()` in `vllm/v1/worker/dp_utils.py` to inject `time.sleep(600)` on rank 1 **after** the `dist.all_reduce` call at step N. This causes rank 1 to hang immediately before entering all2all expert dispatch. The healthy ranks (0, 2, 3) then hit the all2all kernel timeout during MoE dispatch/combine.

## Test Result

**Baseline (without this PR):** When rank 1 hangs, ranks 0, 2, 3 hit the nixl_ep kernel timeout, which sets the mask and allows the kernel to continue. Any rank that is executing `execute_model` completes the forward pass with a corrupted token and returns it to the client via `sample_tokens`.

**With this PR:** Same fault injection. When rank 1 hangs, the ranks executing `execute_model` hit the nixl_ep kernel timeout and the mask is set. During `AsyncGPUModelRunnerOutput._start_async_copy`, `query_fault()` detects the mask change. When `get_output()` is called, a `RuntimeError` is raised:

> RuntimeError: Fault detected in EP all2all communication: one or more ranks timed out during dispatch/combine. Mask: [0, 1, 0, 0]

The corrupted token is never returned to the client.

---
<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [x] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [x] The test plan, such as providing test command.
- [x] The test results, such as pasting the results comparison before and after, or e2e results
- [ ] (Optional) The necessary documentation update, such as updating `supported_models.md` and `examples` for a new model.
- [ ] (Optional) Release notes update. If your change is user facing, please update the release notes draft in the [Google Doc](https://docs.google.com/document/d/1YyVqrgX4gHTtrstbq8oWUImOyPCKSGnJ7xtTpmXzlRs/edit?tab=t.0).
</details>

### CODE REVIEW

File: vllm/distributed/device_communicators/all2all.py [hunk 1]
```diff
@@ -318,12 +323,43 @@ def get_handle(self, kwargs):
...
+        if DeepEPLLAll2AllManager._last_mask is not None:
+            DeepEPLLAll2AllManager._last_mask.zero_()
+
+    def query_fault(self) -> tuple[torch.Tensor, torch.Tensor]:
+        current = self.query_active_mask()
+        if DeepEPLLAll2AllManager._last_mask is None:
+            DeepEPLLAll2AllManager._last_mask = torch.zeros_like(current)
+        has_fault = (current != DeepEPLLAll2AllManager._last_mask).any()
+        DeepEPLLAll2AllManager._last_mask.copy_(current)
+        return has_fault, current
```
[the remark this answers is not in the document]
Comment (fangyuchu) [reply vllm/distributed/device_communicators/all2all.py]: These are intentionally class-level. The fault mask reflects per-GPU hardware/network state (which peers are reachable), not per-instance state — if a rank is dead, it's dead for every manager instance on that GPU. 

The multi-model / speculative decoding concern doesn't apply here — DP+EP with different EP configs on the same GPU isn't a supported topology in vLLM.

File: vllm/distributed/device_communicators/all2all.py [hunk 2]
```diff
@@ -502,6 +540,37 @@ def destroy(self):
...
+    def query_fault(self) -> tuple[torch.Tensor, torch.Tensor]:
+        current = self.query_active_mask()
+        last = NixlEPAll2AllManager._last_active_mask
+        if last is None or last.shape != current.shape:
+            NixlEPAll2AllManager._last_active_mask = torch.zeros_like(current)
+            last = NixlEPAll2AllManager._last_active_mask
+        has_fault = (current != last).any()
+        assert last is not None
+        last.copy_(current)
+        return has_fault, current
```
[the remark this answers is not in the document]
Comment (fangyuchu) [reply vllm/distributed/device_communicators/all2all.py]: Not applicable for the same reason.

File: vllm/distributed/device_communicators/all2all.py [hunk 3]
```diff
@@ -340,6 +376,8 @@ class NixlEPAll2AllManager(All2AllManagerBase):
 
     _buffer: _NixlEPBufferState | None = None
     _lock = threading.RLock()
+    _full_mask: torch.Tensor | None = None
+    _last_active_mask: torch.Tensor | None = None
```
[the remark this answers is not in the document]
Comment (fangyuchu) [reply vllm/distributed/device_communicators/all2all.py]: Same rationale as above — _full_mask and _last_active_mask reflect physical RDMA reachability, which is per-GPU hardware state, not per-process-group state. _buffer was already class-level before this commit.

File: vllm/v1/worker/gpu_model_runner.py [hunk 4]
```diff
@@ -274,6 +278,10 @@ def __init__(
                 if self._routed_experts is not None
                 else None
             )
+            if check_ep_fault:
+                has_fault, current_mask = get_ep_all2all_manager().query_fault()
+                self._has_fault = has_fault.to("cpu", non_blocking=True)
+                self._current_mask = current_mask
```
[the remark this answers is not in the document]
Comment (fangyuchu) [reply vllm/v1/worker/gpu_model_runner.py]: The race condition described here can't happen — execute_model is sequential (one step at a time on the same CUDA stream), so _mask won't be mutated between query_fault() and the subsequent raise. There's no concurrent caller that could overwrite it.

Adding .to("cpu", non_blocking=True) on every step adds overhead to the hot path for a scenario that doesn't exist. The mask is only read if a fault is detected (exceptional path), and at that point the value is already stable since the faulted rank won't recover on its own.

File: vllm/v1/worker/gpu_model_runner.py [hunk 5]
```diff
@@ -310,6 +318,14 @@ def get_output(self) -> ModelRunnerOutput:
             output.routed_experts = self._routed_experts_cpu.tolists()
         del self._routed_experts
 
+        if self._has_fault is not None and self._has_fault.item():
+            assert self._current_mask is not None
+            raise RuntimeError(
+                "Fault detected in EP all2all communication: "
+                "one or more ranks timed out during dispatch/combine. "
+                f"Mask: {self._current_mask.cpu().tolist()}"
+            )
```
[the remark this answers is not in the document]
Comment (fangyuchu) [reply vllm/v1/worker/gpu_model_runner.py:331]: Refer to previous comment.

File: vllm/distributed/device_communicators/all2all.py [hunk 6]
```diff
@@ -260,8 +260,13 @@ class DeepEPLLAll2AllManager(DeepEPAll2AllManagerBase):
     All2All communication based on DeepEP Low-Latency kernels.
     """
 
+    _active_buffer: Any = None
+    _mask: torch.Tensor | None = None
+    _last_mask: torch.Tensor | None = None
+
     def __init__(self, cpu_group, tcp_store_group=None):
         super().__init__(cpu_group, tcp_store_group)
+        self.support_fault_tolerance = False  # TODO: set to True when FT is supported.
```
Comment (SageMoore) [inline vllm/distributed/device_communicators/all2all.py:270]: It looks like this disables ft for Deep EP LL. Is that intentional?

**Review by SageMoore — COMMENTED** [review]
This looks reasonable @fangyuchu. Just one question.

File: vllm/distributed/device_communicators/all2all.py (hunk 6 above)
Comment (fangyuchu) [reply vllm/distributed/device_communicators/all2all.py:270]: Yes, that's intentional. We does not currently support recovery after a fault (the recovery path is planned separately in PR https://github.com/vllm-project/vllm/pull/44428), so there's no benefit to enabling DeepEP's enable_shrink functionality at this stage.

Comment (tlrmchlsmth) [reply vllm/distributed/device_communicators/all2all.py:270]: Is DeepEP's `enable_shrink` needed for the retry recovery mechanism? If it's only needed for scale-down recovery, should we change the variable name to be more descriptive and make that clear?

File: vllm/distributed/device_communicators/all2all.py
Comment (tlrmchlsmth) [inline vllm/distributed/device_communicators/all2all.py:1]: Note that we probably want to support DeepEPV2 in addition to the DeepEPLL and NIXL backends

File: vllm/distributed/device_communicators/all2all.py [hunk 7]
```diff
@@ -318,12 +324,42 @@ def get_handle(self, kwargs):
...
+        buf.get_local_buffer_tensor(dtype=torch.int8, use_rdma_buffer=True).zero_()
+        torch.accelerator.synchronize()
+        buf.low_latency_clean_mask_buffer()
+        torch.accelerator.synchronize()
+        if DeepEPLLAll2AllManager._last_mask is not None:
+            DeepEPLLAll2AllManager._last_mask.zero_()
+
+    def query_fault(self) -> tuple[torch.Tensor, torch.Tensor]:
+        current = self.query_active_mask()
+        if DeepEPLLAll2AllManager._last_mask is None:
```
Comment (tlrmchlsmth) [inline vllm/distributed/device_communicators/all2all.py:347]: Should this be the same as the NIXL EP `query_fault`?
`if last is None or last.shape != current.shape:`

File: vllm/distributed/device_communicators/all2all.py [hunk 8]
```diff
@@ -318,12 +324,42 @@ def get_handle(self, kwargs):
...
+    def clean_buffers(self) -> None:
+        buf = DeepEPLLAll2AllManager._buffer
+        if buf is None:
+            return
+        buf.get_local_buffer_tensor(dtype=torch.int8, use_rdma_buffer=True).zero_()
+        torch.accelerator.synchronize()
+        buf.low_latency_clean_mask_buffer()
+        torch.accelerator.synchronize()
+        if DeepEPLLAll2AllManager._last_mask is not None:
+            DeepEPLLAll2AllManager._last_mask.zero_()
```
Comment (tlrmchlsmth) [inline vllm/distributed/device_communicators/all2all.py]: Should this just set `DeepEPLLAll2AllManager._last_mask` to `None`? (Similar to NIXL EP's `clean_buffers`)

File: vllm/distributed/device_communicators/all2all.py [hunk 9]
```diff
@@ -502,6 +541,37 @@ def destroy(self):
...
+        state = NixlEPAll2AllManager._buffer
+        assert state is not None
+        if NixlEPAll2AllManager._mask is None:
+            NixlEPAll2AllManager._mask = torch.zeros(
+                self.max_num_ep_ranks, device="cuda", dtype=torch.int32
+            )
+        state.buffer.query_mask_buffer(NixlEPAll2AllManager._mask)
+        return NixlEPAll2AllManager._mask[: state.active_ep_size]
+
+    def clean_buffers(self) -> None:
```
Comment (tlrmchlsmth) [inline vllm/distributed/device_communicators/all2all.py]: Nothing calls `clean_buffers` - remove it and bring it back in the followup PR?

File: vllm/v1/worker/gpu_model_runner.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (tlrmchlsmth) [reply vllm/v1/worker/gpu_model_runner.py]: I think this may be a legitimate concern, but need to think about it more. This is hard to reason about due to async scheduling.

Can a later step call `query_fault()` before `AsyncGPUModelRunnerOutput.get_output()` raises the exception? Double buffering (like what we do in ModelRunnerV2) may make this easier to reason about

File: vllm/distributed/device_communicators/all2all.py
Comment (fangyuchu) [reply vllm/distributed/device_communicators/all2all.py:1]: I took a quick look at DeepEP v2, and it seems that fault tolerance is not supported yet. Supporting it on our side would probably require some development in DeepEP itself first.

File: vllm/distributed/device_communicators/all2all.py (hunk 6 above)
Comment (fangyuchu) [reply vllm/distributed/device_communicators/all2all.py:270]: It is needed for retry recovery as well. `enable_shrink` is a variable defined by DeepEP that essentially controls whether the mask feature is enabled. We're just passing it through here.

Comment (tlrmchlsmth) [reply vllm/distributed/device_communicators/all2all.py:270]: Why do we set  `self.support_fault_tolerance` to `False`? What is needed for DeepEP to support FT?

Comment (fangyuchu) [reply vllm/distributed/device_communicators/all2all.py:270]: To support a workable recovery flow, we need the FT framework introduced in PR #44428, which provides the retry mechanism. This PR itself only detects mask changes and raises an exception to prevent corrupted tokens from being sent to users; it does not implement any recovery logic.

The mask feature is always enabled in NIXL-EP, while in DeepEP-LL it is controlled by `enable_shrink` (which corresponds to `self.support_fault_tolerance` in this PR). Since this PR only surfaces the error and does not yet support recovery, I turned if off here. The plan is to turn it on together with PR #44428, where retry-based recovery is actually supported.

File: vllm/distributed/device_communicators/all2all.py (hunk 7 above)
Comment (fangyuchu) [reply vllm/distributed/device_communicators/all2all.py:347]: In NIXL-EP, PR #40881 introduced the concept of `active_ep_size` for elastic EP. This means the queried mask shape can change due to EEP resizing, so whenever the shape changes we need to reset `_last_mask`.

In DeepEP-LL, the mask shape is stable and will not change in this way. So we don’t need the same handling logic as NIXL-EP for shape changes.

File: vllm/v1/worker/gpu_model_runner.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (fangyuchu) [reply vllm/v1/worker/gpu_model_runner.py]: I think you are right. `query_fault()` and `get_output()` may overlap under async scheduling.

Currently, the all2all manager essentially maintains two states in vLLM: `_mask` and `_last_mask`.

- `_mask` queries the actual runtime kernel mask (later referred by `AsyncGPUModelRunnerOutput._current_mask`, and leads to the concern).
- `_last_mask` essentially represents the expected mask in healthy condition.

For `_mask`, we do not need to include the snapshot (`self._current_mask`) in `AsyncGPUModelRunnerOutput`. If `get_output()` detects `self._has_fault`, it can simply issue another `query_active_mask()` and return the latest runtime mask.

For `_last_mask`, we may not need to update it in `query_fault()` because it represents the healthy state we expect. As long as `_mask` differs from `_last_mask`, it indicates an error. We would only need to update `_last_mask` in recovery paths (e.g. `clean_buffers` for retry or `update_mask` in scale_down).

The revision is like: https://github.com/vllm-project/vllm/pull/43637/changes/d91c10ed80741cbd5624436725cccffe9743ff68#diff-80ee7e2a62f9dcfbb8a312dc4e3948557e97ef187290daebbcae1e28596bda29L328

File: vllm/distributed/device_communicators/all2all.py (hunk 9 above)
Comment (fangyuchu) [reply vllm/distributed/device_communicators/all2all.py]: Removed as suggested.

File: vllm/distributed/device_communicators/all2all.py (hunk 8 above)
Comment (fangyuchu) [reply vllm/distributed/device_communicators/all2all.py]: `clean_buffers` itself is removed in this PR.

File: vllm/v1/worker/gpu_model_runner.py [hunk 10]
```diff
@@ -280,6 +283,9 @@ def __init__(
                 if self._routed_experts is not None
                 else None
             )
+            if check_ep_fault:
+                has_fault, _ = get_ep_all2all_manager().query_fault()
```
Comment (tlrmchlsmth) [inline vllm/v1/worker/gpu_model_runner.py]: Should `query_fault` only return a single `torch.Tensor`, or are we going to use `current` in a subsequent PR?

**Review by tlrmchlsmth — APPROVED** [review]
Just one more question, but otherwise LGTM, thanks Yuchu!

File: vllm/v1/worker/gpu_model_runner.py (hunk 10 above)
Comment (fangyuchu) [reply vllm/v1/worker/gpu_model_runner.py]: Good catch. After the code changes, we no longer need to return current_active_mask here. I've removed it.

**Review by mgoin — APPROVED** [review]
