### PR TITLE
[Bugfix][Multimodal] Fix Qwen3-ASR audio preprocessing parity

### LINKED ISSUE #56981: [Bug]:  Qwen3-ASR audio preprocessing produces different audio-token counts from Hugging Face
Reproduced on unmodified upstream vLLM production code at commit: 000c7df9ffd3e470980fd4cd6b8ec1b0585500ff

The source checkout lacks generated version metadata, so collect_env reports N/A (dev). This environment uses the checkout's Python source with existing vLLM 0.29 CUDA extensions, not a fresh CUDA build.

### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
  OS: Ubuntu 22.04.5 LTS (x86_64)
  Kernel: Linux 5.15.0-190-generic
  Libc: glibc-2.35
  GCC: 11.4.0
  Python: 3.13.15, conda-forge, 64-bit

  CPU: Intel Xeon Gold 6444Y
  CPU sockets: 2
  Physical cores: 32
  Logical CPUs: 64

  GPU configuration: 8 × NVIDIA H100 PCIe
  CUDA_VISIBLE_DEVICES: 0
  NVIDIA driver: 610.57.04
  GPU 0 memory: 81559 MiB
  CUDA available: True
  CUDA used to build PyTorch: 13.0
  CUDA toolkit reported by nvcc: 13.3.73

  PyTorch imported version: 2.13.0+cu130
  PyTorch debug build: False

  Relevant installed packages:
  numpy==2.4.6
  transformers==5.15.1
  torch==2.13.0
  torchaudio==2.11.0
  torchvision==0.28.0
  torchcodec==0.16.0
  triton==3.7.1
  flashinfer-python==0.6.16.post3
  nvidia-cublas==13.1.1.3
  nvidia-cuda-runtime==13.0.96
  nvidia-cuda-nvrtc==13.0.88
  nvidia-cuda-nvcc==13.3.73
  nvidia-cudnn-cu13==9.20.0.48
  nvidia-nccl-cu13==2.29.7

  vLLM reported version: N/A (dev)
  vLLM build flags: CUDA Archs: Not Set; ROCm: Disabled; XPU: Disabled

  Relevant environment variables:
  CUDA_VISIBLE_DEVICES=0
  OMP_NUM_THREADS=1
  MKL_NUM_THREADS=1
  VLLM_PLUGINS=
  PYTORCH_NVML_BASED_CUDA_CHECK=1
  TORCHINDUCTOR_COMPILE_THREADS=1

  collect_env completed successfully (exit code 0).

```

</details>

### 🐛 Describe the bug

  Qwen3-ASR's vLLM audio processor produces different audio-placeholder counts from the checkpoint's native Hugging Face processor for the same waveform.

  For example, a 16,001-sample clip at 16 kHz produces 14 audio tokens in vLLM versus 13 in Hugging Face.

  ### Reproducer

  This uses synthetic 16 kHz audio and does not load model weights.

  ```python
  import numpy as np
  from transformers import AutoProcessor
  from vllm.config import ModelConfig
  from vllm.multimodal import MULTIMODAL_REGISTRY

  model = "Qwen/Qwen3-ASR-0.6B-hf"
  revision = "7f1569a48a89f3e3f4dc3a5c9d28bddd903bc76c"
  prompt = "<|audio_start|><|audio_pad|><|audio_end|>"

  hf = AutoProcessor.from_pretrained(model, revision=revision)
  processor = MULTIMODAL_REGISTRY.create_processor(ModelConfig(
      model, revision=revision, dtype="float32", max_model_len=4096,
      mm_processor_cache_gb=0,
  ))
  audio_id = hf.tokenizer.convert_tokens_to_ids("<|audio_pad|>")

  print("samples: vLLM audio tokens / HF audio tokens")
  for samples in (15999, 16001, 321):
      audio = np.random.RandomState(42).randn(samples).astype(np.float32)
      expected = hf(text=prompt, audio=audio, return_tensors="pt")
      actual = processor(
          prompt,
          mm_items=processor.info.parse_mm_data({"audio": audio}),
          hf_processor_mm_kwargs={},
      )
      print(samples, actual["prompt_token_ids"].count(audio_id),
            expected["input_ids"][0].tolist().count(audio_id))
  ```

  ### Actual output

  ```text
  samples: vLLM audio tokens / HF audio tokens
  15999 13 13
  16001 14 13
  321 1 7
  ```

  ### Expected behavior

  For each clip, vLLM should match the checkpoint's native HF preprocessing, including audio features and audio-placeholder counts.

  ### Investigation

  Two preprocessing differences appear responsible:

  - Qwen3-ASR inherits Omni's waveform padding to a multiple of the hop length, which can change feature lengths and audio-token counts.
  - Its processor hardcodes `WhisperFeatureExtractor` instead of honoring the native checkpoint's `Qwen3ASRFeatureExtractor`, including its minimum-length padding.

  I have a candidate fix and regression tests. Of 48 new cases, 34 fail on unmodified upstream; all 48 pass with the fix.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by MatthewCYM**
## Purpose
Fixes #56981.

Qwen3-ASR currently inherits Omni's waveform padding and forces a Whisper feature extractor, which can change audio features and placeholder counts relative to the checkpoint's upstream processor.

Following the review feedback, this revision:

- Uses the upstream Transformers `Qwen3ASRProcessor` and removes the bundled processor and its registration.
- Requires Transformers >=5.13.0 and updates the corresponding test metadata.
- Uses `BaseMultiModalProcessor` without Omni's waveform padding.
- Processes clips independently and packs valid features, preserving parity across differently sized clips and partial cache hits.
- Preserves text-only and precomputed-feature inputs.

Both checkpoint formats remain supported: the original checkpoint declares `WhisperFeatureExtractor`, while the native `-hf` checkpoint declares `Qwen3ASRFeatureExtractor`.

No shared Omni/VL implementation, model weights, encoder kernels, or speculative-decoding behavior is changed.

## Test Plan

Validated against upstream main `528fa835fd37d0805a824d516e22f88df61a771a`
  with Transformers 5.13.0 and 5.17.0.

```bash
.venv/bin/python -m pytest \
  tests/models/multimodal/processing/test_qwen3_asr.py \
  tests/models/multimodal/processing/test_qwen3_omni.py \
  tests/multimodal/test_audio.py \
  tests/models/multimodal/processing/test_common.py \
  tests/model_executor/test_qwen3_asr_mrope.py \
  tests/entrypoints/speech_to_text/transcription/test_qwen3_asr_sanitize_prompt.py \
  tests/entrypoints/speech_to_text/transcription/test_transcription_inter_chunk_spacing.py \
  -k 'not transformers and (Qwen3-ASR or test_qwen3_asr or test_qwen3_omni or test_audio.py or ForcedAligner or test_transcription_inter_chunk_spacing)' \
  -q
```

- 152 repository tests passed per Transformers version, including all 50 new regression cases.
- Supplementary local validation passed another 63 pytest cases and four realtime-processor comparisons per version. These supplementary checks are not all included in this PR.
- Applicable repository pre-commit hooks, the scoped manual Python 3.12 mypy hook, and whitespace checks passed.

### Model validation

Tested both `Qwen/Qwen3-ASR-0.6B` and `Qwen/Qwen3-ASR-0.6B-hf` with both Transformers versions.

Each run compared raw audio against independently computed upstream features in the same vLLM engine, using 32 LibriSpeech test-clean utterances plus 32 near-hop-boundary variants. Settings: single H100, BF16, greedy decoding, eager execution, `max_num_seqs=1`, and processor/prefix caches disabled.

All four model/version combinations matched prompt IDs and generated token IDs on 64/64 clips. Raw/reference WER was 2.8846% in every run. This is a bounded correctness evaluation, not a full-split accuracy or speed benchmark.

Environment: Python 3.13.15, PyTorch 2.13.0+cu130, and NumPy 2.4.6. Tests used this checkout's Python source with existing vLLM 0.29 CUDA extensions, not a fresh CUDA build. Full upstream CI remains necessary. Realtime and forced-aligner checks cover preprocessing, not complete streaming or timestamp-accuracy evaluation.

## Related work and disclosure

This uses the processor hook introduced by #53610; that refactor does not implement this ASR preprocessing fix. #57076 addresses the separate post-expansion truncation issue.

AI assistance was used for implementation, investigation, and test preparation.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
@ywang96 @Isotr0py would it be better to drop the native processor implementation and simply require `transformeres>=5.13`?

**Comment by MatthewCYM** [comment]
Hi @DarkLight1337, I retained the bundled processor to preserve compatibility with Transformers 5.10.4 and existing checkpoints. Happy to switch to the upstream Transformers processor if requiring >=5.13 is preferred.

**Comment by Aatman09** [comment]
Why didn't you use the `Qwen3ASRFeatureExtractor` and instead used `SequentialFeatureExtractor`

**Comment by Isotr0py** [comment]
> would it be better to drop the native processor implementation and simply require transformeres>=5.13

Sure, we should remove the native ones, we only port them because of missing transfomers support at day0

File: vllm/model_executor/models/qwen3_asr.py [hunk 1]
```diff
@@ -279,8 +278,36 @@ def _parse_audio_data(
 
 
 class Qwen3ASRMultiModalProcessor(
-    Qwen3OmniMoeThinkerMultiModalProcessor,
+    BaseMultiModalProcessor[Qwen3ASRProcessingInfo],
 ):
+    def _call_hf_processor(
```
Comment (DarkLight1337) [inline vllm/model_executor/models/qwen3_asr.py:300]: Please refactor this to use `_get_hf_mm_text` and `_postprocess_hf_mm_data`

Comment (MatthewCYM) [reply vllm/model_executor/models/qwen3_asr.py:300]: Thanks! Refactored text setup and output conversion into the requested hooks. Retained per-clip processing because HF batch padding changes audio features and would break cache independence. Added regression coverage and validated both checkpoint formats with Transformers 5.13 and 5.17.

File: vllm/model_executor/models/qwen3_asr.py [hunk 2]
```diff
@@ -280,33 +281,66 @@ def _parse_audio_data(
...
-            mask = hf_inputs["input_features_mask"][0]
-            features.append(hf_inputs["input_features"][0, :, mask.bool()])
-            masks.append(mask)
-
-        return BatchFeature(
-            dict(
-                input_audio_features=torch.cat(features, dim=1),
-                feature_attention_mask=masks,
-                audio_feature_lengths=torch.stack([mask.sum() for mask in masks]),
+        audios = cast(list[AudioItem], hf_data["audio"])
```
Comment (DarkLight1337) [inline vllm/model_executor/models/qwen3_asr.py]: Don't assume that the "audio" key always exists. Take a look at how the other processors handle this

File: vllm/model_executor/models/qwen3_asr.py [hunk 3]
```diff
@@ -280,33 +281,66 @@ def _parse_audio_data(
...
+        mm_items: MultiModalDataItems,
+        hf_kwargs: Mapping[str, object],
+    ) -> HFMultiModalInputs:
+        hf_inputs = super()._get_hf_mm_inputs(mm_items, hf_kwargs)
+        kwargs = dict(hf_inputs.hf_kwargs)
+        if "truncation" not in hf_kwargs:
+            # HF already defaults to no truncation. The base's flat default
+            # would override config kwargs or conflict with nested audio kwargs.
+            kwargs.pop("truncation", None)
+        return hf_inputs._replace(hf_kwargs=kwargs)
```
Comment (DarkLight1337) [inline vllm/model_executor/models/qwen3_asr.py:298]: Is this change really required?

Comment (MatthewCYM) [reply vllm/model_executor/models/qwen3_asr.py:298]: The upstream Hugging Face Qwen3-ASR implementation supports audio_kwargs={"truncation": True}. However, vLLM’s base hook injects a flat truncation=False, causing this supported option to fail with Keyword argument truncation was passed two times.

Comment (DarkLight1337) [reply vllm/model_executor/models/qwen3_asr.py:298]: Are you referring to `call_hf_processor`? That only sets `truncation=False` as the default; it doesn't overwrite user kwargs. Is there really a need for this override?

Comment (MatthewCYM) [reply vllm/model_executor/models/qwen3_asr.py:298]: I mean BaseMultiModalProcessor._get_hf_mm_inputs: when truncation is supplied inside audio_kwargs, the injected top-level default remains, and Transformers rejects the duplicate.

On this PR, removing only Qwen3ASRMultiModalProcessor._get_hf_mm_inputs makes the following request fail. Tested with Transformers 5.17.0.
```python
import numpy as np
from vllm import LLM, SamplingParams

llm = LLM(
    model="Qwen/Qwen3-ASR-0.6B-hf",
    dtype="bfloat16",
    max_model_len=4096,
    max_num_seqs=1,
    gpu_memory_utilization=0.2,
    enforce_eager=True,
)

llm.generate(
    {
        "prompt": (
            "<|im_start|>system\n<|im_end|>\n"
            "<|im_start|>user\n"
            "<|audio_start|><|audio_pad|><|audio_end|>"
            "<|im_end|>\n<|im_start|>assistant\n"
        ),
        "multi_modal_data": {
            "audio": (np.zeros(32000, dtype=np.float32), 16000)
        },
        "mm_processor_kwargs": {
            "audio_kwargs": {
                "truncation": True,
                "max_length": 16000,
            }
        },
    },
    SamplingParams(temperature=0, max_tokens=1),
)
```
raises ValueError: Keyword argument truncation was passed two times: in a dictionary for audio_kwargs and as a **kwarg.

Comment (DarkLight1337) [reply vllm/model_executor/models/qwen3_asr.py:298]: I think https://github.com/vllm-project/vllm/pull/56372 would be a better fix for that

Comment (MatthewCYM) [reply vllm/model_executor/models/qwen3_asr.py:298]: Thanks. That makes sense. Would you prefer that I remove the ASR-specific _get_hf_mm_inputs override and its truncation tests from this PR, and share the audio_kwargs reproducer in #56372 instead?

Comment (DarkLight1337) [reply vllm/model_executor/models/qwen3_asr.py:298]: Do you have urgency to merge this PR? If not, let's wait for #56372 first

File: vllm/model_executor/models/qwen3_asr.py (hunk 2 above)
Comment (MatthewCYM) [reply vllm/model_executor/models/qwen3_asr.py]: Thanks. Updated this to follow the guarded audio lookup and list assertion used in MiDashengLMMultiModalProcessor. Missing or empty audio now skips extraction, and postprocessing leaves the data unchanged when input_features is absent.

File: vllm/model_executor/models/qwen3_asr.py (hunk 3 above)
Comment (MatthewCYM) [reply vllm/model_executor/models/qwen3_asr.py:298]: Happy to wait for #56372, then rebase and rerun the ASR tests.

File: requirements/common.txt [hunk 4]
```diff
@@ -7,7 +7,7 @@ requests >= 2.26.0
 tqdm
 blake3
 py-cpuinfo
-transformers >= 5.10.4
+transformers >= 5.13.0
```
Comment (DarkLight1337) [inline requirements/common.txt]: Revert this

Comment (MatthewCYM) [reply requirements/common.txt]: Reverted
