### PR TITLE
[CPU] Gate the AVX10.2 paths on compiler support

### PR DESCRIPTION
**Pull request by ganeshr10**
## Purpose

`cmake/cpu_extension.cmake` requires `gcc/g++ >= 12.3` for the x86 backend, but `csrc/cpu/sgl-kernels` has used AVX10.2 since #49942, and AVX10.2 landed in GCC 15. On anything older the build does not lose a fast path, it fails outright:

```
common.h:537: error: parameter to builtin not valid: avx10.2
gemm_fp8_w8a8.cpp:775: error: attribute 'target' argument 'avx10.2' is unknown
gemm_fp8_w8a8.cpp:777: error: '_mm256_cvtph_hf8' was not declared in this scope
```

Five objects fail, so a source build on any current distro toolchain is broken — Ubuntu 24.04 (gcc 13), Debian 12 (gcc 12), RHEL 9 (gcc 11). `docker/Dockerfile.cpu` is unaffected because it installs `gcc-15` from a PPA, which is why CI does not see this.

This probes for `-mavx10.2` and defines `VLLM_CPU_HAS_AVX10_2` accordingly, guarding the two `target("avx10.2")` helpers and their two call sites. The AVX512 loops directly below each call site already handle the work. On GCC 15+ nothing changes.

The probe mirrors the `-mamx-fp8` handling a few lines above, which gates "on actual flag support rather than compiler version alone" — a version check would also have been wrong here, since AVX10.2 is 15 while AVX10.1 is 14.

## Test Plan

Build `main` plus this patch for CPU on GCC 12.4, and confirm the probe result reaches the guarded translation unit.

## Test Result

`-mavx10.2` rejected by GCC 12.4 and 13.4. Configure reports:

```
-- Performing Test COMPILER_SUPPORTS_AVX10_2_FLAG - Failed
-- AVX10.2 paths disabled: compiler does not support -mavx10.2 (compiler: GNU 12.4.0)
```

`compile_commands.json` carries `-DVLLM_CPU_HAS_AVX10_2=0` on `gemm_fp8_w8a8.cpp`, so the define reaches the unit rather than the header default masking a plumbing gap.

Full CPU build on GCC 12.4 completes with no errors and imports: `vllm 0.29.1rc1.dev524+g64a48b19b`, torch 2.13.0+cpu. Unpatched `main` fails the five objects above on the same machine.

### CODE REVIEW

File: cmake/cpu_extension.cmake
Comment (bigPYJ1151) [inline cmake/cpu_extension.cmake:648]: Let's add the flag with the same pattern of these.

Comment (ganeshr10) [reply cmake/cpu_extension.cmake:648]: Done.

File: cmake/cpu_extension.cmake [hunk 1]
```diff
@@ -625,8 +637,14 @@ if (ENABLE_X86_ISA)
...
-        target_compile_definitions(_C PRIVATE "-DCPU_CAPABILITY_AMXFP8")
-        message(STATUS "AMX-FP8 (Diamond Rapids) enabled")
+    target_compile_definitions(_C PRIVATE "-DCPU_CAPABILITY_AMXFP8")
+    message(STATUS "AMX-FP8 (Diamond Rapids) enabled")
+    endif()
+
+    # For the sgl-kernels AVX10.2 fp8 quantize paths
+    if (AVX10_2_SUPPORTED)
+    target_compile_definitions(_C PRIVATE "-DCPU_CAPABILITY_AVX10_2")
+    message(STATUS "AVX10.2 enabled")
```
Comment (bigPYJ1151) [inline cmake/cpu_extension.cmake]: Please add indentation as the previous

Comment (ganeshr10) [reply cmake/cpu_extension.cmake]: Done

**Review by bigPYJ1151 — APPROVED** [review]
