### PR TITLE
[bugfix] Fix Dynamo unexpected keyword argument

### PR DESCRIPTION
**Pull request by samutamm**
## Purpose

Fix QuantFP8 with torch.compile on ROCm when CustomOP `quant_fp8` is disabled with `--compilation-config '{"custom_ops": ["-quant_fp8"]}'`.

Current main branch raises error:

```
(EngineCore_DP0 pid=565)   File "/app/vllm/vllm/v1/executor/multiproc_executor.py", line 375, in collective_rpc
(EngineCore_DP0 pid=565)     return aggregate(get_response())
(EngineCore_DP0 pid=565)                      ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=565)   File "/app/vllm/vllm/v1/executor/multiproc_executor.py", line 358, in get_response
(EngineCore_DP0 pid=565)     raise RuntimeError(
(EngineCore_DP0 pid=565) RuntimeError: Worker failed with error 'Observed exception
(EngineCore_DP0 pid=565)   Explanation: Dynamo found no exception handler at the top-level compiled function when encountering an exception. Exception will propagate outside the compiled region.
(EngineCore_DP0 pid=565)   Hint: Dynamo has detected that tracing the code will result in an error when running in eager. Please double check that your code doesn't contain a similar error when actually running eager/uncompiled.
(EngineCore_DP0 pid=565)   Hint: It may be possible to write Dynamo tracing rules for this code. Please report an issue to PyTorch if you encounter this graph break often and it is causing performance issues.
(EngineCore_DP0 pid=565) 
(EngineCore_DP0 pid=565)   Developer debug context: raised exception TypeError([ConstantVariable(str: "Unexpected keyword arguments: ['use_triton']")])
(EngineCore_DP0 pid=565) 
(EngineCore_DP0 pid=565)  For more details about this graph break, please visit: https://meta-pytorch.github.io/compile-graph-break-site/gb/gb0088.html
(EngineCore_DP0 pid=565) 
(EngineCore_DP0 pid=565) from user code:
(EngineCore_DP0 pid=565)    File "/app/vllm/vllm/model_executor/models/qwen3_vl_moe.py", line 133, in forward
(EngineCore_DP0 pid=565)     hidden_states, residual = layer(
(EngineCore_DP0 pid=565) 
(EngineCore_DP0 pid=565) Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"
(EngineCore_DP0 pid=565) ', please check the stack trace above for the root cause
```
This was introduced in https://github.com/vllm-project/vllm/pull/33047 .

## Test Plan

Server
```
export VLLM_ROCM_USE_AITER=1
export VLLM_ROCM_USE_AITER_MOE=1
vllm serve Qwen/Qwen3-VL-235B-A22B-Instruct-FP8 \
    -tp 8 \
	--enable-expert-parallel \
	--max-num-batched-tokens 32768 \
	--compilation-config '{"custom_ops": ["-quant_fp8"]}' \
	--max-num-seqs 1024 \
    --distributed-executor-backend mp \
	--kv-cache-dtype fp8 \
	--no-enable-prefix-caching
```

## Test Result

After moving `use_triton` from kwargs to positional argument, Dynamo error disappears. 

---
<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [x] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [x] The test plan, such as providing test command.
- [x] The test results, such as pasting the results comparison before and after, or e2e results
- [ ] (Optional) The necessary documentation update, such as updating `supported_models.md` and `examples` for a new model.
- [ ] (Optional) Release notes update. If your change is user facing, please update the release notes draft in the [Google Doc](https://docs.google.com/document/d/1YyVqrgX4gHTtrstbq8oWUImOyPCKSGnJ7xtTpmXzlRs/edit?tab=t.0).
</details>

### CODE REVIEW

**Comment by samutamm** [comment]
https://github.com/vllm-project/vllm/pull/34320
