### PR TITLE
[CI] Fix pre-commit issue

### PR DESCRIPTION
**Pull request by yewentao256**
## Purpose

Fixes https://github.com/vllm-project/vllm/actions/runs/25820013150/job/75858527795?pr=39337

```bash
$ mypy --python-version 3.13 
Error: vllm/model_executor/layers/quantization/quark/quark_moe.py:1647: error: Name "FusedMoE" is not defined  [name-defined]
Error: vllm/model_executor/layers/quantization/quark/quark_moe.py:1701: error: Unexpected keyword argument "shared_experts" for "make_nvfp4_moe_kernel"  [call-arg]
Error: vllm/model_executor/layers/quantization/quark/quark_moe.py:1724: error: Name "FusedMoE" is not defined  [name-defined]
vllm/model_executor/layers/fused_moe/oracle/nvfp4.py:471: note: "make_nvfp4_moe_kernel" defined here
Error: vllm/model_executor/layers/quantization/quark/quark_moe.py:1722: error: Signature of "apply" incompatible with supertype "vllm.model_executor.layers.fused_moe.fused_moe_method_base.FusedMoEMethodBase"  [override]

```

## Test

CI should be green now

### CODE REVIEW

**Review by yewentao256 — COMMENTED** [review]
Seems introduced in https://github.com/vllm-project/vllm/pull/35859
CC @fxmarty-amd @mgoin
