### ISSUE TITLE
[Bug] meta-llama/Llama-3.2-11B-Vision model initialization fails on `vllm 0.11.0`

### ISSUE THREAD

**Issue by mrtpk** [vllm-project/vllm#27198]
### Your current environment

```
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 24.04.3 LTS (x86_64)
GCC version                  : (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version                : Could not collect
CMake version                : Could not collect
Libc version                 : glibc-2.39

==============================
       PyTorch Info
==============================
PyTorch version              : 2.8.0+cu128
Is debug build               : False
CUDA used to build PyTorch   : 12.8
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.12 | packaged by Anaconda, Inc. | (main, Oct 14 2025, 16:16:33) [GCC 11.2.0] (64-bit runtime)
Python platform              : Linux-6.8.0-85-generic-x86_64-with-glibc2.39

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : Could not collect
CUDA_MODULE_LOADING set to   : LAZY
GPU models and configuration : GPU 0: NVIDIA GeForce RTX 5090
Nvidia driver version        : 580.65.06
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 57 bits virtual
Byte Order:                           Little Endian
CPU(s):                               48
On-line CPU(s) list:                  0-47
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Xeon(R) w7-3455
CPU family:                           6
Model:                                143
Thread(s) per core:                   2
Core(s) per socket:                   24
Socket(s):                            1
Stepping:                             8
CPU(s) scaling MHz:                   23%
CPU max MHz:                          4800.0000
CPU min MHz:                          800.0000
BogoMIPS:                             4992.00
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect user_shstk avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req vnmi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr ibt amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                       VT-x
L1d cache:                            1.1 MiB (24 instances)
L1i cache:                            768 KiB (24 instances)
L2 cache:                             48 MiB (24 instances)
L3 cache:                             67.5 MiB (1 instance)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-47
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

==============================
Versions of relevant libraries
==============================
[pip3] numpy==2.2.6
[pip3] nvidia-cublas-cu12==12.8.4.1
[pip3] nvidia-cuda-cupti-cu12==12.8.90
[pip3] nvidia-cuda-nvrtc-cu12==12.8.93
[pip3] nvidia-cuda-runtime-cu12==12.8.90
[pip3] nvidia-cudnn-cu12==9.10.2.21
[pip3] nvidia-cufft-cu12==11.3.3.83
[pip3] nvidia-cufile-cu12==1.13.1.3
[pip3] nvidia-curand-cu12==10.3.9.90
[pip3] nvidia-cusolver-cu12==11.7.3.90
[pip3] nvidia-cusparse-cu12==12.5.8.93
[pip3] nvidia-cusparselt-cu12==0.7.1
[pip3] nvidia-nccl-cu12==2.27.3
[pip3] nvidia-nvjitlink-cu12==12.8.93
[pip3] nvidia-nvshmem-cu12==3.3.20
[pip3] nvidia-nvtx-cu12==12.8.90
[pip3] pyzmq==27.1.0
[pip3] torch==2.8.0
[pip3] torchaudio==2.8.0
[pip3] torchvision==0.23.0
[pip3] transformers==4.57.1
[pip3] triton==3.4.0
[conda] numpy                                2.2.6            pypi_0           pypi
[conda] nvidia-cublas-cu12                   12.8.4.1         pypi_0           pypi
[conda] nvidia-cuda-cupti-cu12               12.8.90          pypi_0           pypi
[conda] nvidia-cuda-nvrtc-cu12               12.8.93          pypi_0           pypi
[conda] nvidia-cuda-runtime-cu12             12.8.90          pypi_0           pypi
[conda] nvidia-cudnn-cu12                    9.10.2.21        pypi_0           pypi
[conda] nvidia-cufft-cu12                    11.3.3.83        pypi_0           pypi
[conda] nvidia-cufile-cu12                   1.13.1.3         pypi_0           pypi
[conda] nvidia-curand-cu12                   10.3.9.90        pypi_0           pypi
[conda] nvidia-cusolver-cu12                 11.7.3.90        pypi_0           pypi
[conda] nvidia-cusparse-cu12                 12.5.8.93        pypi_0           pypi
[conda] nvidia-cusparselt-cu12               0.7.1            pypi_0           pypi
[conda] nvidia-nccl-cu12                     2.27.3           pypi_0           pypi
[conda] nvidia-nvjitlink-cu12                12.8.93          pypi_0           pypi
[conda] nvidia-nvshmem-cu12                  3.3.20           pypi_0           pypi
[conda] nvidia-nvtx-cu12                     12.8.90          pypi_0           pypi
[conda] pyzmq                                27.1.0           pypi_0           pypi
[conda] torch                                2.8.0            pypi_0           pypi
[conda] torchaudio                           2.8.0            pypi_0           pypi
[conda] torchvision                          0.23.0           pypi_0           pypi
[conda] transformers                         4.57.1           pypi_0           pypi
[conda] triton                               3.4.0            pypi_0           pypi

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.11.0
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled
GPU Topology:
  	[4mGPU0	CPU Affinity	NUMA Affinity	GPU NUMA ID[0m
GPU0	 X 	0-47	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

==============================
     Environment Variables
==============================
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY

```

### 🐛 Describe the bug

`vllm serve meta-llama/Llama-3.2-11B-Vision` fails on  `vllm 0.11.0`. It works on `vllm 0.10.2`.

Error: `MllamaProcessor' object has no attribute '_get_num_multimodal_tokens`.

Upon debugging, vLLM 0.11’s Transformers-backend expects the HF processor to implement a method called `_get_num_multimodal_tokens` which is [not implemented for mllama](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mllama/processing_mllama.py) in `transformers 4.57.1`.

## Sanity Check
```
from transformers import AutoProcessor
proc = AutoProcessor.from_pretrained("meta-llama/Llama-3.2-11B-Vision-Instruct")
print(hasattr(proc, "_get_num_multimodal_tokens"))  # should be True but not
```

## Useful links
* https://huggingface.co/docs/transformers/main/en/transformers_as_backend#multimodal-models
* https://blog.vllm.ai/2025/04/11/transformers-backend.html

## Run Log
```
INFO 10-20 14:22:27 [__init__.py:216] Automatically detected platform cuda.
INFO 10-20 14:22:29 [api_server.py:1839] vLLM API server version 0.11.0
INFO 10-20 14:22:29 [utils.py:233] non-default args: {'model_tag': 'meta-llama/Llama-3.2-11B-Vision', 'model': 'meta-llama/Llama-3.2-11B-Vision'}
INFO 10-20 14:22:30 [model.py:547] Resolved architecture: TransformersForMultimodalLM
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 10-20 14:22:30 [model.py:1510] Using max model len 131072
INFO 10-20 14:22:30 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=2048.
WARNING 10-20 14:22:31 [utils.py:184] TransformersForMultimodalLM has no vLLM implementation, falling back to Transformers implementation. Some features may not be supported and performance may not be optimal.
INFO 10-20 14:22:34 [__init__.py:216] Automatically detected platform cuda.
INFO 10-20 14:22:36 [core.py:644] Waiting for init message from front-end.
INFO 10-20 14:22:36 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='meta-llama/Llama-3.2-11B-Vision', speculative_config=None, tokenizer='meta-llama/Llama-3.2-11B-Vision', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Llama-3.2-11B-Vision, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}
WARNING 10-20 14:22:36 [utils.py:184] TransformersForMultimodalLM has no vLLM implementation, falling back to Transformers implementation. Some features may not be supported and performance may not be optimal.
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 10-20 14:22:37 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 10-20 14:22:37 [topk_topp_sampler.py:66] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 08868a34-7fd8-4913-9d34-ff76e6d38ce8)')' thrown while requesting HEAD https://huggingface.co/meta-llama/Llama-3.2-11B-Vision/resolve/main/preprocessor_config.json
Retrying in 1s [Retry 1/5].
ERROR 10-20 14:22:55 [core.py:708] EngineCore failed to start.
ERROR 10-20 14:22:55 [core.py:708] Traceback (most recent call last):
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
ERROR 10-20 14:22:55 [core.py:708]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 10-20 14:22:55 [core.py:708]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 498, in __init__
ERROR 10-20 14:22:55 [core.py:708]     super().__init__(vllm_config, executor_class, log_stats,
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 83, in __init__
ERROR 10-20 14:22:55 [core.py:708]     self.model_executor = executor_class(vllm_config)
ERROR 10-20 14:22:55 [core.py:708]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
ERROR 10-20 14:22:55 [core.py:708]     self._init_executor()
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 54, in _init_executor
ERROR 10-20 14:22:55 [core.py:708]     self.collective_rpc("init_device")
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
ERROR 10-20 14:22:55 [core.py:708]     return [run_method(self.driver_worker, method, args, kwargs)]
ERROR 10-20 14:22:55 [core.py:708]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3122, in run_method
ERROR 10-20 14:22:55 [core.py:708]     return func(*args, **kwargs)
ERROR 10-20 14:22:55 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 259, in init_device
ERROR 10-20 14:22:55 [core.py:708]     self.worker.init_device()  # type: ignore
ERROR 10-20 14:22:55 [core.py:708]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 201, in init_device
ERROR 10-20 14:22:55 [core.py:708]     self.model_runner: GPUModelRunner = GPUModelRunner(
ERROR 10-20 14:22:55 [core.py:708]                                         ^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 421, in __init__
ERROR 10-20 14:22:55 [core.py:708]     self.mm_budget = MultiModalBudget(
ERROR 10-20 14:22:55 [core.py:708]                      ^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/worker/utils.py", line 48, in __init__
ERROR 10-20 14:22:55 [core.py:708]     .get_max_tokens_per_item_by_nonzero_modality(model_config,
ERROR 10-20 14:22:55 [core.py:708]      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/multimodal/registry.py", line 167, in get_max_tokens_per_item_by_nonzero_modality
ERROR 10-20 14:22:55 [core.py:708]     max_tokens_per_item = self.get_max_tokens_per_item_by_modality(
ERROR 10-20 14:22:55 [core.py:708]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/multimodal/registry.py", line 143, in get_max_tokens_per_item_by_modality
ERROR 10-20 14:22:55 [core.py:708]     return profiler.get_mm_max_contiguous_tokens(
ERROR 10-20 14:22:55 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/multimodal/profiling.py", line 282, in get_mm_max_contiguous_tokens
ERROR 10-20 14:22:55 [core.py:708]     return self._get_mm_max_tokens(seq_len,
ERROR 10-20 14:22:55 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/multimodal/profiling.py", line 255, in _get_mm_max_tokens
ERROR 10-20 14:22:55 [core.py:708]     max_tokens_per_item = self.processing_info.get_mm_max_tokens_per_item(
ERROR 10-20 14:22:55 [core.py:708]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/model_executor/models/transformers.py", line 226, in get_mm_max_tokens_per_item
ERROR 10-20 14:22:55 [core.py:708]     return {"image": self.get_max_image_tokens()}
ERROR 10-20 14:22:55 [core.py:708]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708]   File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/model_executor/models/transformers.py", line 233, in get_max_image_tokens
ERROR 10-20 14:22:55 [core.py:708]     mm_tokens = processor._get_num_multimodal_tokens(
ERROR 10-20 14:22:55 [core.py:708]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-20 14:22:55 [core.py:708] AttributeError: 'MllamaProcessor' object has no attribute '_get_num_multimodal_tokens'
Process EngineCore_DP0:
Traceback (most recent call last):
File "anaconda3/envs/vllm_env/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
File "anaconda3/envs/vllm_env/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 712, in run_engine_core
    raise e
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
    engine_core = EngineCoreProc(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 498, in __init__
    super().__init__(vllm_config, executor_class, log_stats,
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 83, in __init__
    self.model_executor = executor_class(vllm_config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
    self._init_executor()
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 54, in _init_executor
    self.collective_rpc("init_device")
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
    return [run_method(self.driver_worker, method, args, kwargs)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3122, in run_method
    return func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 259, in init_device
    self.worker.init_device()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 201, in init_device
    self.model_runner: GPUModelRunner = GPUModelRunner(
                                        ^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 421, in __init__
    self.mm_budget = MultiModalBudget(
                    ^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/worker/utils.py", line 48, in __init__
    .get_max_tokens_per_item_by_nonzero_modality(model_config,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/multimodal/registry.py", line 167, in get_max_tokens_per_item_by_nonzero_modality
    max_tokens_per_item = self.get_max_tokens_per_item_by_modality(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/multimodal/registry.py", line 143, in get_max_tokens_per_item_by_modality
    return profiler.get_mm_max_contiguous_tokens(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/multimodal/profiling.py", line 282, in get_mm_max_contiguous_tokens
    return self._get_mm_max_tokens(seq_len,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/multimodal/profiling.py", line 255, in _get_mm_max_tokens
    max_tokens_per_item = self.processing_info.get_mm_max_tokens_per_item(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/model_executor/models/transformers.py", line 226, in get_mm_max_tokens_per_item
    return {"image": self.get_max_image_tokens()}
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/model_executor/models/transformers.py", line 233, in get_max_image_tokens
    mm_tokens = processor._get_num_multimodal_tokens(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MllamaProcessor' object has no attribute '_get_num_multimodal_tokens'
[rank0]:[W1020 14:22:56.374535045 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Traceback (most recent call last):
File "anaconda3/envs/vllm_env/bin/vllm", line 7, in <module>
    sys.exit(main())
            ^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/entrypoints/cli/main.py", line 54, in main
    args.dispatch_function(args)
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/entrypoints/cli/serve.py", line 57, in cmd
    uvloop.run(run_server(args))
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/uvloop/__init__.py", line 96, in run
    return __asyncio.run(
        ^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
        ^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/uvloop/__init__.py", line 48, in wrapper
    return await main
        ^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1884, in run_server
    await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1902, in run_server_worker
    async with build_async_engine_client(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
        ^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 180, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
        ^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 225, in build_async_engine_client_from_engine_args
    async_llm = AsyncLLM.from_vllm_config(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/utils/__init__.py", line 1572, in inner
    return fn(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 207, in from_vllm_config
    return cls(
        ^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 134, in __init__
    self.engine_core = EngineCoreClient.make_async_mp_client(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 102, in make_async_mp_client
    return AsyncMPClient(*client_args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 769, in __init__
    super().__init__(
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 448, in __init__
    with launch_core_engines(vllm_config, executor_class,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "anaconda3/envs/vllm_env/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 732, in launch_core_engines
    wait_for_engine_startup(
File "anaconda3/envs/vllm_env/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 785, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Please consider using other models (e.g. Llama 4)

**Comment by DarkLight1337** [comment]
cc @Isotr0py I thought you added this before?

**Comment by mrtpk** [comment]
So, how should we proceed?

**Comment by ppalantir** [comment]
> We don't support this model in V1 anymore because it's an encoder-decoder model.

@DarkLight1337 Thanks for the explanation. I’m curious why Qwen2.5-VL remains supported in V1, since it is also an encoder–decoder architecture. Is there a specific technical reason or exception for Qwen2.5-VL?

**Comment by DarkLight1337** [comment]
By encoder-decoder model here I am referring to models that use cross-attention.
