### ISSUE TITLE
[Bug]: wrong cutlass Arch import

### ISSUE THREAD

**Issue by BramVanroy** [vllm-project/vllm#47570]
### Your current environment

When running a QAT model like google/gemma-4-12B-it-qat-w4a16-ct, I get this error:

> ImportError: cannot import name 'Arch' from 'cutlass.base_dsl' (.venv/lib/python3.13/site-packages/nvidia_cutlass_dsl/python_packages/cutlass/base_dsl/__init__.py). Did you mean: 'torch'?

After looking at many [different versions of cutlass](https://github.com/NVIDIA/cutlass/blob/v4.5.2/python/CuTeDSL/cutlass/base_dsl/__init__.py), I see that it does not expose `Arch` in its init. It should be imported from [`arch`](https://github.com/NVIDIA/cutlass/blob/v4.5.2/python/CuTeDSL/cutlass/base_dsl/arch.py#L65).

Environment

- CUDA 13
- vllm 0.24.0
- H100 node
- nvidia-cutlass-dsl==4.5.2
- nvidia-cutlass-dsl-libs-base==4.5.2
- nvidia-cutlass-dsl-libs-cu13==4.5.2

### 🐛 Describe the bug

Load and run `google/gemma-4-12B-it-qat-w4a16-ct`, e.g. `vllm serve google/gemma-4-12B-it-qat-w4a16-ct`.

### Before submitting a new issue...

Related but incorrectly closed: https://github.com/vllm-project/vllm/issues/43141

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by SmartAI** [comment]
I dug into this and I believe the offending import is not in vLLM or flashinfer, but in old **quack-kernels** wheels.

- `quack-kernels` 0.3.x–0.4.0 ship `from cutlass.base_dsl import Arch` (e.g. `quack/rmsnorm.py:24` in the 0.4.0 wheel — matching the traceback in #43141, which is the same root cause).
- That import only works on cutlass-dsl <= 4.4.2, where `base_dsl/dsl.py` had a top-level `from .arch import Arch` that got re-exported via `base_dsl/__init__.py`'s `from .dsl import *`. In 4.5.2 that import was moved out of module top level, so `cutlass.base_dsl.Arch` no longer exists.
- quack fixed the import in 0.4.1 (`from cutlass.base_dsl.arch import Arch`).

vLLM pins `nvidia-cutlass-dsl[cu13]==4.5.2` but only requires `quack-kernels>=0.3.3` (requirements/cuda.txt), so any environment that ends up with quack <= 0.4.0 — stale envs, lockfiles, or lowest-version resolution — gets this ImportError at runtime. A fresh resolve typically picks quack 0.5.0 (0.5.1+ pin `nvidia-cutlass-dsl==4.6.0.dev0` and are excluded), which is why it doesn't reproduce everywhere.

@BramVanroy could you check `pip show quack-kernels` in the failing env? I'd expect <= 0.4.0.

I'll open a PR raising the floor to `quack-kernels>=0.4.1`.

**Comment by BramVanroy** [comment]
You are right @SmartAI. uv defaulted to installing v0.3.3 of quack, which seems to be the culprit. I see that 0.4.1 of quack has this explicitly listed as "fixed", so using that as a floor version is a good idea. 👍

**Comment by SmartAI** [comment]
Thanks for confirming @BramVanroy! One small refinement after checking every wheel from 0.3.3 to 0.5.3: the bad `from cutlass.base_dsl import Arch` on the `import quack` path exists in 0.3.10, 0.3.11 and 0.4.0 (in `rmsnorm.py`/`softmax.py`/`cross_entropy.py`). 0.3.3 itself doesn't reference `Arch`, so if uv pinned exactly 0.3.3 the traceback likely came from a sibling env that resolved one of those three. Either way `>=0.4.1` covers the whole broken range — PR is up at #47571.
