### PR TITLE
[Bugfix] Fix mypy errors for StructuredOutputsParams by using stdlib dataclass

### PR DESCRIPTION
**Pull request by hyeongyun0916**
## Purpose

Fix 4 mypy errors that occur when running `pre-commit run --all-files` locally.

The `mypy-local` hook (`--follow-imports skip`) checks all files together, causing mypy to see the actual `StructuredOutputsParams` definition in `sampling_params.py`. Since it uses `pydantic.dataclasses.dataclass` instead of the stdlib `dataclasses.dataclass`, mypy does not recognize it as a valid dataclass — which breaks `dataclasses.replace()` calls and constructor keyword resolution.

`StructuredOutputsParams` had pydantic's `@dataclass` applied, but `dataclasses.replace()` only passes mypy's type check with stdlib dataclasses. Since no pydantic-specific features (validators, etc.) are used, switching to stdlib `dataclass` has no impact on runtime behavior.

```
$ pre-commit run --all-files
Run mypy locally for lowest supported Python version...Failed

vllm/entrypoints/openai/chat_completion/protocol.py:466: error: Value of type variable "_DataclassT" of "replace" cannot be "StructuredOutputsParams"  [type-var]
vllm/entrypoints/openai/responses/protocol.py:339: error: Unexpected keyword argument "json" for "StructuredOutputsParams"  [call-arg]
vllm/entrypoints/openai/completion/protocol.py:272: error: Value of type variable "_DataclassT" of "replace" cannot be "StructuredOutputsParams"  [type-var]
vllm/entrypoints/openai/responses/serving.py:505: error: Value of type variable "_DataclassT" of "replace" cannot be "StructuredOutputsParams"  [type-var]
Found 4 errors in 4 files (checked 644 source files)
```

This was introduced in https://github.com/vllm-project/vllm/pull/22772. During that refactor, the `dataclass` import was switched from stdlib to pydantic, but `StructuredOutputsParams` does not use any pydantic-specific features (validators, etc.). If this was an intentional change, please let me know.

**Fix:** Change `from pydantic.dataclasses import dataclass` back to `from dataclasses import dataclass`.

## Test Plan
```
pre-commit run mypy-local --all-files
```

## Test Result
```
Run mypy locally for lowest supported Python version...Passed
```

---
<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [x] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [x] The test plan, such as providing test command.
- [x] The test results, such as pasting the results comparison before and after, or e2e results
- [ ] (Optional) The necessary documentation update, such as updating `supported_models.md` and `examples` for a new model.
- [ ] (Optional) Release notes update. If your change is user facing, please update the release notes draft in the [Google Doc](https://docs.google.com/document/d/1YyVqrgX4gHTtrstbq8oWUImOyPCKSGnJ7xtTpmXzlRs/edit?tab=t.0).
</details>

### CODE REVIEW

**Review by njhill — APPROVED** [review]
Thanks @hyeongyun0916 this had also been annoying for me, though I could swear it started much more recently than https://github.com/vllm-project/vllm/pull/22772.

**Review by hickeyma — COMMENTED** [review]
Thanks @hyeongyun0916 for pushing the changes. I did not see your PR when I started adding a fix in #34739, sorry about that.

I took another approach. Like you I didn't see any obvious reasons for changing to Pydantic but I didn't want to alter it in case there maybe serialization somewhere and also not knowing the background for the change. Also, it meant overriding the `replace()` method which I though was overkill. 

As Pydantic dataclasses do not satisfy mypy's type system with `replace()` even though they are fully compatible at runtime, I decided to follow recommended practice which is to ignore that specific error `type-var`. My reasoning is that its a "known mypy/pydantic interop gap" and has no side effects.
