### PR TITLE
[CI][Models] Add VLM Support for Sequence Classification Conversion

### PR DESCRIPTION
**Pull request by AndreasKaratzas**
This PR enables Vision-Language Models (VLMs) like Gemma 3 to be converted to sequence classifiers using the `no_post_processing` and `from_2_way_softmax` methods. Additionally, it fixes two PyTorch compiler warnings that were causing noise in the logs.

### 1. `vllm/model_executor/models/adapters.py`

- Added `_get_language_model_for_seq_cls()` helper function to correctly retrieve the inner language model component from VLMs
- Updated `load_weights_no_post_processing()` and `load_weights_using_from_2_way_softmax()` to:
  - Detect VLM vs standard LLM architecture
  - Temporarily clear `method` and `classifier_from_token` configs on inner model to prevent recursive `seq_cls_model_loader` calls
  - Access the correct `score` layer location (`language_model.score` for VLMs vs `model.score` for LLMs)
  - Use correct weight names for validation (`language_model.score.weight` vs `score.weight`)

### 2. `vllm/model_executor/layers/layernorm.py`

- Split `GemmaRMSNorm.forward_static()` into two separate functions to fix torch.dynamo recompilation warning:
  - `_forward_static_no_residual()` - handles `residual=None` case
  - `_forward_static_with_residual()` - handles `residual=Tensor` case
- Each function is compiled separately, eliminating type-based recompilation

### 3. `vllm/v1/attention/backends/triton_attn.py`

- Fixed PyTorch nested tensor prototype warning by using `layout=torch.jagged`

## Problem

<details>

<summary><b>Original VLM Classification Error</b></summary>
```
AttributeError: 'Gemma3ForSequenceClassification' object has no attribute 'model'
```

The sequence classification conversion assumed all models have a `.model` attribute, but VLMs like Gemma 3 use `.language_model.model` structure.

</details>

<details>

<summary><b>Torch Dynamo Recompilation Warning</b></summary>
```
[rank0]:W0122 21:05:25.851000 torch/_dynamo/convert_frame.py:1358] [0/8] torch._dynamo hit config.recompile_limit (8)
[rank0]:W0122 21:05:25.851000    function: 'forward_static' (/app/vllm/vllm/model_executor/layers/layernorm.py:280)
[rank0]:W0122 21:05:25.851000    last reason: 0/7: expected type of 'residual' to be a tensor type, but found <class 'NoneType'>
```

The `forward_static` function was being recompiled repeatedly because it handled both `residual=None` and `residual=Tensor` cases, causing torch.dynamo to specialize and recompile on each type change.

</details>

<details>

<summary><b>Nested Tensor Prototype Warning</b></summary>
```
UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. 
We recommend specifying layout=torch.jagged when constructing a nested tensor...
```

</details>

<details>

<summary><b>VLM Architecture Root Cause</b></summary>

VLMs have a nested architecture:
```
Gemma3ForConditionalGeneration (outer VLM):
* vision_tower: SiglipVisionModel
* multi_modal_projector: Gemma3MultiModalProjector
* language_model: Gemma3ForCausalLM (inner LLM):
    - model: Gemma3Model
    - lm_head: ParallelLMHead
```

When wrapped as `ModelForSequenceClassification`, BOTH the outer VLM and inner LLM get the wrapper applied. This caused:

1. **Attribute access failure**: Code tried `model.model.embed_tokens` but VLMs need `model.language_model.model.embed_tokens`
2. **Recursive weight loading**: Inner `language_model` also triggered `seq_cls_model_loader`, deleting `lm_head` before outer model could use it
3. **Missing score layer**: For VLMs, `_init_pooler` (which creates `score`) is not called on outer model since it reuses inner model's pooler
4. **Wrong weight names**: Validation expected `score.weight` but VLMs have `language_model.score.weight`

</details>

## Testing

<details>
<summary><b>Classification Test Results</b></summary>

Tested with `google/gemma-3-4b-it` as a 5-class furniture classifier:
```python
def update_config(config):
    config.text_config.update({
        "architectures": ["Gemma3ForSequenceClassification"],
        "classifier_from_token": ["A", "B", "C", "D", "E"],
        "method": "no_post_processing",
        "id2label": {"0": "Chair", "1": "Couch", "2": "Table", "3": "Bed", "4": "Cupboard"},
    })
    return config
```

**Results on red chair image:**
```
Probabilities: [1.0, 3.27e-09, 9.24e-09, 2.61e-08, 1.96e-08]
Prediction: Chair (100% confidence)
```

</details>

<details>

<summary><b>Generation Test Results (Regression Check)</b></summary>

Verified VLM generation mode still works correctly:
```
Turn 1 - User: What color is this furniture?
Assistant: Frame: Primarily a rich, dark reddish-brown, likely mahogany.
          Seat: A vibrant red leather.
          Details: Touches of black on decorative elements.

Turn 2 - User: What material do you think it's made of?
Assistant: Frame: Almost certainly mahogany wood...
          Seat: Made of leather...

Turn 3 - User: Would this be suitable for an office or a living room?
Assistant: Living Room – Highly Suitable...
          Office – Less Ideal, but Possible...
```

Multi-turn context maintained correctly

</details>

## Backwards Compatibility

| Model Type | Behavior |
|------------|----------|
| Standard LLMs (Gemma, Qwen, etc.) | `_get_language_model_for_seq_cls()` returns `model` itself → unchanged behavior |
| VLMs (Gemma 3, etc.) | Returns inner `language_model` → now works |
| GemmaRMSNorm | Same numerical results, just split compilation paths |

### CODE REVIEW

File: vllm/model_executor/models/adapters.py [hunk 1]
```diff
@@ -411,12 +444,40 @@ def load_weights_using_from_2_way_softmax(
...
+        )
+        loaded_weights = pooling_model_cls.load_weights(model, weights)
+    finally:
+        if inner_text_config is not None:
+            if original_method is not None:
+                inner_text_config.method = original_method
+            if original_tokens is not None:
+                inner_text_config.classifier_from_token = original_tokens
+        if inner_hf_config is not None and original_hf_tokens is not None:
+            inner_hf_config.classifier_from_token = original_hf_tokens
```
[the remark this answers is not in the document]
Comment (AndreasKaratzas) [reply vllm/model_executor/models/adapters.py]: Good point. I've pushed a commit refactoring adapters to handle VLM config into a central context manager.

**Review by noooop — APPROVED** [review]
