### PR TITLE
[Bugfix][Spec Decode][Quantization] Handle quantized qkv_proj in DFlash fused-KV buffers

### LINKED ISSUE #51581: [Bug][Spec Decode]: DFlash fused-KV projection calls F.linear on a sliced qkv_proj weight — breaks (and can silently corrupt) any weight-quantized drafter
### Your current environment

- vLLM **0.26.0** (`vllm/vllm-openai:latest-aarch64`), also verified against current `main` by reading the source (see below)
- NVIDIA **GB10 / DGX Spark**, sm_121a, CUDA 13.2, aarch64, 128 GB unified memory
- Target: Qwen3.6-35B-A3B (compressed-tensors NVFP4)
- Drafter: `z-lab/Qwen3.6-35B-A3B-DFlash`, quantized offline to FP8 (E4M3, per-tensor `weight_scale`, `activation_scheme: dynamic`)

### 🐛 Describe the bug

DFlash speculative decoding cannot be used with a **weight-quantized drafter**. Serving a DFlash drafter that carries any weight-quantization config fails at engine init:

```
File "vllm/model_executor/models/qwen3_dflash.py", line 514, in <...>
    all_kv_flat = F.linear(
                  ^^^^^^^^^
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::BFloat16 != c10::Float8_e4m3fn
```

**Root cause.** `Qwen3DFlash` builds a fused KV GEMM by *slicing the merged `qkv_proj` weight tensor* and applying it with a raw `torch.nn.functional.linear`, which bypasses the module's quantization method entirely. On current `main`:

```python
# vllm/model_executor/models/qwen3_dflash.py:448-449
kv_weights = [a.qkv_proj.weight[a.q_size :] for a in layers_attn]
self._fused_kv_weight = torch.cat(kv_weights, dim=0)

# vllm/model_executor/models/qwen3_dflash.py:521-522
all_kv_flat = F.linear(
    normed_context_states, self._fused_kv_weight, self._fused_kv_bias
)
```

When `qkv_proj` is a quantized `Linear`, `.weight` is the packed/quantized tensor, so `F.linear` is being handed something it cannot consume.

**This is broader than the FP8 case that surfaced it, and it is a correctness hazard, not only a crash.** `.weight` is the packed tensor for *any* weight-only scheme (fp8, compressed-tensors, AWQ, GPTQ, …). Where the dtypes happen to line up rather than raise, this path silently omits `weight_scale` and produces **numerically wrong drafts** — which speculative decoding will not surface as an error, only as degraded acceptance.

Note this is **not** a duplicate of #42588: that one was ROCm-specific, in `combine_hidden_states` (the `fc` layer), and was caused by *activations* being promoted to fp32; it was fixed by #42646. This one is on CUDA, in the fused-KV path, and is caused by the *weight* being quantized.

### Suggested fix

Either de-quantize when building the buffer — apply the module's `weight_scale` and cast to the activation dtype in `_build_fused_kv_buffers` — or, preferably, route the fused KV projection through the module's quantization method instead of calling `F.linear` on a raw weight.

### Secondary observation (possibly a separate bug)

Trying to exempt the module via the drafter checkpoint's `quantization_config.ignored_layers` did **not** take effect. I listed both `layers.{N}.self_attn.qkv_proj` and `model.layers.{N}.self_attn.qkv_proj` and the engine still quantized it and still crashed at the same line. Also worth noting for anyone hitting this: with `quant_method: fp8` and no `ignored_layers`, vLLM quantizes *every* `Linear` **online at load**, so simply leaving q/k/v as BF16 tensors in the checkpoint does not avoid the crash.

### Reproduce

1. Quantize `z-lab/Qwen3.6-35B-A3B-DFlash` to FP8 (E4M3 weights + per-tensor `weight_scale`) and write a `quantization_config` of `{"quant_method": "fp8", "activation_scheme": "dynamic"}` into its `config.json`.
2. Serve any Qwen3.6-35B-A3B target with that drafter:

```
--speculative-config '{"method":"dflash","model":"<fp8-drafter-path>","num_speculative_tokens":6}'
```

3. Engine init fails with the traceback above.

### Why it matters

On a bandwidth-bound machine the drafter is read every speculative cycle. For this pairing the BF16 drafter is 0.772 GB of a ~4.35 GB cycle, so quantizing it is a straightforward win that is currently unavailable.

### PR DESCRIPTION
**Pull request by SayHelloToWorld**
## Purpose

Fixes #51581 (competing drafts #51620 / #53122 do not cover quantized drafters).

DFlash-family speculative decoding crashes at engine init when the drafter is quantized.
The DFlash fused-KV path sliced the raw `.weight` of the KV projections and fed it to a
single fused GEMM, bypassing the quant method. This PR reworks the fused context-KV
precompute into a tiered strategy:

| tier | when | behavior |
|---|---|---|
| `FUSED` | unquantized drafters | fuse qkv weights as before (fastest, unchanged) |
| `SCALED_MM` | per-tensor FP8 with cutlass fp8 | keep weights quantized, fuse per-output-row scales, run `cutlass_scaled_mm` |
| `FUSED_DEQUANT` | per-tensor FP8 without cutlass fp8 | dequant once into a fused bf16 weight at build time |
| `PER_LAYER` | anything else (marlin / block-quant / mixed) | project per layer and concat (always correct) |

The fused buffers are now built lazily at the first precompute (after
`process_weights_after_loading`), so quantized layers are handled after their scales
exist.

## Changes

- `vllm/model_executor/models/qwen3_dflash.py` (main rework, +225/-17)
- `vllm/model_executor/models/laguna_dflash.py`
- `vllm/model_executor/models/gemma4_dspark.py`
- `vllm/model_executor/models/qwen3_dspark.py`
- `tests/v1/spec_decode/test_dflash_fusedkv_quantized.py` (new, +341)

## Test Plan

```bash
pytest tests/v1/spec_decode/test_dflash_fusedkv_quantized.py -v
# plus an end-to-end serve with a quantized DFlash drafter:
vllm serve <model> --speculative-config '{"model": "<quantized-drafter>", ...}'
```

## Notes

- Rebased onto latest `main` (previously `needs-rebase`).
- Unquantized drafters keep the original fused path — no perf change there.
- AI-assisted; reviewed by me. DCO `Signed-off-by:` present.

### CODE REVIEW

**Comment by SayHelloToWorld** [comment]
Could a maintainer add the verified label so CI can run? Thanks! 
Give me some advice.

**Review by SayHelloToWorld — COMMENTED** [review]
test

**Comment by SayHelloToWorld** [comment]
@jeejeelee Please take a look.

**Comment by greatyingzi** [comment]
## Independently validated the `PER_LAYER` tier on 2× RTX 3090 — works, no acceptance loss

We hit the same bug (W4A16 + Marlin variant, posted details in #51581) and, before finding this PR, wrote a minimal local fix that turns out to match your `PER_LAYER` tier exactly: detect quantized `qkv_proj` at buffer-build time, fall back to per-layer `qkv_proj` forward (through the module's quant method), keep each layer's K/V slice `[..., q_size:]`, concatenate layer-major to match the fused-GEMM layout bit-for-bit. Non-quantized drafters stay on the fused path.

**End-to-end results on real hardware (2× RTX 3090 24GB PCIe, TP=2, Huihui-Qwen3.8-27B-Abliterated-INT4 target, Qwen3.8-27B-DFlash2 drafter, n=7, identical eval protocol across arms):**

| drafter | size | accept rate | notes |
|---|---|---|---|
| bf16 | 3.58 GiB | 39.5% | baseline |
| W4A16 int4 + per-layer fix | 1.19 GiB | 38.4–40.4% | engine init 3/3 crashes → clean start; within noise of bf16 |
| partial int4 (qkv bf16) | 1.41 GiB | 40.7% | fused path unaffected |

So the per-layer fallback is not just "always correct" — it's fast enough that a fully-quantized drafter recovers the entire bandwidth win with no measurable acceptance penalty. That should help answer the question of whether `PER_LAYER` is acceptable as the default for marlin/block-quant schemes rather than needing `SCALED_MM`/`FUSED_DEQUANT` for W4A16 too.

One implementation note from our version: `QKVParallelLinear.forward()` can return a `(output, bias)` tuple depending on `return_bias`, so the fallback needs to unwrap it before slicing. Worth checking your tier handles that.

This PR is the right shape — hope it gets a review soon. Happy to run any additional benchmarks you want on this hardware pairing.

**Comment by jsboige** [comment]
**Validation on pack-quantized targets (2× RTX 4090, TP=2, V2 runner, WSL2)** — this PR takes DFlash2 from a hard crash to fully working for us.

**Setup:** vLLM v0.30.0 + this PR (@ b1b3aefa, file-for-file overlay; base 73fb19151f4f verified an ancestor of the release and the touched files unchanged since). Target `philbert440/Qwen3.8-27B-W4A16-AWQ` (compressed-tensors **pack-quantized** INT4), drafter `syvai/Qwen3.8-27B-DFlash2-W4A16`, `num_speculative_tokens=8`, fp8 KV, TP=2.

**On stock v0.30.0:** deterministic crash at weight load in both TP workers, reproduced with two independent pack-quantized checkpoints (also cyankiwi/Qwen3.8-27B-AWQ-INT4):
```
AttributeError: 'QKVParallelLinear' object has no attribute 'weight'
  qwen3_dflash.py:472 _build_context_kv_buffers
```
(the exact failure in #51581 — the fused-KV path slices raw `.weight`, which pack-quantized layers don't expose)

**With this PR:** boots to healthy in ~5.5 min, RestartCount 0. Functional gates all pass (vision, tool-calling, thinking, chunked-prefill 31K/102K/253K each followed by a survival request). Most importantly for a correctness-sensitive fix: our degenerate-output canary (fixed prompts, 4-gram repetition ratio, threshold 0.5) is **clean at 0.00** — the tiered fused-KV path produces genuinely correct drafts on a quantized target, not just a booting engine.

**Spec-dec stats:** acceptance 0.48 (410/856) single-stream, degrading to 0.21 cumulative under 16-way concurrency — consistent with draft accuracy under batched verification rather than any correctness issue in the fused path.

Thanks for the fix — happy to run any additional checks from this hardware profile if useful for the review.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
