### ISSUE TITLE
[Bug]: TORCHINDUCTOR_FORCE_DISABLE_CACHES=1 fails with vLLM-compile in torch <= 2.7.1

### ISSUE THREAD

**Issue by zou3519** [vllm-project/vllm#21858]
### Your current environment

PyTorch 2.7.1, 

### 🐛 Describe the bug

`TORCHINDUCTOR_FORCE_DISABLE_CACHES=1 vllm serve` fails with the following. It doesn't matter what model gets used, this fails as long as you're using vLLM-compile.

```
RuntimeError: vLLM failed to compile the model. The most likely reason for this is that a previous compilation failed, leading to a corr
upted compilation artifact. We recommend trying to remove ~/.cache/vllm/torch_compile_cache and try again to see the real issue.
```

I believe this problem is fixed in PyTorch 2.8, so we could just wait until then. But I'm not completely sure we can fix this in PyTorch 2.7. If not, the only thing we can do is make the error message better.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by zou3519** [comment]
NB: using VLLM_DISABLE_COMPILE_CACHE=1 will work around the problem

**Comment by zou3519** [comment]
This might be a wontfix

**Comment by zou3519** [comment]
actionable to improve the error message, also verify if this is a problem in PyTorch 2.8
