### PR TITLE
[CI] Skip the pooling models that do not support transformers v4.55

### LINKED ISSUE #22398: [CI Failure]: test_reward.py::test_prm_models - AttributeError: 'DynamicCache' object has no attribute 'get_usable_length'. Did you mean: 'get_seq_length'?
### Name of failing test

models/language/pooling/test_reward.py::test_prm_models[True-half-Qwen/Qwen2.5-Math-PRM-7B]

### Basic information

- [ ] Flaky test
- [ ] Can reproduce locally
- [ ] Caused by external libraries (e.g. bug in `transformers`)

### 🧪 Describe the failing test

[2025-08-06T21:39:31Z] FAILED models/language/pooling/test_reward.py::test_prm_models[True-half-Qwen/Qwen2.5-Math-PRM-7B] - AttributeError: 'DynamicCache' object has no attribute 'get_usable_length'. Did you mean: 'get_seq_length'?
[2025-08-06T21:39:31Z] FAILED models/language/pooling/test_reward.py::test_prm_models[False-half-Qwen/Qwen2.5-Math-PRM-7B] - AttributeError: 'DynamicCache' object has no attribute 'get_usable_length'. Did you mean: 'get_seq_length'?

### 📝 History of failing test

https://buildkite.com/organizations/vllm/analytics/suites/ci-1/tests/600d233a-e9e7-8f9f-b750-17eede6e1172?branch=main&period=1day

broken by #22327 

### CC List.

_No response_

### PR DESCRIPTION
**Pull request by noooop**
# Essential Elements of an Effective PR Description Checklist

- [ ] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [ ] The test plan, such as providing test command.
- [ ] The test results, such as pasting the results comparison before and after, or e2e results
- [ ] (Optional) The necessary documentation update, such as updating `supported_models.md` and `examples` for a new model.

## Purpose

Qwen/Qwen2.5-Math-PRM-7B hf Implementation does not support v4.54.1

refer to https://github.com/vllm-project/vllm/pull/21931#issuecomment-3154000018

Fix #22398

### CODE REVIEW

File: .buildkite/test-pipeline.yaml [hunk 1]
```diff
@@ -569,6 +569,8 @@ steps:
   - vllm/
   - tests/models/language/pooling
   commands:
+    # Some pooling models are not support transformers v4.55
+    - pip install transformers==4.53.2
```
Comment (DarkLight1337) [inline .buildkite/test-pipeline.yaml]: Let's just skip the tests for that model. We should avoid having multiple transformers versions.

Comment (noooop) [reply .buildkite/test-pipeline.yaml]: how about now

File: tests/models/language/pooling/test_gte.py [hunk 2]
```diff
@@ -60,6 +61,10 @@
 @pytest.mark.parametrize("model_info", MODELS)
 def test_embed_models_mteb(hf_runner, vllm_runner,
                            model_info: EmbedModelInfo) -> None:
+    if model_info.name == "Alibaba-NLP/gte-Qwen2-1.5B-instruct":
```
Comment (DarkLight1337) [inline tests/models/language/pooling/test_gte.py:64]: Why not simply update these models in `HF_EXAMPLE_MODELS`?

Comment (noooop) [reply tests/models/language/pooling/test_gte.py:64]: Let's not touch this code.

```
    "Qwen2ForCausalLM": _HfExamplesInfo("Qwen/Qwen2-0.5B-Instruct",
                                        extras={"2.5": "Qwen/Qwen2.5-0.5B-Instruct"}), # noqa: E501
```

Comment (DarkLight1337) [reply tests/models/language/pooling/test_gte.py:64]: Got it

**Review by DarkLight1337 — APPROVED** [review]
Thanks for fixing
