### ISSUE TITLE
Get a bug when I upgrade to 0.1.3

### ISSUE THREAD

**Issue by Huffman-cotdom** [vllm-project/vllm#664]
Traceback (most recent call last):
  File "/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/quanyong/conversion_summary/vllm_test/run_vllm_response.py", line 8, in <module>
    from vllm import LLM, SamplingParams
  File "/root/miniforge3/envs/vllm/lib/python3.10/site-packages/vllm/__init__.py", line 4, in <module>
    from vllm.engine.async_llm_engine import AsyncLLMEngine
  File "/root/miniforge3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 7, in <module>
    from vllm.engine.llm_engine import LLMEngine
  File "/root/miniforge3/envs/vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 10, in <module>
    from vllm.engine.ray_utils import initialize_cluster, ray, RayWorker
  File "/root/miniforge3/envs/vllm/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 8, in <module>
    from ray.air.util.torch_dist import TorchDistributedWorker
  File "/root/miniforge3/envs/vllm/lib/python3.10/site-packages/ray/air/__init__.py", line 1, in <module>
    from ray.air.checkpoint import Checkpoint
  File "/root/miniforge3/envs/vllm/lib/python3.10/site-packages/ray/air/checkpoint.py", line 22, in <module>
    from ray.air._internal.remote_storage import (
  File "/root/miniforge3/envs/vllm/lib/python3.10/site-packages/ray/air/_internal/remote_storage.py", line 142, in <module>
    _cached_fs: Dict[tuple, Tuple[float, pyarrow.fs.FileSystem]] = {}
AttributeError: 'NoneType' object has no attribute 'fs'

**Comment by zhangxiaofan-zy** [comment]
me too, whenupgrade to 0.1.3,that error happened

**Comment by raahulraa** [comment]
Same here.

**Comment by 18600709862** [comment]
pip install ray==2.5.1

**Comment by nutmilk10** [comment]
> pip install ray==2.5.1

I am now getting this issue
```
vllm = LLM(
    model="mosaicml/mpt-7b-instruct", 
    trust_remote_code=True,
    tensor_parallel_size=4,
    
ImportError: Ray is not installed. Please install Ray to use distributed serving.

```

**Comment by madaan** [comment]
Looks like `ray==2.5.1` depends on pandas, which is is not included in the dependencies. 

It worked for me after running `pip install pandas`.

**Comment by zhuohan123** [comment]
Please update to the latest ray and check again!

**Comment by Lzhang-hub** [comment]
> ImportError: Ray is not installed. Please install Ray to use distributed serving.

I install ray 2.6.2 and vllm 0.1.3, get the error:

ImportError: Ray is not installed. Please install Ray to use distributed serving.

**Comment by madaan** [comment]
@Lzhang-hub it works with `ray==2.5.1` (you will also need to install `pandas`).

**Comment by Lzhang-hub** [comment]
> pip install ray==2.5.1

Thanks! I will try it
