### ISSUE TITLE
Benchmarking Error with enforce_eager: TypeError: __init__() got an unexpected keyword argument 'enforce_eager'

### ISSUE THREAD

**Issue by Shreyaskulkarni98** [vllm-project/vllm#2213]
I am trying to benchmark the throughput of my model using the ShareGPT dataset.

```shell
python benchmarks/benchmark_throughput.py --model $MODEL --dataset ShareGPT_V3_unfiltered_cleaned_split.json
```

However with the latest version I get the following error:

```shell
Namespace(backend='vllm', dataset='ShareGPT_V3_unfiltered_cleaned_split.json', dtype='auto', enforce_eager=False, hf_max_batch_size=None, input_len=None, max_model_len=None, model='/oda/llm/c2kreader/converted_1260_fp16_hf', n=1, num_prompts=1000, output_len=None, quantization=None, seed=0, tensor_parallel_size=1, tokenizer='/oda/llm/c2kreader/converted_1260_fp16_hf', trust_remote_code=False, use_beam_search=False)
Traceback (most recent call last):
  File "benchmark_throughput.py", line 318, in <module>
    main(args)
  File "benchmark_throughput.py", line 205, in main
    elapsed_time = run_vllm(requests, args.model, args.tokenizer,
  File "benchmark_throughput.py", line 76, in run_vllm
    llm = LLM(
  File "/usr/.venv/lib64/python3.8/site-packages/vllm/entrypoints/llm.py", line 78, in __init__
    engine_args = EngineArgs(
TypeError: __init__() got an unexpected keyword argument 'enforce_eager'
``` 

I didn't get this error with previous versions

**Comment by WoosukKwon** [comment]
@Shreyaskulkarni98 Could you re-install vLLM v0.2.6?

**Comment by Shreyaskulkarni98** [comment]
Same error even with latest v0.2.6. However, it seems to work with v0.2.5( 31c1f32)

**Comment by WoosukKwon** [comment]
@Shreyaskulkarni98 Did you install vLLM? Could you share the output of `python -c "import vllm; print(vllm.__version__)"`?

**Comment by Shreyaskulkarni98** [comment]
@WoosukKwon Yes i did, here is the output 

```shell
$python -c "import vllm; print(vllm.__version__)"
0.2.1.post1
```

**Comment by WoosukKwon** [comment]
@Shreyaskulkarni98 Thanks. The `enforce_eager` argument was recently added. Please upgrade vLLM to v0.2.6!
