### PR TITLE
[Bug] Fix ci issue `assert output_size is not None` AssertionError

### PR DESCRIPTION
**Pull request by yewentao256**
## Purpose

Fixes https://github.com/vllm-project/vllm/pull/42651#issuecomment-4503490306

`pytest tests/v1/spec_decode/test_speculators_correctness.py::test_speculators_model[dflash]`

Originally

```bash
(EngineCore pid=2423736)   File "/home/yewentao256/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1790, in _call_impl
(EngineCore pid=2423736)     return forward_call(*args, **kwargs)
(EngineCore pid=2423736)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=2423736)   File "/home/yewentao256/vllm-source/vllm/model_executor/layers/linear.py", line 585, in forward
(EngineCore pid=2423736)     output_parallel = self.quant_method.apply(self, input_, bias)
(EngineCore pid=2423736)                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=2423736)   File "/home/yewentao256/vllm-source/vllm/model_executor/layers/quantization/fp8.py", line 483, in apply
(EngineCore pid=2423736)     return self.fp8_linear.apply_weights(layer, x, bias)
(EngineCore pid=2423736)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=2423736)   File "/home/yewentao256/vllm-source/vllm/model_executor/kernels/linear/scaled_mm/ScaledMMLinearKernel.py", line 147, in apply_weights
(EngineCore pid=2423736)     return self.apply_scaled_mm(
(EngineCore pid=2423736)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=2423736)   File "/home/yewentao256/vllm-source/vllm/model_executor/kernels/linear/scaled_mm/cutlass.py", line 227, in apply_scaled_mm
(EngineCore pid=2423736)     assert output_size is not None
(EngineCore pid=2423736)            ^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=2423736) AssertionError
```

Now 

```bash
=============================== 1 passed, 17 warnings in 35.25s ===============================
```

### CODE REVIEW

**Review by Isotr0py — APPROVED** [review]

**Comment by njhill** [comment]
The test on this PR is still failing with a similar error: https://buildkite.com/vllm/ci/builds/67272/list?sid=019e47f4-bfd2-4b68-82af-c17416c4a351&tab=output#019e47f4-c300-4a31-9a71-b2a2b85a2097/L3766

**Comment by haosdent** [comment]
Here are the related CI failures in the nightly build

- [Kernels (B200)](https://buildkite.com/vllm/ci/builds/67233/canvas?sid=019e4743-e7c8-4d26-b027-551c60dc3e0e&tab=output)
- [Fusion and Compile Unit Tests (2xB200)](https://buildkite.com/vllm/ci/builds/67233/canvas?sid=019e4743-e771-4b50-a2c8-9bdfc252a7a2&tab=output)
- [V1 Spec Decode](https://buildkite.com/vllm/ci/builds/67277/canvas?sid=019e480d-8dd9-4711-819b-573cec65a910&tab=output)
- [Quantization](https://buildkite.com/vllm/ci/builds/67233/canvas?sid=019e4743-e830-4990-857e-38b29f3e84bc&tab=output)
- [Distributed Torchrun + Examples (4 GPUs)](https://buildkite.com/vllm/ci/builds/67254/canvas?sid=019e4793-40c4-4493-9fa2-cc0a6d99e463&tab=output)

File: vllm/model_executor/layers/quantization/fp8.py [hunk 1]
```diff
@@ -557,6 +557,7 @@ def process_weights_after_loading(self, layer: torch.nn.Module) -> None:
         else:
             weight = qweight.t()
             replace_parameter(layer, "weight", weight.data)
+            self.fp8_linear.process_weights_after_loading(layer)
```
Comment (haosdent) [inline vllm/model_executor/layers/quantization/fp8.py:560]: Should we also patch https://github.com/vllm-project/vllm/blob/905b97adfaf7b08f3cc95b328579e5336ed6d3b6/vllm/model_executor/layers/quantization/online/fp8.py#L145-L157

**Review by haosdent — CHANGES_REQUESTED** [review]

File: vllm/model_executor/layers/quantization/fp8.py (hunk 1 above)
Comment (haosdent) [reply vllm/model_executor/layers/quantization/fp8.py:560]: This change seems could not address
```
AttributeError: 'CutlassFP8ScaledMMLinearKernel' object has no attribute 'logical_output_size'
```

**Comment by njhill** [comment]
I feel we should revert https://github.com/vllm-project/vllm/pull/42651 and fix these things before re-applying.

File: vllm/model_executor/layers/quantization/fp8.py (hunk 1 above)
Comment (Isotr0py) [reply vllm/model_executor/layers/quantization/fp8.py:560]: It's fixed by https://github.com/vllm-project/vllm/pull/43268 instead

**Comment by Isotr0py** [comment]
Tried to push more fix since wentao is likely asleep. Let's revert https://github.com/vllm-project/vllm/pull/42651 if tests can't still pass.

**Comment by haosdent** [comment]
I also have a PR at https://github.com/vllm-project/vllm/pull/43291 , which I think could address the root cause. @Isotr0py may take a look as well

File: vllm/model_executor/layers/quantization/fp8.py (hunk 1 above)
Comment (haosdent) [reply vllm/model_executor/layers/quantization/fp8.py:560]: Seems even #43261 + #43268 , could not handle cases like
* test_fp8_reloading[False-None-True-Fp8LinearMethod]

Comment (Isotr0py) [reply vllm/model_executor/layers/quantization/fp8.py:560]: Reloading test should be fixed by the `padded_weight_loader` introduced in https://github.com/vllm-project/vllm/pull/43261/commits/d13cb7903084eae4df87c8d7a2dbb90d365cd7be

**Comment by njhill** [comment]
Thanks @Isotr0py @haosdent @yewentao256
