### ISSUE TITLE
[CI Failure]: Model Executor Test - model_executor/model_loader/test_reload.py::test_padded_moe_reload_releases_each_layer

### ISSUE THREAD

**Issue by kaijunli-infr** [vllm-project/vllm#57483]
### Name of failing test

`model_executor/model_loader/test_reload.py::test_padded_moe_reload_releases_each_layer` (all 16 parametrizations)

### Basic information

- [ ] Flaky test
- [x] Can reproduce locally
- [ ] Caused by external libraries (e.g. bug in `transformers`)

### 🧪 Describe the failing test

The Model Executor Test step fails deterministically on current `main` (observed identically on both `amd-mi300` and `nvidia-h200-mig-35gb` in https://buildkite.com/vllm/ci/builds/89654, a PR branch rebased onto `main` tip `78fdf4ef`).

The test's stub MoE config is a `SimpleNamespace` that does not define `tp_shard_with_padding`, which the padded weight-loading path now reads:

```
tests/model_executor/model_loader/test_reload.py:553: in test_padded_moe_reload_releases_each_layer
    layer.weight_loader(expected[name], weight, name, shard, expert)
vllm/model_executor/layers/fused_moe/routed_experts.py:877: in weight_loader
    self._load_model_weight_or_group_weight_scale(
vllm/model_executor/layers/fused_moe/routed_experts.py:349: in _load_model_weight_or_group_weight_scale
    padded_tp = self.moe_config.tp_shard_with_padding
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: 'types.SimpleNamespace' object has no attribute 'tp_shard_with_padding'
```

Reproduce locally (CPU-only, ~3 s):

```bash
pytest "tests/model_executor/model_loader/test_reload.py::test_padded_moe_reload_releases_each_layer" -q
```

### 📝 History of failing test

Broken since `78fdf4ef` (#54699, merged 2026-09-17 14:00 UTC) via a semantic conflict with #55867 (merged 2026-09-17 08:56 UTC):

- #55867 (`08633cb5`) added the `self.moe_config.tp_shard_with_padding` read in `_load_model_weight_or_group_weight_scale`.
- #54699 (`78fdf4ef`) added `test_padded_moe_reload_releases_each_layer`, whose `SimpleNamespace` config stub (built before #55867 landed) does not set that attribute, and its CI ran on a pre-#55867 base.

Neither PR fails on its own base; the combination on `main` does. The fix is presumably a one-liner: add `tp_shard_with_padding=False` (or the appropriate value per `padded` param) to the stub config in the test.

cc @yuchenwang3 @gcanlin

**Comment by kaijunli-infr** [comment]
Already fixed on main by #57402 (merged 2026-09-17 17:02 UTC), which adds tp_shard_with_padding to the test's SimpleNamespace config — I missed it when filing since I only searched issues, not merged PRs. Verified all 16 params pass at current main tip (d12c2768). Closing as completed.
