### PR TITLE
[CI Failure] Skip failing nvfp4 silu test

### PR DESCRIPTION
**Pull request by mgoin**
## Purpose

It seems the Blackwell Test is failing on main since https://github.com/vllm-project/vllm/pull/23929, so skipping if the symbol isn't found for now

Log: https://buildkite.com/vllm/ci/builds/28870/steps/canvas?sid=0198f6b1-3529-46d8-9896-06aac42648d6

```
FAILED tests/kernels/quantization/test_silu_nvfp4_quant_fusion.py::test_quantize_to_fp4[cuda:0-42-shape0-dtype0] - AttributeError: '_OpNamespace' '_C' object has no attribute 'silu_and_mul_nvfp4_quant'
```

## Test Result

---
<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [ ] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [ ] The test plan, such as providing test command.
- [ ] The test results, such as pasting the results comparison before and after, or e2e results
- [ ] (Optional) The necessary documentation update, such as updating `supported_models.md` and `examples` for a new model.
- [ ] (Optional) Release notes update. If your change is user facing, please update the release notes draft in the [Google Doc](https://docs.google.com/document/d/1YyVqrgX4gHTtrstbq8oWUImOyPCKSGnJ7xtTpmXzlRs/edit?tab=t.0).
</details>

### CODE REVIEW

**Review by njhill — APPROVED** [review]

**Comment by DarkLight1337** [comment]
Maybe fixed by #23973, let's see https://buildkite.com/vllm/ci/builds/28921/steps/canvas?jid=0198f9d4-fc6b-4e72-89a5-08aa3fac4cd9

**Comment by njhill** [comment]
It appears this wasn't fixed by #23973 and it's still impacting CI. So we should probably merge this?

**Review by yewentao256 — APPROVED** [review]
We should land this first, still PR failing like https://github.com/vllm-project/vllm/pull/23289
