### PR TITLE
[Frontend] Rerank API (Jina- and Cohere-compatible API) 

### LINKED ISSUE #4316: [Feature Request]: Support LLMs, embeddings & reranking models served through vLLM
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

_No response_

### Describe the feature you'd like

It would be great if RAGflow could support LLMs served through vLLM's OpenAI-compatible APi server, and if RAGflow could also support embedding models and re-ranking models served through vLLM. 

### Describe implementation you've considered

vLLM is the most popular open-source framework for high-performance, GPU-accelerated serving of LLMs and other AI models, and it would be great to have support for it. 

vLLM has a well-documented API for LLM serving and embeddings (which is compatible with OpenAI's format), and a custom API for serving reranking models:
- [Chat Completions API documentation](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#chat-api)
- [Embeddings API documentation](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#embeddings-api)
- [Rerank API documentation, named "score"](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#score-api)

### Documentation, adoption, use case

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by K-Mistele**
This PR introduces an explicit re-rank API at `/rerank` and `/v1/rerank`. The same fundamental relevant-scoring functionality with cross-encoder models has been previously implemented in `/score`, but this API is unique and does not follow any standardized API, and therefore requires custom code to consume. 

The endpoints introduced in this PR use the same cross-encoder scoring functionality under the hood, but they reproduce the API behavior of [Jina AI's re-ranker](https://jina.ai/reranker/) and therefore also of [Cohere's re-ranker](https://docs.cohere.com/v2/reference/rerank) (which is a subset of Jina's API) in terms of API request and response schemas and behavior. 

_Why Jina and Cohere?_ OpenAI does not have a re-ranking API. Jina and Cohere's API standards are very common for re-rank APIs, simliar to how OpenAI's chat completions API has become near-universally adopted. The Jina/Cohere re-rank API format has notably been followed by other labs and projects, including:
- Qwen 
- Voyage
- Baidu 
- Siliconflow
- localai.io 
- ragflow

The code in `serving_rerank.py` is 90% the same as `serving_score.py`, but implements the rerank API as described above. This enhances vLLM's compatibility with Open-source tools & frameworks that use existing well-defined APIs, allowing vLLM to be used for self-hosted RAG setup with off-the-shelf tooling

FIX infiniflow/ragflow#4316

### CODE REVIEW

File: examples/online_serving/jinjaai_rerank_client.py [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+Jina and Cohere
+run: vllm serve --model BAAI/bge-reranker-base
+"""
+import json
+
+import requests
+
+url = "http://127.0.0.1:8000/rerank"
+
+headers = {"accept": "application/json", "Content-Type": "application/json"}
```
Comment (DarkLight1337) [inline examples/online_serving/jinjaai_rerank_client.py:12]: To better demonstrate the convenience of this API over `/score`, I suggest using the Python client of Jina and Cohere directly,

File: vllm/entrypoints/openai/api_server.py [hunk 2]
```diff
@@ -502,6 +508,33 @@ async def create_score_v1(request: ScoreRequest, raw_request: Request):
...
+
+
+@router.post("/v1/rerank")
+@with_cancellation
+async def do_rerank_v1(request: RerankRequest, raw_request: Request):
+    logger.warning(
+        "To indicate that the rerank API is not part of the standard OpenAI"
+        " API, we have located it at `/rerank`. Please update your client"
+        "accordingly. (Note: Conforms to JinaAI rerank API)")
+    return await do_rerank(request, raw_request)
```
Comment (DarkLight1337) [inline vllm/entrypoints/openai/api_server.py:535]: It seems that the latest version of both Jina and Cohere clients use `/v2/rerank`. We should handle that case as well.

File: examples/online_serving/jinjaai_rerank_client.py (hunk 1 above)
Comment (K-Mistele) [reply examples/online_serving/jinjaai_rerank_client.py:12]: happy to, I just didn't want to add a dependency but I guess it can be manually installed

File: vllm/entrypoints/openai/api_server.py (hunk 2 above)
Comment (K-Mistele) [reply vllm/entrypoints/openai/api_server.py]: done in 230b0630feca14e91384dba09d6e4ebf2b6bf53a

File: docs/source/serving/openai_compatible_server.md [hunk 3]
```diff
@@ -473,3 +478,90 @@ The following extra parameters are supported:
...
+Our Re-rank API applies a cross-encoder model to predict relevant scores between a single query, and
+each of a list of documents. Usually, the score for a sentence pair refers to the similarity between two sentences, on
+a scale of 0 to 1.
+
+You can find the documentation for these kind of models at [sbert.net](https://www.sbert.net/docs/package_reference/cross_encoder/cross_encoder.html).
+
+The rerank endpoints support popular re-rank models such as `BAAI/bge-reranker-base` and other models supporting the
+`score` task. Additionally, both `/rerank` and `/v1/rerank` endpoints
+endpoints are compatible with both  [Jina AI's re-rank API interface](https://jina.ai/reranker/) and
+[Cohere's re-rank  API interface](https://docs.cohere.com/v2/reference/rerank) to ensure compatibility with
```
[the remark this answers is not in the document]
Comment (K-Mistele) [reply docs/source/serving/openai_compatible_server.md]: fixed in 2e9c48e2

File: examples/online_serving/jinjaai_rerank_client.py (hunk 1 above)
Comment (K-Mistele) [reply examples/online_serving/jinjaai_rerank_client.py:13]: fwiw I can't find a Jina SDK / API client, their docs just show using the `requests` library in python. So i left that example, and added a cohere example using v1 and v2 clients.

Comment (DarkLight1337) [reply examples/online_serving/jinjaai_rerank_client.py:13]: Sounds good. Btw you made a typo in the name of this file.

File: vllm/entrypoints/openai/api_server.py [hunk 4]
```diff
@@ -502,6 +508,43 @@ async def create_score_v1(request: ScoreRequest, raw_request: Request):
...
+    assert_never(generator)
+
+
+@router.post("/v1/rerank")
+@with_cancellation
+async def do_rerank_v1(request: RerankRequest, raw_request: Request):
+    logger.warning(
+        "To indicate that the rerank API is not part of the standard OpenAI"
+        " API, we have located it at `/rerank`. Please update your client"
+        "accordingly. (Note: Conforms to JinaAI rerank API)")
```
Comment (DarkLight1337) [inline vllm/entrypoints/openai/api_server.py:534]: I think we should remove these warnings as the Cohere Python client will access this URL by default. Unless there's a way to change the URL in the client?

Comment (K-Mistele) [reply vllm/entrypoints/openai/api_server.py:534]: there's a way to change the base URL, but that's just the server or hostname. unlike OpenAI which expects you to include the `/v1` in the `base_url` if you change it, cohere doesn't want you to set it, it just wants the host and automatically sets `/v1` or `/v2` depending on if you use the v1 client or v2 client. 

I will remove the logger warnings

File: tests/entrypoints/openai/test_rerank.py [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+                                        "documents": documents,
+                                    })
+    rerank_response.raise_for_status()
+    rerank = RerankResponse.model_validate(rerank_response.json())
+
+    assert rerank.id is not None
+    assert rerank.results is not None
+    assert len(rerank.results) == 2
+    assert rerank.results[1].relevance_score <= 0.01
+    assert rerank.results[0].relevance_score >= 0.9
```
Comment (DarkLight1337) [inline tests/entrypoints/openai/test_rerank.py:40]: Nit: Test the results in order of increasing index

File: vllm/entrypoints/openai/api_server.py [hunk 6]
```diff
@@ -514,6 +549,9 @@ async def create_score_v1(request: ScoreRequest, raw_request: Request):
     "score": {
         "default": (ScoreRequest, create_score),
     },
+    "rerank": {
+        "default": (RerankRequest, do_rerank)
+    },
```
Comment (DarkLight1337) [inline vllm/entrypoints/openai/api_server.py:554]: The key here refers to the task in vLLM. Let's use rerank handler instead of score handler for "score" task by default.

File: examples/online_serving/jinjaai_rerank_client.py (hunk 1 above)
Comment (K-Mistele) [reply examples/online_serving/jinjaai_rerank_client.py:13]: fixing

File: vllm/entrypoints/openai/api_server.py (hunk 6 above)
Comment (K-Mistele) [reply vllm/entrypoints/openai/api_server.py:554]: I see. So I should remove the `rerank` key, and replace the value for `score` with `{"default": (RerankRequest, do_rerank)}` ? I am not familliar with this part of the server, so I am unsure if this is likely to break things downstream due to the request pydantic models being different

Comment (DarkLight1337) [reply vllm/entrypoints/openai/api_server.py:554]: Yes, that's correct. This code is mainly being used for `generate` task (#11576), so it shouldn't really matter.

Comment (K-Mistele) [reply vllm/entrypoints/openai/api_server.py]: ok, done

**Comment by K-Mistele** [comment]
Is there an issue with docker or dependencies being downloaded? CI is failing for reasons that seem unrelated to my code. Something about invalid `flashinfer` wheels?

File: vllm/entrypoints/openai/api_server.py [hunk 7]
```diff
@@ -759,6 +802,11 @@ async def init_app_state(
         state.openai_serving_models,
         request_logger=request_logger
     ) if model_config.task == "score" else None
+    state.jinaai_serving_reranking = JinaAIServingRerank(
+        engine_client,
+        model_config,
+        state.openai_serving_models,
+        request_logger=request_logger)
```
Comment (mgoin) [inline vllm/entrypoints/openai/api_server.py:809]: I think we should only make it in the rerank task case, like above
```suggestion
    state.jinaai_serving_reranking = JinaAIServingRerank(
        engine_client,
        model_config,
        state.openai_serving_models,
        request_logger=request_logger
    ) if model_config.task == "rerank" else None
```

File: examples/online_serving/jinjaai_rerank_client.py
Comment (mgoin) [inline examples/online_serving/jinjaai_rerank_client.py:1]: This seems duplicated from `examples/online_serving/jinaai_rerank_client.py`?

File: examples/online_serving/jinaai_rerank_client.py [hunk 8]
```diff
@@ -0,0 +1,33 @@
+"""
+Example of using the OpenAI entrypoint's rerank API which is compatible with
+Jina and Cohere https://jina.ai/reranker
+
+run: vllm serve --model BAAI/bge-reranker-base
```
Comment (mgoin) [inline examples/online_serving/jinaai_rerank_client.py:5]:
```suggestion
run: vllm serve BAAI/bge-reranker-base
```

File: docs/source/serving/openai_compatible_server.md [hunk 9]
```diff
@@ -50,6 +50,11 @@ In addition, we have the following custom APIs:
   - Applicable to all [pooling models](../models/pooling_models.md).
 - [Score API](#score-api) (`/score`)
   - Only applicable to [cross-encoder models](../models/pooling_models.md) (`--task score`).
+- [Re-rank API](#rerank-api) (`/rerank`, `/v1/rerank`)
```
Comment (mgoin) [inline docs/source/serving/openai_compatible_server.md:53]:
```suggestion
- [Re-rank API](#rerank-api) (`/rerank`, `/v1/rerank`, `/v2/rerank`)
```

File: vllm/entrypoints/openai/api_server.py [hunk 10]
```diff
@@ -512,7 +552,10 @@ async def create_score_v1(request: ScoreRequest, raw_request: Request):
         "default": (EmbeddingCompletionRequest, create_embedding),
     },
     "score": {
-        "default": (ScoreRequest, create_score),
+        "default": (RerankRequest, do_rerank)
```
[the remark this answers is not in the document]
Comment (K-Mistele) [reply vllm/entrypoints/openai/api_server.py:555]: This was suggested by @DarkLight1337

**Comment by DarkLight1337** [comment]
> Is there an issue with docker or dependencies being downloaded? CI is failing for reasons that seem unrelated to my code. Something about invalid flashinfer wheels?

You can merge from main to fix this.

File: vllm/entrypoints/openai/api_server.py (hunk 7 above)
Comment (DarkLight1337) [reply vllm/entrypoints/openai/api_server.py:809]: Should use "score" task instead of "rerank" task (which doesn't exist)

File: docs/source/serving/openai_compatible_server.md (hunk 9 above)
Comment (K-Mistele) [reply docs/source/serving/openai_compatible_server.md:53]: 29a03667

File: examples/online_serving/jinjaai_rerank_client.py
Comment (K-Mistele) [reply examples/online_serving/jinjaai_rerank_client.py:1]: 844d39a2

File: examples/online_serving/jinaai_rerank_client.py (hunk 8 above)
Comment (K-Mistele) [reply examples/online_serving/jinaai_rerank_client.py]: 844d39a2

File: vllm/entrypoints/openai/api_server.py (hunk 7 above)
Comment (K-Mistele) [reply vllm/entrypoints/openai/api_server.py]: af83c253

**Comment by K-Mistele** [comment]
> > Is there an issue with docker or dependencies being downloaded? CI is failing for reasons that seem unrelated to my code. Something about invalid flashinfer wheels?
> 
> You can merge from main to fix this.

I am up-to-date with main, but still seeing tests fail for what appear to be dependency-related reasons, this is the relevant part of the trace:

```

[2025-01-25T20:59:12Z]     return forward_call(*args, **kwargs)
--
  | [2025-01-25T20:59:12Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | [2025-01-25T20:59:12Z]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/clip.py", line 340, in forward
  | [2025-01-25T20:59:12Z]     hidden_states, _ = self.self_attn(hidden_states=hidden_states)
  | [2025-01-25T20:59:12Z]                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | [2025-01-25T20:59:12Z]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
  | [2025-01-25T20:59:12Z]     return self._call_impl(*args, **kwargs)
  | [2025-01-25T20:59:12Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | [2025-01-25T20:59:12Z]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
  | [2025-01-25T20:59:12Z]     return forward_call(*args, **kwargs)
  | [2025-01-25T20:59:12Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | [2025-01-25T20:59:12Z]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/clip.py", line 277, in forward
  | [2025-01-25T20:59:12Z]     out = self.attn(query_states, key_states, value_states)
  | [2025-01-25T20:59:12Z]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | [2025-01-25T20:59:12Z]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
  | [2025-01-25T20:59:12Z]     return self._call_impl(*args, **kwargs)
  | [2025-01-25T20:59:12Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | [2025-01-25T20:59:12Z]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
  | [2025-01-25T20:59:12Z]     return forward_call(*args, **kwargs)
  | [2025-01-25T20:59:12Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | [2025-01-25T20:59:12Z]   File "/usr/local/lib/python3.12/dist-packages/vllm/attention/layer.py", line 254, in forward
  | [2025-01-25T20:59:12Z]     from vllm.vllm_flash_attn import flash_attn_func
  | [2025-01-25T20:59:12Z] ImportError: cannot import name 'flash_attn_func' from 'vllm.vllm_flash_attn' (/usr/local/lib/python3.12/dist-packages/vllm/vllm_flash_attn/__init__.py)
```

**Comment by DarkLight1337** [comment]
The failure should be fixed by https://github.com/vllm-project/vllm/pull/12433#pullrequestreview-2574116835. You can merge from main after that.

File: vllm/entrypoints/openai/api_server.py (hunk 4 above)
Comment (mgoin) [reply vllm/entrypoints/openai/api_server.py:534]: Remember to remove or switch to warning_once

**Review by mgoin — APPROVED** [review]
LGTM with one nit

**Comment by K-Mistele** [comment]
CI failing with what looks like a hugging face issue? 
Screenshot 2025-01-26 at 5 05 30 PM
