### PR TITLE
Revert "[MM][CG] Support ViT full CUDA graph for Ernie-4.5-VL image inference" (#45254)

### PR DESCRIPTION
**Pull request by vllm-agent**
Reverts vllm-project/vllm#45254 — [MM][CG] Support ViT full CUDA graph for Ernie-4.5-VL image inference

**Why:** the new `Ernie4_5_VLMoeForConditionalGeneration.postprocess_encoder_output` crashes on its own test case.

```
File "vllm/model_executor/models/ernie45_vl.py", line 1734, in postprocess_encoder_output
    grid_thw = batch_mm_kwargs["image_grid_thw"].to(output.device)
AttributeError: 'dict' object has no attribute 'device'
```

`output` is a dict at this call site, so encoder CUDA-graph replay fails for Ernie-4.5-VL immediately.

- Failing job: `Multi-Modal Models (Extended Generation 1)` — `tests/models/multimodal/generation/test_vit_cudagraph.py::test_vit_cudagraph_image[ernie45_vl]`
- Failures linked to this PR: 1
- Build: https://buildkite.com/vllm/ci/builds/82629 (commit c0202c5)
- The `ernie45_vl` case was added by this same PR, so the job was green before it merged.

The revert applied cleanly with no conflicts. Happy to close this in favour of a one-line fix-forward.

_Auto-generated by CI failure analyzer._

### CODE REVIEW

**Comment by qyYue1389** [comment]
Thanks for catching this

It's a semantic merge conflict, not a bug in the original logic. The SupportsEncoderCudaGraph.postprocess_encoder_output signature changed to a multi-path form — it now receives outputs: dict[str, torch.Tensor] keyed by encoder path, and the caller in encoder_cudagraph.py passes graph_outputs (a dict). #45254 was written and CI-green against the older single-tensor signature; the two landed close together, so each was green independently but the combination broke Ernie's override:

```
grid_thw = batch_mm_kwargs["image_grid_thw"].to(output.device)
AttributeError: 'dict' object has no attribute 'device'
```
I've opened a one-line fix in #51461 — it just updates Ernie's override to the current signature and pulls out the single "default" path output:

```
def postprocess_encoder_output(self, outputs: dict[str, torch.Tensor], ...):
    output = outputs["default"]
    grid_thw = batch_mm_kwargs["image_grid_thw"].to(output.device)
    ...
```
Verified locally with the exact case from build 82629:
`pytest tests/models/multimodal/generation/test_vit_cudagraph.py::test_vit_cudagraph_image[ernie45_vl]
`

Could we merge [#51461](https://github.com/vllm-project/vllm/pull/51461) and close this revert PR? Thank you!

**Comment by khluu** [comment]
superseded by https://github.com/vllm-project/vllm/pull/51461
