### ISSUE TITLE
[Bug]: AttributeError: 'FusedMoE' object has no attribute 'moe' when trying to run Qwen3-Next

### ISSUE THREAD

**Issue by drrros** [vllm-project/vllm#24803]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 24.04.3 LTS (x86_64)
GCC version                  : (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version                : Could not collect
CMake version                : version 3.31.6
Libc version                 : glibc-2.39

==============================
       PyTorch Info
==============================
PyTorch version              : 2.8.0+cu128
Is debug build               : False
CUDA used to build PyTorch   : 12.8
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.3 (main, Aug 14 2025, 17:47:21) [GCC 13.3.0] (64-bit runtime)
Python platform              : Linux-6.8.0-71-generic-x86_64-with-glibc2.39

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 12.9.86
CUDA_MODULE_LOADING set to   : LAZY
GPU models and configuration : 
GPU 0: NVIDIA RTX A5000
GPU 1: NVIDIA RTX A5000

Nvidia driver version        : 570.172.08
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        43 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               20
On-line CPU(s) list:                  0-19
Vendor ID:                            GenuineIntel
Model name:                           Montage Jintide(R) C6230R
CPU family:                           6
Model:                                85
Thread(s) per core:                   1
Core(s) per socket:                   1
Socket(s):                            20
Stepping:                             7
BogoMIPS:                             4190.15
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xsaves arat pku ospke md_clear flush_l1d arch_capabilities
Hypervisor vendor:                    VMware
Virtualization type:                  full
L1d cache:                            640 KiB (20 instances)
L1i cache:                            640 KiB (20 instances)
L2 cache:                             20 MiB (20 instances)
L3 cache:                             715 MiB (20 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-19
Vulnerability Gather data sampling:   Unknown: Dependent on hypervisor status
Vulnerability Itlb multihit:          KVM: Mitigation: VMX unsupported
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Mitigation; Enhanced IBRS
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI SW loop, KVM SW loop
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

==============================
Versions of relevant libraries
==============================
[pip3] conch-triton-kernels==1.3
[pip3] intel_extension_for_pytorch==2.8.0
[pip3] numpy==2.2.6
[pip3] nvidia-cublas-cu12==12.8.4.1
[pip3] nvidia-cuda-cupti-cu12==12.8.90
[pip3] nvidia-cuda-nvrtc-cu12==12.8.93
[pip3] nvidia-cuda-runtime-cu12==12.8.90
[pip3] nvidia-cudnn-cu12==9.10.2.21
[pip3] nvidia-cudnn-frontend==1.14.0
[pip3] nvidia-cufft-cu12==11.3.3.83
[pip3] nvidia-cufile-cu12==1.13.1.3
[pip3] nvidia-curand-cu12==10.3.9.90
[pip3] nvidia-cusolver-cu12==11.7.3.90
[pip3] nvidia-cusparse-cu12==12.5.8.93
[pip3] nvidia-cusparselt-cu12==0.7.1
[pip3] nvidia-ml-py==12.575.51
[pip3] nvidia-nccl-cu12==2.27.3
[pip3] nvidia-nvjitlink-cu12==12.8.93
[pip3] nvidia-nvshmem-cu12==3.3.20
[pip3] nvidia-nvtx-cu12==12.8.90
[pip3] pynvml==12.0.0
[pip3] pytorch-triton==3.4.0+gitf7888497
[pip3] pyzmq==27.1.0
[pip3] torch==2.8.0+cu128
[pip3] torchaudio==2.8.0+cu128
[pip3] torchvision==0.23.0+cu128
[pip3] transformers==4.56.1
[pip3] triton==3.4.0
[pip3] triton_kernels==1.0.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
Neuron SDK Version           : N/A
vLLM Version                 : 0.10.2rc3.dev44+g98229db24 (git sha: 98229db24)
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
  	GPU0	GPU1	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	PHB	0-19	0		N/A
GPU1	PHB	 X 	0-19	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

==============================
     Environment Variables
==============================
LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY

```

</details>

### 🐛 Describe the bug

When trying to run Intel's quantized Qwen3-Next ( https://huggingface.co/Intel/Qwen3-Next-80B-A3B-Instruct-int4-mixed-AutoRound ) I'm getting this error:
```
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600] WorkerProc failed to start.
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600] Traceback (most recent call last):
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 574, in worker_main
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     worker = WorkerProc(*args, **kwargs)
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 440, in __init__
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     self.worker.load_model()
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 213, in load_model
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     self.model_runner.load_model(eep_scale_up=eep_scale_up)
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 2373, in load_model
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     self.model = model_loader.load_model(
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]                  ^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/model_loader/base_loader.py", line 45, in load_model
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     model = initialize_model(vllm_config=vllm_config,
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/model_loader/utils.py", line 64, in initialize_model
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     return model_class(vllm_config=vllm_config, prefix=prefix)
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/models/qwen3_next.py", line 1079, in __init__
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     self.model = Qwen3NextModel(vllm_config=vllm_config,
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/compilation/decorators.py", line 199, in __init__
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     old_init(self, vllm_config=vllm_config, prefix=prefix, **kwargs)
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/models/qwen3_next.py", line 915, in __init__
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     self.start_layer, self.end_layer, self.layers = make_layers(
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]                                                     ^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/models/utils.py", line 643, in make_layers
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/models/qwen3_next.py", line 904, in get_layer
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     return Qwen3NextDecoderLayer(
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]            ^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/models/qwen3_next.py", line 782, in __init__
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     self.mlp = Qwen3NextSparseMoeBlock(
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]                ^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/models/qwen3_next.py", line 115, in __init__
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     self.experts = FusedMoE(num_experts=self.n_routed_experts,
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 909, in __init__
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     else quant_config.get_quant_method(self, prefix))
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/auto_round.py", line 386, in get_quant_method
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     return self.apply_gptq_quant_layer(layer, prefix)
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/auto_round.py", line 330, in apply_gptq_quant_layer
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     return GPTQMarlinMoEMethod(quant_args_marlin, layer.moe)
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]                                                   ^^^^^^^^^
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1962, in __getattr__
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600]     raise AttributeError(
(Worker_TP0 pid=517059) ERROR 09-13 08:02:17 [multiproc_executor.py:600] AttributeError: 'FusedMoE' object has no attribute 'moe'

```

Tried to revert commit c0bd6a684aee2b47fe52b75ec97379e40ca5d36c (latest commit which changes this lines) - vllm loads weigts but still fails:
```
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600] WorkerProc failed to start.
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600] Traceback (most recent call last):
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 574, in worker_main
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]     worker = WorkerProc(*args, **kwargs)
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 440, in __init__
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]     self.worker.load_model()
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 213, in load_model
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]     self.model_runner.load_model(eep_scale_up=eep_scale_up)
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 2373, in load_model
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]     self.model = model_loader.load_model(
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]                  ^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/model_loader/base_loader.py", line 51, in load_model
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]     process_weights_after_loading(model, model_config, target_device)
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/model_loader/utils.py", line 113, in process_weights_after_loading
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]     quant_method.process_weights_after_loading(module)
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/gptq_marlin.py", line 367, in process_weights_after_loading
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]     self.kernel.process_weights_after_loading(layer)
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]   File "/home/drros/vllm/.venv/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/kernels/mixed_precision/bitblas.py", line 177, in process_weights_after_loading
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]     None if quant_config.is_sym else  # type: ignore[union-attr]
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600]             ^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=517502) ERROR 09-13 08:55:08 [multiproc_executor.py:600] AttributeError: 'NoneType' object has no attribute 'is_sym'
```
Command i use to run:
`vllm serve /mnt/nfs-share/LLM/Qwen3-Next-80B-A3B-Instruct-int4-mixed-AutoRound/ --host 0.0.0.0 --port 30000 --dtype auto --tensor-parallel-size 2 --served-model-name Qwen3-30B --max-model-len 4096 --gpu-memory-utilization 0.95`

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by drrros** [comment]
Hardware: dual Nvidia A5000

**Comment by ssakar** [comment]
I have this too with the current version and Intel/Qwen3-30B-A3B-Thinking-2507-int4-AutoRound. My vllm build from Sep 09 works however.

**Comment by David-Wen2025** [comment]
The same to RTX PRO 6000

**Comment by RoadToNowhereX** [comment]
that may be caused by #24217 . If you're using Ampere or later GPU (>=sm80), try to edit site-packages/vllm/model_executor/layers/quantization/auto_round.py in your python environment and set use_marlin = false between line 328 and 329.
i guess vllm has not supported gptq marlin method for autoround, but gptq linear method works well for sm75 and lower.

**Comment by David-Wen2025** [comment]
> that may be caused by [#24217](https://github.com/vllm-project/vllm/pull/24217) . If you're using Ampere or later GPU (>=sm80), try to edit site-packages/vllm/model_executor/layers/quantization/auto_round.py in your python environment and set use_marlin = false between line 328 and 329. i guess vllm has not supported gptq marlin method for autoround, but gptq linear method works well for sm75 and lower.

I have noticed an issue. In line 330, "return GPTQMarlinMoEMmethod (quantit_args_marlin, layer. moe)", the ". moe" in "layer. moe" needs to be removed because the error message mentions "AttributeError: 'FusedMoE' object has no attribute 'moe'".

I have currently modified it to 'return GPTQMarlinMoEMmethod (quant.args_marlin, layer)' and it has been successfully executed！

**Comment by RoadToNowhereX** [comment]
> > that may be caused by [#24217](https://github.com/vllm-project/vllm/pull/24217) . If you're using Ampere or later GPU (>=sm80), try to edit site-packages/vllm/model_executor/layers/quantization/auto_round.py in your python environment and set use_marlin = false between line 328 and 329. i guess vllm has not supported gptq marlin method for autoround, but gptq linear method works well for sm75 and lower.
> 
> I have noticed an issue. In line 330, "return GPTQMarlinMoEMmethod (quantit_args_marlin, layer. moe)", the ". moe" in "layer. moe" needs to be removed because the error message mentions "AttributeError: 'FusedMoE' object has no attribute 'moe'".
> 
> I have currently modified it to 'return GPTQMarlinMoEMmethod (quant.args_marlin, layer)' and it has been successfully executed！

Funny XD. If that works properly, you should fork vllm and pull requests. By the way, in line 244 there's same issue in AWQMoEMethod, you can try the same fix and test it with a awq pack of autoround: [Intel/Qwen3-30B-A3B-Instruct-2507-int4-sym-AutoRound](https://huggingface.co/Intel/Qwen3-30B-A3B-Instruct-2507-int4-sym-AutoRound)

**Comment by David-Wen2025** [comment]
> > > that may be caused by [#24217](https://github.com/vllm-project/vllm/pull/24217) . If you're using Ampere or later GPU (>=sm80), try to edit site-packages/vllm/model_executor/layers/quantization/auto_round.py in your python environment and set use_marlin = false between line 328 and 329. i guess vllm has not supported gptq marlin method for autoround, but gptq linear method works well for sm75 and lower.
> > 
> > 
> > I have noticed an issue. In line 330, "return GPTQMarlinMoEMmethod (quantit_args_marlin, layer. moe)", the ". moe" in "layer. moe" needs to be removed because the error message mentions "AttributeError: 'FusedMoE' object has no attribute 'moe'".
> > I have currently modified it to 'return GPTQMarlinMoEMmethod (quant.args_marlin, layer)' and it has been successfully executed！
> 
> Funny XD. If that works properly, you should fork vllm and pull requests. By the way, in line 244 there's same issue in AWQMoEMethod, you can try the same fix and test it with a awq pack of autoround: [Intel/Qwen3-30B-A3B-Instruct-2507-int4-sym-AutoRound](https://huggingface.co/Intel/Qwen3-30B-A3B-Instruct-2507-int4-sym-AutoRound)

Okay, I will try it later~
