### ISSUE TITLE
[Bug]: vllm.entrypoints.api_server throw exception when startup in v0.8.5

### ISSUE THREAD

**Issue by xjpang** [vllm-project/vllm#17395]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
INFO 04-29 23:02:39 [__init__.py:239] Automatically detected platform cuda.
Collecting environment information...
/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/_distutils_hack/__init__.py:31: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
PyTorch version: 2.6.0+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

Python version: 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.119-1-tlinux4-0010.3-x86_64-with-glibc2.38
Is CUDA available: True
CUDA runtime version: 12.4.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/local/cudnn/lib/libcudnn.so.9.5.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          208
On-line CPU(s) list:             0-207
Vendor ID:                       GenuineIntel
BIOS Vendor ID:                  Intel(R) Corporation
Model name:                      Intel(R) Xeon(R) Platinum 8372HC CPU @ 3.40GHz
BIOS Model name:                 Intel(R) Xeon(R) Platinum 8372HC CPU @ 3.40GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              26
Socket(s):                       4
Stepping:                        11
Frequency boost:                 enabled
CPU max MHz:                     3401.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        6800.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       3.3 MiB (104 instances)
L1i cache:                       3.3 MiB (104 instances)
L2 cache:                        104 MiB (104 instances)
L3 cache:                        143 MiB (4 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-25,104-129
NUMA node1 CPU(s):               26-51,130-155
NUMA node2 CPU(s):               52-77,156-181
NUMA node3 CPU(s):               78-103,182-207
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flashinfer==0.1.6+cu124torch2.4
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-cusparselt-cu12==0.6.2
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pyzmq==26.2.0
[pip3] torch==2.6.0
[pip3] torchaudio==2.6.0
[pip3] torchvision==0.21.0
[pip3] transformers==4.51.2
[pip3] triton==3.2.0
[pip3] tritonclient==2.51.0
[pip3] trpc_triton==0.0.5a4
[conda] flashinfer                0.1.6+cu124torch2.4          pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-cusparselt-cu12    0.6.2                    pypi_0    pypi
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.6.0                    pypi_0    pypi
[conda] torchaudio                2.6.0                    pypi_0    pypi
[conda] torchvision               0.21.0                   pypi_0    pypi
[conda] transformers              4.51.2                   pypi_0    pypi
[conda] triton                    3.2.0                    pypi_0    pypi
[conda] tritonclient              2.51.0                   pypi_0    pypi
[conda] trpc-triton               0.0.5a4                  pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.8.5
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect

TORCHVISION_LIB=/usr/local/lib64
VLLM_NCCL_SO_PATH=/usr/lib/libnccl.so
NCCL_ROOT_DIR=/usr/lib/nccl
CUDNN_HOME=/usr/local/cudnn
CUDA_VISIBLE_DEVICES=6,7
CUDA_VISIBLE_DEVICES=6,7
LD_LIBRARY_PATH=/usr/local/lib/usr/lib64:/usr/lib/nccl:/usr/local/cuda-12.4/compat:/usr/local/lib64:/usr/lib:/usr/local/lib/:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cudnn/lib:
CUDA_HOME=/usr/local/cuda
CUDA_HOME=/usr/local/cuda
NCCL_LAUNCH_MODE=GROUP
NCCL_CUMEM_ENABLE=0
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY

```

</details>

### 🐛 Describe the bug

python3 -m vllm.entrypoints.api_server --model Qwen/Qwen2-7B-Instruct --tensor-parallel-size=2 --gpu-memory-utilization 0.95 --port 21131 --enforce-eager --trust-remote-code  

Whenever the above command is executed, the following exception will be thrown. This issue did not occur before v0.8.5.

```text
(VllmWorker rank=0 pid=47465) 
(VllmWorker rank=0 pid=47465) INFO 04-29 22:59:27 [loader.py:458] Loading weights took 3.59 seconds
(VllmWorker rank=0 pid=47465) INFO 04-29 22:59:27 [gpu_model_runner.py:1347] Model loading took 7.1217 GiB and 170.700889 seconds
INFO 04-29 22:59:31 [kv_cache_utils.py:634] GPU KV cache size: 473,184 tokens
INFO 04-29 22:59:31 [kv_cache_utils.py:637] Maximum concurrency for 32,768 tokens per request: 14.44x
INFO 04-29 22:59:31 [kv_cache_utils.py:634] GPU KV cache size: 473,184 tokens
INFO 04-29 22:59:31 [kv_cache_utils.py:637] Maximum concurrency for 32,768 tokens per request: 14.44x
INFO 04-29 22:59:31 [core.py:159] init engine (profile, create kv cache, warmup model) took 3.96 seconds
INFO 04-29 22:59:31 [core_client.py:439] Core engine process 0 ready.
INFO 04-29 22:59:31 [launcher.py:28] Available routes are:
INFO 04-29 22:59:31 [launcher.py:36] Route: /openapi.json, Methods: HEAD, GET
INFO 04-29 22:59:31 [launcher.py:36] Route: /docs, Methods: HEAD, GET
INFO 04-29 22:59:31 [launcher.py:36] Route: /docs/oauth2-redirect, Methods: HEAD, GET
INFO 04-29 22:59:31 [launcher.py:36] Route: /redoc, Methods: HEAD, GET
INFO 04-29 22:59:31 [launcher.py:36] Route: /health, Methods: GET
INFO 04-29 22:59:31 [launcher.py:36] Route: /generate, Methods: POST
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/starlette/datastructures.py", line 673, in __getattr__
    return self._state[key]
KeyError: 'engine_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/vllm/entrypoints/api_server.py", line 177, in <module>
    asyncio.run(run_server(args))
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/vllm/entrypoints/api_server.py", line 129, in run_server
    shutdown_task = await serve_http(
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/vllm/entrypoints/launcher.py", line 46, in serve_http
    watchdog_loop(server, app.state.engine_client))
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/starlette/datastructures.py", line 676, in __getattr__
    raise AttributeError(message.format(self.__class__.__name__, key))
AttributeError: 'State' object has no attribute 'engine_client'
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by chaunceyjiang** [comment]
Indeed, I can also reproduce it locally.

```
python3 -m vllm.entrypoints.api_server --model Qwen/Qwen3-8B --gpu-memory-utilization 0.95 --port 21131 --enforce-eager --trust-remote-code
....
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/vllm/vllm/entrypoints/api_server.py", line 177, in <module>
    asyncio.run(run_server(args))
  File "/root/anaconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/vllm/vllm/entrypoints/api_server.py", line 129, in run_server
    shutdown_task = await serve_http(
                    ^^^^^^^^^^^^^^^^^
  File "/root/vllm/vllm/entrypoints/launcher.py", line 46, in serve_http
    watchdog_loop(server, app.state.engine_client))
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.12/site-packages/starlette/datastructures.py", line 671, in __getattr__
    raise AttributeError(message.format(self.__class__.__name__, key))
AttributeError: 'State' object has no attribute 'engine_client'

```

**Comment by russellb** [comment]
@afeldman-nm @njhill It looks like this is related to that shutdown / error handling PR #11737

**Comment by chaunceyjiang** [comment]
I can try to fix this issue,

**Comment by Haiming94** [comment]
I have the same question when I update vllm to 0.8.5.

`python3 -m vllm.entrypoints.api_server --model Qwen/Qwen3-14B --enforce-eager --trust-remote-code`
