### ISSUE TITLE
[Bug]: DeepSeek-V4-Flash-0731 + DSpark fails on RTX PRO 6000 (SM120) with FlashInfer sparse MLA decode kernel routing

### ISSUE THREAD

**Issue by harleywang** [vllm-project/vllm#50720]
### Hardware

- GPU: 2 × NVIDIA RTX PRO 6000 Blackwell (96GB)
- Compute Capability: SM120 (12.0)
- CPU: AMD Threadripper PRO 9985WX
- RAM: 96GB

### Software

- Ubuntu 24.04 LTS
- NVIDIA Driver: 595.58.03
- CUDA: 13.2
- Python: 3.12

### vLLM

```bash
vllm 0.26.0+cu129
```

### FlashInfer

```bash
flashinfer-python 0.6.16
```

### Model

```text
deepseek-ai/DeepSeek-V4-Flash-0731
```

### Launch Configuration

- Data Parallel: 2
- Expert Parallel: Enabled
- Tensor Parallel: 1
- Speculative Decoding: DSpark
- num_speculative_tokens: 5 (also reproduced with 7)
- kv-cache-dtype: fp8
- block-size: 256
- max-model-len: 8192

### Environment

- vLLM: 0.26.0
- FlashInfer: 0.6.16
- CUDA: 13.x
- GPU:
  - 2 × NVIDIA RTX PRO 6000 Blackwell (SM120)
  - Compute Capability 12.0

### Model

```
deepseek-ai/DeepSeek-V4-Flash-0731
```

### Launch Command

```bash
vllm serve deepseek-ai/DeepSeek-V4-Flash-0731 \
  --data-parallel-size 2 \
  --enable-expert-parallel \
  --kv-cache-dtype fp8 \
  --gpu-memory-utilization 0.96 \
  --max-model-len 8192 \
  --speculative-config '{"method":"dspark","num_speculative_tokens":5,"draft_sample_method":"greedy"}'
```

(The same happens with `num_speculative_tokens=7`.)

### What happens

The model loads successfully.

FlashInfer autotuning also completes successfully.

Failure happens during kernel warmup.

The stack eventually enters

```
flashinfer_sparse.py

↓

trtllm_batch_decode_sparse_mla_dsv4

↓

_sparse_mla_sm120_paged_attention
```

and fails with

```
Check failed:
num_tokens > 64 (5 vs. 64)

Decode (num_tokens <=64)
must go through
sparse_mla_sm120_decode_dsv4

got num_tokens=5
```

The same happens with

```
num_speculative_tokens=7
```

which reports

```
num_tokens >64 (7 vs.64)
```

### Expected behavior

For

```
num_tokens <=64
```

the code should dispatch to

```
sparse_mla_sm120_decode_dsv4
```

instead of

```
_sparse_mla_sm120_paged_attention
```

### Notes

- DeepGEMM FP4 Experts works correctly.
- Model weights load correctly.
- KV cache initialization succeeds.
- Failure only occurs during DSpark warmup.

This looks like a kernel dispatch issue for SM120 sparse MLA decode.

[vllm-deepseek-v4-flash-0731.log](https://github.com/user-attachments/files/30626869/vllm-deepseek-v4-flash-0731.log)

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by thegoldenflow** [comment]
This looks like a downstream manifestation of FlashInfer issue [#3828](https://github.com/flashinfer-ai/flashinfer/issues/3828) — the SM120 sparse-MLA DSV4 kernels are not instantiated for `topk=256`.

**Mechanism** (there's nothing DSpark-specific about it):

`_paged_attention` in `flashinfer/mla/_sparse_mla_sm120.py` only routes to `sparse_mla_sm120_decode_dsv4` when `(num_heads, topk)` is present in `_DECODE_DSV4_DISPATCH`, which is instantiated for `topk ∈ {128, 512, 1024}` only. On a miss it falls straight through — with no Python-level check — into `sparse_mla_sm120_paged_attention`, the prefill orchestrator in `csrc/sparse_mla_sm120.cu`, which is decode-rejecting: `TVM_FFI_ICHECK_GT(num_tokens, 64)`. That guard is exactly the failure you're seeing.

So the `num_tokens=5` in the message is a red herring: 5 is just `num_speculative_tokens`, and the DSpark draft happens to be the first caller issuing a small-token attention call. Any shape missing from the dispatch table lands in the same place whenever `num_tokens <= 64`. The prefill side has the matching hole — `dispatch_dsv4_single` in `csrc/sparse_mla_sm120_prefill.cu` has no `topk == 256` branch and returns `Unsupported sparse-MLA prefill configuration` for `num_tokens > 64`.

**The fix is upstream in FlashInfer, not in vLLM:**

- flashinfer-ai/flashinfer#3989 — adds the `topk=256` instantiations on *both* paths (decode dispatch table + `dispatch_dsv4_single`). This is the complete one.
- flashinfer-ai/flashinfer#3817 — adds the decode half only.

Both are still open, so no released `flashinfer-python` wheel covers this shape yet; applying #3989 locally is the unblock path today.

**Could you confirm the shape before we call this a duplicate?** Please paste the resolved `num_heads` and `topk` for the failing layer from your log. #3828's repro is `num_heads=32, topk=256, page_block_size=64` at TP2; you're on DP2/TP1 so `num_heads` will differ — `(128, 256)` is equally absent from the table, but worth confirming rather than assuming.

For the broader SM12x DeepSeek-V4 story, #41834 is the PR to track.

**Comment by jasl** [comment]
A contrasting data point from #41834's CI hardware, which may help localise this: **we run 0731 + DSpark nst=5 on FlashInfer 0.6.16 daily and never hit this**, and the reason turns out to be structural rather than luck.

**Our shape:** 2x GB10 (SM121), TP=2, no DP, no EP. `n_heads=64` → `num_heads=32` per rank, `sliding_window=128`, `index_topk=512`, `block-size 256`, fp8 KV.

The dispatch key is taken from the **primary** `indices` tensor:

```python
# flashinfer/mla/_sparse_mla_sm120.py
num_tokens, num_heads, d_qk = q.shape
topk = indices.shape[-1]                  # <- primary indices, not extra_indices
extra_topk = int(extra_indices.size(-1)) if extra_indices is not None else 0
if model_type == _MODEL_TYPE_DSV4 and kv_pbs == _DECODE_DSV4_PAGE_BLOCK_SIZE \
   and _decode_dsv4_dispatchable(num_tokens, num_heads, topk, d_qk, kv_pbs, extra_topk):
```

#41834's SM120 decode path calls the low-level `_SparseMLAPagedAttentionRunner` with the **sliding-window** indices as `indices` and the sparse top-k as `extra_indices`:

```python
self._sm120_runner.run(
    q, swa_cache, swa_indices, output, self.scale,
    topk_length=swa_lens,
    extra_indices=topk_indices, extra_topk_length=topk_lens,
    mid_out=mid_out, mid_lse=mid_lse,
)
```

so our key is `(num_heads=32, topk=128)` — the sliding-window width — which **is** instantiated. Our `index_topk=512` never enters the key at all; it only reaches `_decode_dsv4_dispatchable` as `extra_topk`. Verified against the installed 0.6.16:

```
_DECODE_DSV4_DISPATCH: 15 entries
  num_heads ∈ {8, 16, 32, 64, 128}
  topk      ∈ {128, 512, 1024}
  (32, 128) PRESENT      (32, 256) MISSING      (128, 256) MISSING
```

That also means the daily serve is itself evidence: DSpark nst=5 issues decode calls with `num_tokens=5`, so if we were falling through to the prefill orchestrator we would trip `TVM_FFI_ICHECK_GT(num_tokens, 64)` on the very first step, every time.

So the analysis above looks right to me, with one refinement worth stating: **the exposure depends on which entry point the caller uses, not only on the model config.** A caller that passes the sparse top-k as the *primary* `indices` gets `topk = index_topk` in the key; a caller that passes the sliding window as primary gets `topk = sliding_window`. Both are legitimate uses of the same kernel and only the first is exposed to the `topk=256` hole. Anyone who reproduces this is worth asking which of the two they are on, alongside `num_heads`/`topk`.

Also worth flagging for anyone bisecting: 0.6.16 is not a regression here. The same 15-entry table with `topk ∈ {128, 512, 1024}` is what 0.6.15.post1 shipped; the hole predates the bump.

We can test candidate fixes on SM121 if that is useful — flashinfer-ai/flashinfer#3989 in particular, since it covers both the decode table and `dispatch_dsv4_single`.

**Comment by b0bh00d** [comment]
Confirming reproduction with a different config variant that may help narrow down the trigger condition, since @jasl's non-repro case is very close to mine otherwise.

**My setup**: 2× NVIDIA GB10 (DGX Spark, SM121/12.1), one GPU per node, `--tensor-parallel-size 2` over Ray (TCP/RoCE, 2 physical nodes), **`--enable-expert-parallel`**, `--block-size 256`, `--kv-cache-dtype fp8`, vLLM 0.26.0, FlashInfer 0.6.14, `--speculative-config '{"method":"dspark","num_speculative_tokens":7,"draft_sample_method":"greedy"}'`.

Hit the identical assertion:
```
tvm.error.InternalError: Check failed: num_tokens > 64 (7 vs. 64) : Decode (num_tokens <= 64) must go through sparse_mla_sm120_decode_dsv3_2 or sparse_mla_sm120_decode_dsv4; got num_tokens=7
```

@jasl's non-repro daily config is 2× GB10 SM121, TP=2, **no DP, no EP** — otherwise very close to mine. The one config difference I can point to is `--enable-expert-parallel`. I don't have the resolved `(num_heads, topk)` shape captured from that run (didn't have debug instrumentation in at the time), but if EP sharding changes how `num_heads` resolves per rank (e.g. expert-parallel-specific code path calling into `forward_mqa` with different tensor shapes than the TP-only path), that could be the missing variable between "reproduces" and "doesn't." Happy to re-run with added logging if that resolved shape is still useful — let me know what you'd want printed.

Also, for what it's worth: reverting `block-size` from 256 to 64 (matching `_DECODE_DSV4_PAGE_BLOCK_SIZE`) avoids this specific crash but immediately hits a different one — `vllm/models/deepseek_v4/compressor.py` hardcodes an internal `self.block_size = 4` (or `8`) assuming a global `--block-size 256` (see the `TODO(yifan): make block size automatically determined and configurable` comment there), so `get_kv_cache_groups` then fails with `assert max(sm_page_sizes) <= max(all_page_sizes)`. So on this stack, block-size 256 and 64 each satisfy one constraint and break the other — worth being aware of if anyone reaches for that as a workaround.

**Comment by aisensiy** [comment]
Another reproduction, with the resolved dispatch shape that @thegoldenflow asked for. This is a **TP=4, no-DP, no-EP** config, which I think is a new point in the matrix and rules out one of the variables raised above.

### Environment

- 4× RTX PRO 6000 Blackwell Server Edition (SM120, 12.0), single node, no NVLink
- vLLM 0.26.0, **flashinfer-python 0.6.14**, CUDA 13.0, driver 595.71.05
- `deepseek-ai/DeepSeek-V4-Flash-0731` (official checkpoint, FP4 experts)
- `--tensor-parallel-size 4` (no DP, **no `--enable-expert-parallel`**), `--block-size 256`, `--kv-cache-dtype fp8`, `--max-model-len 131072`
- `--speculative-config '{"method":"dspark","num_speculative_tokens":7}'`

Fails identically at warmup, right after `DSpark draft model loaded: 96 params`:

```
tvm.error.InternalError: Check failed: num_tokens > 64 (7 vs. 64) : Decode (num_tokens <= 64)
must go through sparse_mla_sm120_decode_dsv3_2 or sparse_mla_sm120_decode_dsv4; got num_tokens=7
```

### Resolved shapes

I instrumented `_paged_attention` in `flashinfer/mla/_sparse_mla_sm120.py` to print every distinct
`(num_tokens, num_heads, topk, d_qk, kv_pbs, extra_topk)` it sees, plus the outcome of each guard.
Complete set observed over a full startup:

```
num_tokens=2  num_heads=16  topk=128  d_qk=512  kv_pbs=64  extra_topk=0     in_table=True   dispatchable=True
num_tokens=2  num_heads=16  topk=128  d_qk=512  kv_pbs=64  extra_topk=512   in_table=True   dispatchable=True
num_tokens=2  num_heads=16  topk=128  d_qk=512  kv_pbs=64  extra_topk=1024  in_table=True   dispatchable=True
num_tokens=7  num_heads=16  topk=256  d_qk=512  kv_pbs=64  extra_topk=0     in_table=False  dispatchable=False   <-- crashes here
```

`_DECODE_DSV4_DISPATCH` on 0.6.14 is the same 15-entry table reported above
(`num_heads ∈ {8,16,32,64,128} × topk ∈ {128,512,1024}`), so **`(16, 256)` is the missing key**.

### Three things this pins down

1. **The `topk=256` diagnosis is confirmed, with a third `num_heads` value.** #3828's repro is `(32, 256)`; `(128, 256)` was raised as a candidate here; ours is **`(16, 256)`**. So the hole is in the `topk` axis and every `num_heads` in the table is exposed to it, which is consistent with flashinfer-ai/flashinfer#3989 (adding the `topk=256` instantiations) being the right fix rather than anything `num_heads`-specific.

2. **Expert parallelism is not required to reproduce.** @b0bh00d suggested `--enable-expert-parallel` might be the variable separating his repro from @jasl's non-repro. We reproduce with EP **off** and DP off, plain TP=4. The variable is which caller supplies the primary `indices`, exactly as @jasl described.

3. **`--block-size 256` is not the variable either.** `kv_pbs` resolves to **64** on every call here
 despite `--block-size 256`, so the `kv_pbs == _DECODE_DSV4_PAGE_BLOCK_SIZE` guard passes and is never what short-circuits the dispatch. Worth stating explicitly because the block-size 256 ↔ 64 tension noted above (`compressor.py`'s hardcoded internal block size) could otherwise look like a contributing factor, on this stack it isn't.

Also consistent with @jasl's note that this is not a 0.6.16 regression: we see it on **0.6.14** with
the identical 15-entry table.

### On the two code paths

The target model's own decode calls come through with `topk=128` (the sliding window) and the sparse top-k arriving as `extra_topk ∈ {512, 1024}` — i.e. on released vLLM 0.26.0 the primary-`indices` argument is already the sliding window, and those calls dispatch fine. **The DSpark draft layer is the only caller in this configuration that passes `topk=256` as primary.** Our checkpoint has `sliding_window=128`, `index_topk=512`, `dspark_markov_rank=256`; I did not trace which of those the draft's 256 derives from, so I'll leave that to someone who knows the DSpark layer.

**Comment by jasl** [comment]
@aisensiy's instrumentation closes this, and it also explains our non-repro in a way that is structural rather than lucky. Answering the open question in that comment — *"I did not trace which of those the draft's 256 derives from"* — it is `dspark_markov_rank`.

**Where the 256 comes from.** In `vllm/models/deepseek_v4/nvidia/dspark.py`:

```python
markov_rank = int(getattr(config, "dspark_markov_rank", 256))
```

That matches the `dspark_markov_rank=256` in your checkpoint, and it is neither `sliding_window` (128) nor `index_topk` (512) — consistent with your observation that the target model's own calls come through at `topk=128` with the sparse top-k arriving as `extra_topk ∈ {512, 1024}` and dispatching fine.

**Why the DSpark draft is the only caller passing it as *primary*.** Upstream's draft layer reuses `DeepseekV4DecoderLayer`, so its attention is the ordinary DSv4 sparse path — the module docstring says as much: *"To implement non-causal attention, we leverage the sparse attention implementation"*. The draft's non-causal window is `markov_rank`, so it arrives at `_paged_attention` as `indices.shape[-1] == 256`, and `topk = indices.shape[-1]` is exactly the dispatch key. `(16, 256)`, `(32, 256)`, `(128, 256)` — none of them are in the 15-entry table, which is why every `num_heads` you three have tried is exposed.

**Why #41834 does not reproduce it.** Not because of TP/DP/EP or block size — those are all ruled out now, and correctly. It is that #41834 replaced the DSpark draft attention kernel outright (`71a03834a5`, "Replace DSpark attention v1 kernel"). On that branch the draft layer keeps a DSv4 attention object only for its parameters and metadata (`n_local_heads`, `window_size`, `wo_b`, …) and runs the actual attention through a branch-local Triton kernel:

```python
# vllm/models/deepseek_v4/nvidia/dspark.py
def _dspark_attention(self, ...):
    ...
    o = dspark_triton_attention(...)
```

so the draft never enters `flashinfer/mla/_sparse_mla_sm120.py:_paged_attention` at all, and the `topk=256` hole is unreachable from it. The target model's decode calls still go through FlashInfer, but those are the `topk=128` sliding-window ones that dispatch fine — which is what my earlier comment described from the caller side without my having realised the draft was on a different kernel entirely.

That is worth stating plainly for anyone triaging: **on this stack, the "which caller supplies the primary indices" question resolves to "which DSpark attention implementation you are running", and the two available answers differ by a whole kernel.**

**So there are two independent routes out of this**, and they are not equivalent:

1. **flashinfer-ai/flashinfer#3989** — add the `topk=256` instantiations to both the decode dispatch table and `dispatch_dsv4_single`. This is the actual fix: it repairs the shape hole for every caller, including upstream vLLM's own DSpark draft, and it is where the problem lives. Still open, so no released wheel has it.
2. **Run #41834**, where the draft does not use those kernels. This sidesteps the crash today but it is a side effect of a branch-local kernel replacement, not a fix to the reported bug, and nobody should read it as one.

Happy to test #3989 on SM121 once someone has it in a buildable state — we have 4× GB10 and the DSpark configuration that would exercise the `topk=256` decode path if the draft were routed back through FlashInfer.

One correction to my earlier comment while I am here: I said there that the exposure "depends on which entry point the caller uses, not only on the model config". That is true but it undersold it — the entry point is not a caller-side detail here, it is a different attention kernel, and @aisensiy's trace showing `extra_topk=0` on the failing call (rather than 512/1024) is the tell I should have picked up on and did not.

**Comment by jasl** [comment]
I tested flashinfer-ai/flashinfer#3989 on SM121a (2× GB10) — **it fixes this**,
and there is a way to apply it today without building FlashInfer. Full detail in
flashinfer-ai/flashinfer#3989 (comment); the short version:

Calling the SM120 sparse-MLA entrypoint directly at DSv4 shapes with
`num_tokens=7` — the `7` from @b0bh00d's and @aisensiy's `num_speculative_tokens`:

| num_heads | topk | stock 0.6.16 | with #3989 |
|---|---|---|---|
| 16 | 128 | OK | OK |
| 16 | **256** | `Check failed: num_tokens > 64 (7 vs. 64)` | OK |
| 32 | **256** | `Check failed: num_tokens > 64 (7 vs. 64)` | OK |
| 128 | **256** | `Check failed: num_tokens > 64 (7 vs. 64)` | OK |

FlashInfer's own reference tests pass on the patched build (75 decode, 44
prefill), including the three `topk=256` decode shapes the PR instantiates but
does not add to its test grid.

### Workaround while #3989 is unmerged

These kernels are JIT-built from sources shipped inside the wheel, so patching
the installed package is enough — no FlashInfer build, no AOT step:

```bash
PKG=$(python -c "import flashinfer,os;print(os.path.dirname(flashinfer.__file__))")
git clone https://github.com/flashinfer-ai/flashinfer.git && cd flashinfer
git fetch origin pull/3989/head:pr3989 && git checkout pr3989
cp csrc/sparse_mla_sm120_decode_dsv4.cu csrc/sparse_mla_sm120_prefill.cu "$PKG/data/csrc/"
cp flashinfer/mla/_sparse_mla_sm120.py "$PKG/mla/"
rm -rf ~/.cache/flashinfer/*sparse_mla_sm120*
```

The JIT rebuilds on the next call. Note @b0bh00d and @aisensiy are both on
FlashInfer 0.6.14 — I tested this against 0.6.16, so upgrade first; the dispatch
table is identical in both, so 0.6.14 fails the same way for the same reason.

### What I have *not* shown

**Kernel level only.** I could not run this end-to-end through vLLM's DSpark,
and the reason is the same one that makes us the odd non-repro here: #41834
replaces the DSpark draft attention with a windowed kernel over a small
per-request buffer, so our draft never reaches FlashInfer's paged sparse-MLA at
all. Upstream's `dspark.py` builds a `DeepseekV4DecoderLayer` directly and reads
`config.dspark_markov_rank`, which is the path all three of you are on — I have
no way to exercise it locally without running upstream's draft implementation.

So: the kernel now accepts your shape and computes it correctly, but somebody on
the failing config should confirm the serve actually comes up. If one of you
applies the patch above, that closes the loop.

### Why this was hard to localise, and a fix for that

#3989 adds the missing shape, but the *diagnosis* stays bad for the next one.
`_paged_attention` does consult `_decode_dsv4_dispatchable` — a **miss is simply
unhandled**, falling through to the prefill orchestrator with nothing checking
that the call is decode-sized. So an uninstantiated `topk` reports an assertion
about `num_tokens`, which is not the thing that is wrong. Three reports and an
instrumented run went into working that out.

I have suggested a guard on the FlashInfer PR that would name the actual
`(num_heads, topk)` instead, and offered to send it separately.

**Comment by b0bh00d** [comment]
Confirming end-to-end on the exact config @jasl asked about: **2× GB10 (SM121a)**, TP=2, `--enable-expert-parallel`, `deepseek-ai/DeepSeek-V4-Flash-0731`, upstream `dspark.py` (not #41834's branch-local kernel), `--speculative-config '{"method":"dspark","num_speculative_tokens":7}'`.

### What I did

1. Upgraded `flashinfer-python` 0.6.14 → 0.6.16 on both nodes (pinning `torch==2.11.0` back down afterward — a bare `uv pip install -U flashinfer-python` will happily drag torch to 2.13.0 since flashinfer's own `torch` dependency is unpinned, which breaks vLLM 0.26.0's `torch==2.11.0` compiled-extension pin. Worth flagging for anyone following this thread.)
2. Applied the JIT patch from your comment (cloned flashinfer, checked out `pull/3989/head`, copied `sparse_mla_sm120_decode_dsv4.cu`, `sparse_mla_sm120_prefill.cu`, `_sparse_mla_sm120.py` into the installed package, cleared `~/.cache/flashinfer/*sparse_mla_sm120*`).
3. Restarted, reproduced the crash you'd expect if the patch *hadn't* landed correctly — confirmed it's gone. The DSpark draft layer now dispatches `(16, 256)` cleanly through `sparse_mla_sm120_decode_dsv4`.

### Result

Serve comes up, stays up, and answers correctly under greedy decoding. `/metrics` shows genuine spec-decode activity, not a silent fallback:

```
vllm:spec_decode_num_drafts_total 7
vllm:spec_decode_num_draft_tokens_total 49
vllm:spec_decode_num_accepted_tokens_total 18
vllm:spec_decode_num_accepted_tokens_per_pos_total{position="0"} 5
vllm:spec_decode_num_accepted_tokens_per_pos_total{position="1"} 5
vllm:spec_decode_num_accepted_tokens_per_pos_total{position="2"} 2
...
```

That's the accept-rate curve I'd expect (decaying by position), so #3989 is fixing real inference, not just clearing the assertion.

### Three more blockers on the way to a clean serve — none of them your bug, but worth logging here since anyone following #3989 to get DSpark working will hit them in sequence

1. **`tilelang` is a hard, unconditional `vllm==0.26.0` dependency (pinned `tilelang==0.1.9`) for `nvidia/model.py`, `nvidia/mtp.py`, and `nvidia/dspark.py`, but it was simply not installed** in either of our venvs — presumably because nothing had exercised that import path before (the topk=256 crash always happened first). `pip install tilelang==0.1.9` surfaces it.
2. **`tilelang` and `flashinfer-python` want incompatible `apache-tvm-ffi` versions.** `tilelang==0.1.9` breaks on `apache-tvm-ffi==0.1.13.post0` (`AttributeError: attribute '__dict__' of 'type' objects is not writable`, in its vendored TVM's `ir.DictAttrs` registration) but works on `0.1.7`. `flashinfer-python==0.6.16`'s sparse-MLA kernels need `apache-tvm-ffi>=~0.1.10` (`make_kwargs_wrapper() got an unexpected keyword argument 'map_dataclass_to_tuple'` on 0.1.7). Both packages' declared version ranges technically permit the whole 0.1.6–0.1.13 span, so `uv`/`pip` won't warn you — it's a real runtime incompatibility inside the allowed range, not a resolvable constraint. `apache-tvm-ffi==0.1.10` is the version that satisfied both for us.
3. **DSpark's extra CUDA graphs (~2.3–2.5 GiB/node) tip unified-memory nodes into Ray's own OOM killer.** GB10's shared CPU+GPU pool means `--gpu-memory-utilization` competes with host/Ray/OS memory, not just other GPU workloads. `0.8` (our previous known-good value *without* speculative decoding) now gets a node to 115.6/121.7 GiB (95%) mid-warmup and Ray kills a worker with no Python traceback — just `RayWorkerProc rank=[0] died unexpectedly`. `0.7` avoids that but then vLLM's own KV-cache sizing check fails for the full 262144 context (`2.78 GiB KV cache is needed... available KV cache memory (2.05 GiB)`). `0.75` threads the needle for our checkpoint/context-length combination.

None of that is flashinfer's problem, but the combination cost more time to isolate than the #3989 fix itself, so recording it here in case it saves someone a repeat.

@aisensiy @thegoldenflow — if either of you is on a similar node-memory-constrained setup (vs. discrete-GPU RTX PRO 6000), #3 above may bite you even after #1/#2 are handled.

**Comment by dkmode22** [comment]
Reproduced on different hardware and a different parallelism layout, which narrows the trigger.

Environment:
- 2x NVIDIA DGX Spark (GB10, SM121 / compute 12.1), aarch64
- vLLM 0.26.0 (PyPI aarch64 wheel), FlashInfer 0.6.14, torch 2.11.0+cu130
- DeepSeek-V4-Flash-0731 (NVFP4), TP=2 across the two nodes, no DP, no EP
- kv-cache-dtype fp8_ds_mla, block-size 256, max-model-len 766208
- speculative-config `{"method":"dspark","num_speculative_tokens":5,"draft_sample_method":"probabilistic"}`

Same check failure, reached through the decode autotune rather than the trtllm path:

```
vllm/model_executor/warmup/kernel_warmup.py:99  deepseek_v4_sparse_mla_attention_warmup(worker)
vllm/model_executor/warmup/flashinfer_sparse_mla_warmup.py:237 -> :204 _deepseek_v4_sparse_mla_decode_autotune
vllm/model_executor/warmup/flashinfer_sparse_mla_warmup.py:135  module.sparse_mla_sm120_paged_attention(...)
tvm.error.InternalError: Check failed: num_tokens > 64 (5 vs. 64) : Decode (num_tokens <= 64)
must go through sparse_mla_sm120_decode_dsv3_2 or sparse_mla_sm120_decode_dsv4; got num_tokens=5
```

num_tokens equals num_speculative_tokens for us as well. Model load completes (79 GiB per rank) and the failure lands during compile_or_warm_up_model, before the API port binds.

So this is not specific to DP/EP, x86, FlashInfer 0.6.16, or plain fp8 KV: TP=2 on aarch64 with fp8_ds_mla and FlashInfer 0.6.14 hits the identical check at sparse_mla_sm120.cu:261. The common factor looks like the SM120-family sparse MLA warmup calling the paged attention entry point with a decode-sized num_tokens instead of routing to the decode_dsv4 entry, whenever dspark spec decode is configured.

Full environment and config for our repro: https://github.com/dkmode22/DeepSeek-V4-Flash-0731-3.23x1M-context-653-toks-2x-DGX-Spark-GB10

**Comment by HyokaChen** [comment]
I see flashinfer merge this commit: [https://github.com/flashinfer-ai/flashinfer/pull/4380](4380)，maybe need vllm  publish new version can solve this issue?

**Comment by Mirrdhyn** [comment]
We hit the same failure class on a different family-12 part. PR #51538 resolves it for
us. It is open, not yet merged.

Our configuration is close to yours but not identical, so take this as corroboration
rather than an exact reproduction:

| | you | us |
|---|---|---|
| GPU | 2× RTX PRO 6000, SM120 | 2× DGX Spark GB10, SM121 |
| parallelism | DP=2, EP on, TP=1 | TP=2, EP off, Ray, 2 nodes |
| vLLM | 0.26.0 | `main` + PR #51538 (`db39e675`) |
| flashinfer | 0.6.16 | 0.6.18.dev20260811 |
| CUDA / torch | 13.x | 13.2 / 2.13.0+cu132 |
| model | DeepSeek-V4-Flash-0731 | same |
| spec | dspark, k=5 | dspark, k=5 |

With PR #51538 applied the server starts, serves, and keeps speculative decoding
active: about 60 requests from 4 k to 131 k input tokens, no crash, acceptance
95.6–100 % on the long-context sweep and 34.8–90.1 % on short single-stream series
depending on what the model is writing.

Two things may matter before you retest.

## DeepGEMM

`hc_mult=4` in this checkpoint sends every forward pass through DeepGEMM's
hyperconnection path. The DeepGEMM revision pinned in
`cmake/external_projects/deepgemm.cmake` ships no `sm120_*` kernels at all, and its
dispatch in `csrc/apis/hyperconnection.hpp` handles `arch_major` 9 and 10 only, so
family-12 falls through to `DG_HOST_UNREACHABLE("Unsupported architecture")`. Building
from source, you hit this well before the sparse-MLA routing. We repointed the pin at
`deepseek-ai/DeepGEMM a6b593d` and filed it separately. If you install a prebuilt
wheel this may not apply to you.

## FlashInfer: you need PR #4380, and 0.6.16 does not have it

You are on flashinfer 0.6.16. That is very likely your immediate blocker, and the
reason is not the one you would guess from `index_topk=512` in the config.

The `top_k` the SM120 sparse-MLA decode dispatch asks for is not the model's
`index_topk`. It is computed in `get_dspark_swa_index_width`
(`vllm/v1/attention/backends/mla/compressor_utils.py`):

```
top_k = ceil((sliding_window + num_speculative_tokens) / 64) * 64
```

This checkpoint has `sliding_window=128`, so with your `num_speculative_tokens=5` the
required specialization is `(num_heads, 192)`. With `k=7`, still 192. In fact any
`k` from 1 to 64 lands on 192, and only `k=0` stays at 128:

| k | width | required top_k | in 0.6.16 / 0.6.17 |
|---|---|---|---|
| 0 | 128 | 128 | yes |
| 1–64 | 129–192 | 192 | no |
| 65+ | 193+ | 256 | no |

The 192 and 256 entries were added by flashinfer PR #4380, merged 2026-08-08. Stable
0.6.16 and 0.6.17 carry only 128, 512 and 1024. So **with DSpark speculation enabled at
any depth, a flashinfer build predating #4380 cannot serve this model on SM12x**.

We verified this the hard way: we downgraded from the nightly to 0.6.17 stable on our
own setup and got

```
RuntimeError: FLASHINFER_MLA_SPARSE_DSV4 on SM120 requires a FlashInfer DSV4 sparse
MLA decode specialization for (num_q_heads=32, top_k=192).
Install a FlashInfer build containing flashinfer-ai/flashinfer#4380.
```

We run `flashinfer-python==0.6.18.dev20260811` from the nightly index.

Note that vLLM's own metadata still pins `flashinfer-python==0.6.15.post1`, so a clean
install will give you a version that cannot run this path with speculation.

Our full setup, the raw measurement draws and the scripts are at
https://github.com/Mirrdhyn/dsv4-flash-dgx-spark if you want to diff it against yours.

**Comment by TurboTheTurtle** [comment]
End-to-end confirmation on the official vLLM 0.27.1 dependency layout, plus one packaging detail that can hide the source fix.

vLLM 0.27.1 pins `flashinfer-python==0.6.16.post3` and installs the matching `flashinfer-jit-cache`. I replaced the three wheel-shipped sparse-MLA sources with the exact `topk=256` changes from flashinfer-ai/flashinfer#3989 and cleared the user JIT cache, but the failure was unchanged: the separate precompiled module at `flashinfer_jit_cache/jit_cache/sparse_mla_sm120` was loaded before those patched sources.

After preserving that stock module under a non-active path, the next launch JIT-compiled the patched sources. The exact live shape `(tokens=5, heads=32, topk=256, d_qk=512)` then passed independently on both DGX Spark / GB10 ranks, followed by vLLM autotuning, CUDA graph capture, full TP=2 API readiness, DSpark activity, and a six-part functional run including 48,033-token retrieval. Both ranks stayed restart-zero and OOM-free with no Xid or CUDA/NCCL/runtime fatal.

flashinfer-ai/flashinfer#4380 now contains the merged 192/256 specializations, but a vLLM image/release needs the source package and precompiled JIT cache to agree. Updating only the Python/CUDA sources can still leave this issue reproducing if the older `sparse_mla_sm120` AOT module remains active.
