### PR TITLE
[CPU] Fix spec decode kernel signatures for synthetic mode compatibility

### PR DESCRIPTION
**Pull request by jmamou**
## Purpose

Fixes CPU speculative decoding crashes by adding missing parameters to CPU Triton fallback kernel signatures. 

**Problem**: CPU speculative decoding fails immediately with `TypeError: _rejection_greedy_sample_kernel_impl() got an unexpected keyword argument 'SYNTHETIC_MODE'`

**Root cause**: The rejection sampler (`vllm/v1/sample/rejection_sampler.py`) passes `uniform_probs`, `synthetic_conditional_rates`, and `SYNTHETIC_MODE` parameters to support synthetic mode, but the CPU fallback kernels (`vllm/utils/cpu_triton_utils.py`) did not accept them.

**Solution**: Add these parameters to CPU kernel signatures:
- `_rejection_greedy_sample_kernel_impl`: Added `uniform_probs`, `synthetic_conditional_rates`, `SYNTHETIC_MODE`
- `_rejection_random_sample_kernel_impl`: Added `synthetic_conditional_rates`, `SYNTHETIC_MODE`

The parameters are accepted but not used (C++ kernels don't implement synthetic mode yet), maintaining compatibility with the calling convention.

**Impact**:
- **Enables CPU speculative decoding** in vLLM v1 (previously completely broken)
- **No GPU impact** (GPU kernels already handle these parameters)
- **Backward compatible** (all parameters have default values)
- **Future-proof** for synthetic mode implementation in C++ CPU kernels

**Related**: Builds on CPU spec decode support from #32662

## Test Plan

Tested on **Intel Xeon Platinum 8580** (Emerald Rapids, 120 cores, 240 threads):

```bash
# Baseline (no spec decode)
VLLM_USE_V1=1 VLLM_TARGET_DEVICE=cpu \
python -m vllm.entrypoints.openai.api_server \
  --model facebook/opt-1.3b \
  --max-model-len 512 \
  --port 8000

# Spec decode  
VLLM_USE_V1=1 VLLM_TARGET_DEVICE=cpu \
python -m vllm.entrypoints.openai.api_server \
  --model facebook/opt-1.3b \
  --speculative_config '{"method":"draft_model","model":"facebook/opt-125m","num_speculative_tokens":5}' \
  --max-model-len 512 \
  --port 8001

# Run 10 inference requests @ 50 tokens each
```

### Before Fix
```
❌ Server crashes on initialization:
TypeError: _rejection_greedy_sample_kernel_impl() got an unexpected keyword argument 'SYNTHETIC_MODE'
```

### After Fix

**Test: opt-1.3b + opt-125m** (10.8x model ratio)

| Metric | Baseline | Spec Decode | Improvement |
|--------|----------|-------------|-------------|
| **Throughput** | 27.41 tok/s | 60.48 tok/s | **2.21x** 🎉 |
| **Latency** | 1.824s/req | 0.826s/req | **2.21x faster** |
| **Total Time** | 18.2s (500 tok) | 8.3s (500 tok) | **55% reduction** |

**Key Findings**:
- ✅ Server initializes successfully (previously crashed)
- ✅ Achieves 2.21x speedup

### Code Changes

**Modified file**: `vllm/utils/cpu_triton_utils.py`

```python
# Before:
def _rejection_greedy_sample_kernel_impl(
    output_token_ids,
    cu_num_draft_tokens,
    draft_token_ids,
    target_argmax,
    bonus_token_ids,
    is_greedy,
    max_spec_len,
):

# After:
def _rejection_greedy_sample_kernel_impl(
    output_token_ids,
    cu_num_draft_tokens,
    draft_token_ids,
    target_argmax,
    bonus_token_ids,
    is_greedy,
    max_spec_len,
    uniform_probs=None,                    # Added
    synthetic_conditional_rates=None,      # Added
    SYNTHETIC_MODE=False,                  # Added
):
```

Similar changes for `_rejection_random_sample_kernel_impl` (added `synthetic_conditional_rates`, `SYNTHETIC_MODE`).

---

<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [x] The purpose of the PR: Fix CPU spec decode crash by adding missing kernel parameters
- [x] The test plan: Tested on Xeon 8580 with opt-350m and opt-1.3b model pairs
- [x] The test results: Server initializes successfully, 2.21x speedup with opt-1.3b + opt-125m
- [x] Documentation: Added explanatory comments in code explaining parameter usage
</details>

### CODE REVIEW

**Comment by jmamou** [comment]
PR #32662 successfully enabled CPU speculative decoding when it was merged on **April 10, 2026**. However, CPU spec decode broke shortly after due to a subsequent change.

1. **April 10, 2026**: PR #32662 merged, adding CPU fallback kernels for spec decode
   - Kernels worked correctly with the rejection sampler at that time
   - No synthetic mode parameters were being passed

2. **April 23, 2026**: PR #40662 merged, adding unified synthetic acceptance rate support
   - Updated rejection sampler to **always** pass `SYNTHETIC_MODE`, `uniform_probs`, and `synthetic_conditional_rates` parameters
   - GPU kernels were updated to accept these parameters
   - **CPU kernels were not updated**, causing immediate crashes with `TypeError: unexpected keyword argument 'SYNTHETIC_MODE'`

The rejection sampler (`vllm/v1/sample/rejection_sampler.py`) now passes synthetic mode parameters unconditionally, even when `SYNTHETIC_MODE=False`. CPU fallback kernels must accept these parameters to maintain compatibility with the calling convention, even though the C++ implementations don't use them yet.

This fix restores CPU speculative decoding functionality that was broken by PR #40662, ensuring CPU users can benefit from the spec decode support originally added in PR #32662.

@ganeshr10

File: vllm/utils/cpu_triton_utils.py [hunk 1]
```diff
@@ -233,11 +240,17 @@ def _rejection_random_sample_kernel_impl(
...
     NO_DRAFT_PROBS=False,
+    SYNTHETIC_MODE=False,
 ):
     # C++ kernel expects int64 for all integer tensors and float32 for probs.
     # uniform_probs is intentionally float64 in Python to avoid exact-zero
     # samples; cast to float32 here for C++ compatibility.
+    # Note: synthetic_conditional_rates and SYNTHETIC_MODE are passed by the
+    # rejection sampler for synthetic mode support, but are not yet implemented
+    # in the C++ CPU kernel. We accept them here to maintain compatibility with
+    # the kernel calling convention.
```
Comment (benchislett) [inline vllm/utils/cpu_triton_utils.py:254]:
```suggestion
    # the kernel calling convention.
    assert not SYNTHETIC_MODE, "Synthetic acceptance not supported with CPU sampling"
```

File: vllm/utils/cpu_triton_utils.py [hunk 2]
```diff
@@ -204,8 +204,15 @@ def _rejection_greedy_sample_kernel_impl(
...
     max_spec_len,
+    uniform_probs=None,
+    synthetic_conditional_rates=None,
+    SYNTHETIC_MODE=False,
 ):
     # C++ kernel expects int64 for all integer tensors.
+    # Note: uniform_probs, synthetic_conditional_rates, and SYNTHETIC_MODE are
+    # passed by the rejection sampler for synthetic mode support, but are not
+    # yet implemented in the C++ CPU kernel. We accept them here to maintain
+    # compatibility with the kernel calling convention.
```
Comment (benchislett) [inline vllm/utils/cpu_triton_utils.py:215]:
```suggestion
    # compatibility with the kernel calling convention.
    assert not SYNTHETIC_MODE, "Synthetic acceptance not supported with CPU sampling"
```

**Review by benchislett — APPROVED** [review]

**Comment by ganeshr10** [comment]
Thanks for the fix, @jmamou. Minimal signature change is the right approach -- keeps CPU/GPU calling conventions in sync. Synthetic mode in C++ kernels can come later if needed.
