### PR TITLE
[Misc] Update to Transformers 4.48

### PR DESCRIPTION
**Pull request by tlrmchlsmth**
Update Transformers to 4.48. Split off from https://github.com/vllm-project/vllm/pull/10909 to isolate any 4.48-related changes here and for easier debugging.

From @fabianlim, we have the following open issues:
 > * **Basic Correctness Test**: this somehow we are observing memory access [errors](https://buildkite.com/vllm/ci/builds/12029#01946bef-b936-44a1-93d5-e6bb700c904f/152-1088) with gemma probably related to [this](https://github.com/huggingface/transformers/issues/35711). (skip and wait for patch fix)?
 > * **Language Model Test**: this happens for a custom [model](https://buildkite.com/vllm/ci/builds/12029#01946bef-b94a-4e9a-a4d5-b278a0e395ab/200-1470), where in the remote code it imports something from transformers/pytorch_utils.py that is not there anymore (hard to fix since its not public code)
 > * **Multi GPU Test**: this one I cant really repro yet locally as im running into some ray troubles. But my guess its 4.48 related since it [passed](https://buildkite.com/vllm/ci/builds/11978#0194674e-7e74-4926-9728-c3b99ab898ba/176) before I upgrade the transformers, or its an intermittent error (is it possible to retrigger to test?)
 > * **Quantization Test**: this one I reproduced locally, it actually comes from this [PR](https://github.com/huggingface/transformers/pull/34719). Its happening on the ckpt neuralmagic/Llama-3.2-1B-quantized.w8a8, where quantization_config.quantization_status=="frozen" . In 4.47, it will need to come to this [line](https://github.com/huggingface/transformers/blob/99e0ab6ed888136ea4877c6d8ab03690a1478363/src/transformers/quantizers/quantizer_compressed_tensors.py#L79) to run as compressed, but in 4.48, the new logic will determine that because of the frozen tag, it is not compressed, and will skip to the other [line](https://github.com/huggingface/transformers/blob/99e0ab6ed888136ea4877c6d8ab03690a1478363/src/transformers/quantizers/quantizer_compressed_tensors.py#L81) .

### CODE REVIEW

**Comment by tlrmchlsmth** [comment]
FYI @mgoin, @dsikka, @robertgshaw2-redhat on the neuralmagic/Llama-3.2-1B-quantized.w8a8 issue

File: requirements-test.txt [hunk 1]
```diff
@@ -2,7 +2,7 @@
 # This file is autogenerated by pip-compile with Python 3.12
 # by the following command:
 #
-#    python3.12 -m piptools compile requirements-test.in -o requirements-test.txt
+#    pip-compile --output-file=requirements-test.txt requirements-test.in
```
Comment (DarkLight1337) [inline requirements-test.txt:5]: Please keep the original command as we want to keep this in Python 3.12 to maintain consistency.

**Comment by dsikka** [comment]
The transformers 4.48 release has the required change in how Automodel is expected to handle compressed vs frozen models. The model in question has the frozen state, which really should be compressed. 

I'll look into updating the model

File: requirements-test.txt (hunk 1 above)
Comment (fabianlim) [reply requirements-test.txt:5]: @DarkLight1337 yea this is what I got when I used py 3.12 and the following versions to generate compute with the same command

```
python3.12 -m piptools compile requirements-test.in -o requirements-test.txt -P transformers
```
but it comes out as what you see above, can you suggest what is the preferred way to compile?

versions:
```
build==1.2.2.post1
click==8.1.8
packaging==24.2
pip-tools==7.4.1
pyproject_hooks==1.2.0
setuptools==75.8.0
wheel==0.45.1
```

**Comment by dsikka** [comment]
> The custom model in question that is causing Language Model Test to fail is this one in particular. What can we do about this since this code is only modifiable but the its maintainers?.
> 
> ```
> [2025-01-15T23:58:08Z]     from transformers.modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast, SequenceClassifierOutputWithPast
> --
>   | [2025-01-15T23:58:08Z]     from transformers.modeling_utils import PreTrainedModel
>   | [2025-01-15T23:58:08Z] >   from transformers.pytorch_utils import ALL_LAYERNORM_LAYERS, is_torch_greater_or_equal_than_1_13
>   | [2025-01-15T23:58:08Z] E   ImportError: cannot import name 'is_torch_greater_or_equal_than_1_13' from 'transformers.pytorch_utils' (/usr/local/lib/python3.12/dist-packages/transformers/pytorch_utils.py)
>   | [2025-01-15T23:58:08Z]
>   | [2025-01-15T23:58:08Z] /root/.cache/huggingface/modules/transformers_modules/openbmb/MiniCPM3-4B/e5715484011d723a1892db91da8b59d979d14aee/modeling_minicpm.py:41: ImportError
> ```

The same issue has appeared in a few other models as a result of the release e.g Deepseek

File: requirements-test.txt (hunk 1 above)
Comment (tlrmchlsmth) [reply requirements-test.txt:5]: @DarkLight1337 I thought the same thing when I saw it in #10909, but when you run
```
python3.12 -m piptools compile requirements-test.in -o requirements-test.txt
```
it generates 
```
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile --output-file=requirements-test.txt requirements-test.in
```

You still think I should update the comment? I can definitely see a case for being explicit about python 3.12 in the command. If so I'll update the comment indicating that the command should be left as-is.

**Comment by tlrmchlsmth** [comment]
I put up a PR to fix those ch

> > The custom model in question that is causing Language Model Test to fail is this one in particular. What can we do about this since this code is only modifiable but the its maintainers?.
> > ```
> > [2025-01-15T23:58:08Z]     from transformers.modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast, SequenceClassifierOutputWithPast
> > --
> >   | [2025-01-15T23:58:08Z]     from transformers.modeling_utils import PreTrainedModel
> >   | [2025-01-15T23:58:08Z] >   from transformers.pytorch_utils import ALL_LAYERNORM_LAYERS, is_torch_greater_or_equal_than_1_13
> >   | [2025-01-15T23:58:08Z] E   ImportError: cannot import name 'is_torch_greater_or_equal_than_1_13' from 'transformers.pytorch_utils' (/usr/local/lib/python3.12/dist-packages/transformers/pytorch_utils.py)
> >   | [2025-01-15T23:58:08Z]
> >   | [2025-01-15T23:58:08Z] /root/.cache/huggingface/modules/transformers_modules/openbmb/MiniCPM3-4B/e5715484011d723a1892db91da8b59d979d14aee/modeling_minicpm.py:41: ImportError
> > ```
> 
> The same issue has appeared in a few other models as a result of the release e.g Deepseek

I have a PR up to fix it just  for MiniCMP here: https://huggingface.co/openbmb/MiniCPM3-4B/discussions/39

But alternatively if there are multiple models with the same issue, I think it would be better to fix via https://github.com/huggingface/transformers/pull/35734 -- @dsikka do you have links to other failing models?

**Comment by dsikka** [comment]
FYI the model has been updated and the tests now pass (at least locally)
@tlrmchlsmth @fabianlim

File: requirements-test.txt (hunk 1 above)
Comment (fabianlim) [reply requirements-test.txt:5]: yea it doesnt print the command that was actually run, it messages it to this format, which is actually consistent with the `pip-tools` docs

Comment (DarkLight1337) [reply requirements-test.txt:5]: cc @khluu since you made this change.

**Comment by tlrmchlsmth** [comment]
Added the ready label to see if the Multi GPU test is intermittent

**Comment by tlrmchlsmth** [comment]
[Looks like the multi gpu tests are passing](https://buildkite.com/vllm/ci/builds/12113#019476ca-3177-4b8f-9261-4383a1f56d5d) so we should be good to go once https://github.com/huggingface/transformers/pull/35681 lands. I'm inclined to wait for a transformers point release but lmk if you disagree

**Comment by fabianlim** [comment]
@tlrmchlsmth thanks! Im absolutely on board with waiting for the point release

File: requirements-test.txt [hunk 2]
```diff
@@ -533,6 +533,7 @@ tqdm==4.66.6
     #   lm-eval
     #   nltk
     #   peft
+    #   pqdm
     #   sentence-transformers
     #   tqdm-multiprocess
     #   transformers
```
Comment (DarkLight1337) [inline requirements-test.txt:539]: We should update `transformers` version in this file as well. Some of the resulting errors have been fixed in #12187

Comment (fabianlim) [reply requirements-test.txt:539]: @tlrmchlsmth ah yes, when you generate the file you need to pass the `-P` argument so that the `transformers` version get updated.

```
python3.12 -m piptools compile requirements-test.in -o requirements-test.txt -P transformers
```

**Comment by ani300** [comment]
https://github.com/huggingface/transformers/pull/35681 is now merged, so that's one less error as soon as they make a point release after it!

**Comment by noldorj** [comment]
It still happens in 
Torch version: 2.5.1+cu124
Transformers version: 4.48.1

File: requirements-test.txt (hunk 2 above)
Comment (hmellor) [reply requirements-test.txt:539]: Am I right in saying that if dependencies change in `requirements-{x}.txt`, they must be copied to `requirements-test.in` and then `pip-compile` must be run so that the built containers (which consume `requirements-dev.txt` which consumes `requirements-test.txt`) have updated requirements?

If yes, this seems very error prone.

Comment (tlrmchlsmth) [reply requirements-test.txt:539]: @hmellor This is my first time interacting with these but am inclined to agree

**Comment by ArthurZucker** [comment]
Patch release 4.48.2 is out btw !

File: requirements-test.txt (hunk 1 above)
Comment (tlrmchlsmth) [reply requirements-test.txt]: Reverted the command and added a comment to leave as-is

**Comment by fabianlim** [comment]
@tlrmchlsmth seems like few tests failed, its wierd because some of these tests (e.g., Open AI, TPU test) [passed before](https://buildkite.com/vllm/ci/builds/12029#01946bef-b990-40f6-aa39-e939e0014aa4) when I first tried to upgrade to 4.48 in my other PR #10909

**Comment by tlrmchlsmth** [comment]
The CI for TPUs is broken due to disks being full.

**Comment by DarkLight1337** [comment]
Closing as superseded by #12599
