### ISSUE TITLE
[CI Failure]: Flashinfer Kernel tests missing argument: 'num_logical_experts'

### ISSUE THREAD

**Issue by wzhao18** [vllm-project/vllm#34315]
### Name of failing test

tests/kernels/moe/test_flashinfer.py

### Basic information

- [ ] Flaky test
- [x] Can reproduce locally
- [ ] Caused by external libraries (e.g. bug in `transformers`)

### 🧪 Describe the failing test

Saw in CI - https://buildkite.com/vllm/ci/builds/51024/steps/canvas?jid=019c4ab1-5052-4272-80b7-00cbbea53a4e
```
>           moe_config = FusedMoEConfig(
--
num_experts=e,
experts_per_token=topk,
hidden_dim=k,
intermediate_size_per_partition=n,
num_local_experts=e,
activation=activation,
device="cuda",
moe_parallel_config=FusedMoEParallelConfig.make_no_parallel(),
in_dtype=torch.bfloat16,
is_act_and_mul=is_act_and_mul,
routing_method=RoutingMethodType.TopK,
)
E           TypeError: FusedMoEConfig.__init__() missing 1 required positional argument: 'num_logical_experts'
 
tests/kernels/moe/test_flashinfer.py:284: TypeError
```

### 📝 History of failing test

Seems like introduced in #32344, which was merged earlier today.
