### PR TITLE
[Bugfix][ROCm] Add record_logical_topk_ready to ROCMAiterMLASparseImpl (GLM-5.3-Flash boot crash)

### PR DESCRIPTION
**Pull request by mustafayildirim**
## Why this is not duplicating #56604

#56604 (open since 2026-09-12) fixes the same crash class by adding a **default no-op `record_logical_topk_ready` on the `MLAAttentionImpl` base class** in `vllm/v1/attention/backend.py`, so every backend silently inherits it.

This PR instead adds the method **on `ROCMAiterMLASparseImpl` itself**, mirroring the existing `SparseMLACommonImpl` contract (`vllm/model_executor/layers/attention/sparse_mla_attention.py:717`): impls that participate in sparse-MLA index groups implement the hook with real semantics; impls that don't declare an explicit no-op at their own site.

Trade-off: the base-class default in #56604 is broader (also covers any other backend that skips `SparseMLACommonImpl`) but weakens the interface — a new sparse backend that *should* implement index-group notification would silently no-op instead of failing loudly. This PR keeps that failure loud and fixes the one backend that currently crashes (ROCm AITER sparse MLA, GLM-5.3-Flash on MI350X). Either fix resolves the boot regression in #57248; happy to withdraw this in favor of #56604 if maintainers prefer the base-class default.

## Description

`MLAAttention.forward` calls `impl.record_logical_topk_ready()` on every sparse layer (`vllm/model_executor/layers/mla.py:235`). `ROCMAiterMLASparseImpl` inherits `SharedTopkIndicesBuffer` directly (not `SparseMLACommonImpl`) and never gained the method, so serving GLM-5.3-Flash on ROCm (gfx950, `ROCM_AITER_MLA_SPARSE`) crashes at the first forward with `AttributeError: 'ROCMAiterMLASparseImpl' object has no attribute 'record_logical_topk_ready'`.

This impl shares the top-k indices buffer via `SharedTopkIndicesBuffer` but does not participate in `SparseMLAIndexGroup` host-side prefetching, so the correct implementation is a no-op.

Fixes the first boot regression in #57248.

## Test commands run and results

- Reproduced on the cluster before the fix: nightly `af1c01499` on 8×MI350X TP8, engine dies at first forward with the AttributeError above.
- With the equivalent no-op method patched in-pod (same 5-line change), the model boots and serves; combined with `VLLM_USE_BREAKABLE_CUDAGRAPH=0` it passes the full chunked-prefill repro suite with zero faults (details in #57227).
- `python3 -c "import ast; ast.parse(...)"` — syntax OK; AST check confirms the method is now on the class.
- No GPU/ROCm environment is available in CI for the full path, so no new automated test is added here; #56604 already adds an interface-level test (`tests/v1/attention/test_sparse_mla_topk_ready_hook.py`) that covers this method's presence on backends.

## AI assistance

This PR was prepared with AI assistance (Hermes Agent). The change was reviewed and validated end-to-end on the affected hardware by the submitter: the same no-op patch was applied in-pod on the MI350X cluster and confirmed to resolve the crash.

### CODE REVIEW

**Comment by mustafayildirim** [comment]
## Unit tests + end-to-end validation of the fix on the affected hardware

Added unit tests for the fix (run on the actual ROCm nightly image, MI350X):

```
test_rocm_mla_topk_ready.py::test_method_exists PASSED
test_rocm_mla_topk_ready.py::test_method_is_no_arg_noop PASSED
test_rocm_mla_topk_ready.py::test_method_semantics_match_base_contract PASSED
test_rocm_mla_topk_ready.py::test_module_imports_without_aiter_gpu_errors PASSED
4 passed in 6.55s
```

`test_method_semantics_match_base_contract` asserts the no-op is *semantically equivalent* to `SparseMLACommonImpl.record_logical_topk_ready` for this impl: the base implementation only acts when an index group is registered (`if self.index_group is not None`), and `ROCMAiterMLASparseImpl` never registers one (it has no `set_logical_topk_ready` / index-group machinery — it shares the top-k buffer via `SharedTopkIndicesBuffer` only).

### End-to-end on 8×MI350X (nightly af1c01499 + this patch)

With this exact patch applied in-place, the engine boots (previously died at first forward with the AttributeError) and passes the full chunked-prefill repro twice, combined with `VLLM_USE_BREAKABLE_CUDAGRAPH=0` and `--kernel-config '{"enable_jit_warmup": false}'`:

- Ready with 57 FULL cudagraphs captured (FULL_AND_PIECEWISE active)
- `prefill-cold OK 10.3s` (20K-token prompt, 16K chunks)
- Mixed-phase + cached-decode phases OK
- **Memory access faults: 0**

**Comment by simondanielsson** [comment]
Thanks @mustafayildirim! I think this is the same fix as @Rohan138 suggested in a comment on that other PR: https://github.com/vllm-project/vllm/pull/56604#discussion_r4030104305

**Comment by Rohan138** [comment]
Hi @mustafayildirim thanks for the PR! Can you fix pre-commit, merge main and comment `/ci run`? Otherwise LGTM

**Review by dllehr-amd — APPROVED** [review]
Thanks @mustafayildirim  for fixing this!

**Review by AndreasKaratzas — APPROVED** [review]
