### PR TITLE
[Bugfix] Cap fastapi < 0.137 to avoid prometheus-fastapi-in strumentator crash on serve startup

### LINKED ISSUE #45596: [Bug]: vLLM 0.23.0 API server returns HTTP 500 on /v1/models due to prometheus_fastapi_instrumentator AttributeError: '_IncludedRouter' object has no attribute 'path'
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 24.04.4 LTS (x86_64)
GCC version                  : (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0
Clang version                : Could not collect
CMake version                : Could not collect
Libc version                 : glibc-2.39

==============================
       PyTorch Info
==============================
PyTorch version              : 2.11.0+cu130
Is debug build               : False
CUDA used to build PyTorch   : 13.0
ROCM used to build PyTorch   : N/A
XPU used to build PyTorch    : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.3 (main, Mar 23 2026, 19:04:32) [GCC 13.3.0] (64-bit runtime)
Python platform              : Linux-6.8.0-124-generic-x86_64-with-glibc2.39
    
==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 12.9.86
CUDA_MODULE_LOADING set to   : 
GPU models and configuration : 
GPU 0: NVIDIA RTX PRO 6000 Blackwell Server Edition
GPU 1: NVIDIA RTX PRO 6000 Blackwell Server Edition
GPU 2: NVIDIA RTX PRO 6000 Blackwell Server Edition
GPU 3: NVIDIA RTX PRO 6000 Blackwell Server Edition
GPU 4: NVIDIA RTX PRO 6000 Blackwell Server Edition

Nvidia driver version        : 580.159.04
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                            x86_64
CPU op-mode(s):                          32-bit, 64-bit
Address sizes:                           52 bits physical, 57 bits virtual
Byte Order:                              Little Endian
CPU(s):                                  128
On-line CPU(s) list:                     0-127
Vendor ID:                               AuthenticAMD
Model name:                              AMD EPYC 9355 32-Core Processor
CPU family:                              26
Model:                                   2
Thread(s) per core:                      2
Core(s) per socket:                      32
Socket(s):                               2
Stepping:                                1
Frequency boost:                         enabled
CPU(s) scaling MHz:                      45%
CPU max MHz:                             4413,2319
CPU min MHz:                             1500,0000
BogoMIPS:                                7089,46
Flags:                                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp ibrs_enhanced vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk avx_vnni avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc amd_ibpb_ret arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl vnmi avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid bus_lock_detect movdiri movdir64b overflow_recov succor smca fsrm avx512_vp2intersect flush_l1d debug_swap srso_user_kernel_no
Virtualization:                          AMD-V
L1d cache:                               3 MiB (64 instances)
L1i cache:                               2 MiB (64 instances)
L2 cache:                                64 MiB (64 instances)
L3 cache:                                512 MiB (16 instances)
NUMA node(s):                            2
NUMA node0 CPU(s):                       0-31,64-95
NUMA node1 CPU(s):                       32-63,96-127
Vulnerability Gather data sampling:      Not affected
Vulnerability Indirect target selection: Not affected
Vulnerability Itlb multihit:             Not affected
Vulnerability L1tf:                      Not affected
Vulnerability Mds:                       Not affected
Vulnerability Meltdown:                  Not affected
Vulnerability Mmio stale data:           Not affected
Vulnerability Reg file data sampling:    Not affected
Vulnerability Retbleed:                  Not affected
Vulnerability Spec rstack overflow:      Not affected
Vulnerability Spec store bypass:         Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:                Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:                Mitigation; Enhanced / Automatic IBRS; IBPB conditional; STIBP always-on; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                     Not affected
Vulnerability Tsa:                       Not affected
Vulnerability Tsx async abort:           Not affected
Vulnerability Vmscape:                   Not affected

==============================
Versions of relevant libraries
==============================
[pip3] flashinfer-python==0.6.12
[pip3] numpy==2.3.5
[pip3] nvidia-cublas==13.1.0.3
[pip3] nvidia-cuda-cccl==13.3.3.3.1
[pip3] nvidia-cuda-crt==13.3.33
[pip3] nvidia-cuda-cupti==13.0.85
[pip3] nvidia-cuda-nvcc==13.2.78
[pip3] nvidia-cuda-nvrtc==13.0.88
[pip3] nvidia-cuda-runtime==13.0.96
[pip3] nvidia-cuda-tileiras==13.2.78
[pip3] nvidia-cudnn-cu13==9.19.0.56
[pip3] nvidia-cudnn-frontend==1.25.0
[pip3] nvidia-cufft==12.0.0.61
[pip3] nvidia-cufile==1.15.1.6
[pip3] nvidia-curand==10.4.0.35
[pip3] nvidia-cusolver==12.0.4.66
[pip3] nvidia-cusparse==12.6.3.3
[pip3] nvidia-cusparselt-cu13==0.8.0
[pip3] nvidia-cutlass-dsl==4.5.2
[pip3] nvidia-cutlass-dsl-libs-base==4.5.2
[pip3] nvidia-cutlass-dsl-libs-cu13==4.5.2
[pip3] nvidia-ml-py==13.610.43
[pip3] nvidia-nccl-cu13==2.28.9
[pip3] nvidia-nvjitlink==13.0.88
[pip3] nvidia-nvshmem-cu13==3.4.5
[pip3] nvidia-nvtx==13.0.85
[pip3] nvidia-nvvm==13.2.78
[pip3] pyzmq==27.1.0
[pip3] tokenspeed-triton==3.7.10.post20260531
[pip3] torch==2.11.0+cu130
[pip3] torch_c_dlpack_ext==0.1.5
[pip3] torchaudio==2.11.0+cu130
[pip3] torchvision==0.26.0+cu130
[pip3] transformers==5.12.0
[pip3] triton==3.6.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.23.0
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled; XPU: Disabled
GPU Topology:
  	[4mGPU0	GPU1	GPU2	GPU3	GPU4	CPU Affinity	NUMA Affinity	GPU NUMA ID[0m
GPU0	 X 	PIX	NODE	NODE	SYS	0-31,64-95	0		N/A
GPU1	PIX	 X 	NODE	NODE	SYS	0-31,64-95	0		N/A
GPU2	NODE	NODE	 X 	PIX	SYS	0-31,64-95	0		N/A
GPU3	NODE	NODE	PIX	 X 	SYS	0-31,64-95	0		N/A
GPU4	SYS	SYS	SYS	SYS	 X 	32-63,96-127	1		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

==============================
     Environment Variables
==============================
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_userx
```

</details>

### 🐛 Describe the bug

After upgrading a working MiniMax-M2.5 deployment from vLLM 0.22.1 to vLLM 0.23.0, the vLLM engine starts successfully and the model appears to load correctly, but the OpenAI-compatible HTTP API is unusable.

The server reaches:

```text
Application startup complete
```

However, a readiness/API request to:

```bash
curl -v http://127.0.0.1:<PORT>/v1/models
```

returns:

```text
HTTP/1.1 500 Internal Server Error
```

The exception is raised in `prometheus_fastapi_instrumentator` while resolving the route name:

```text
AttributeError: '_IncludedRouter' object has no attribute 'path'
```

Relevant sanitized traceback excerpt:

```text
File ".../site-packages/prometheus_fastapi_instrumentator/middleware.py", line 131, in __call__
    handler, is_templated = self._get_handler(request)

File ".../site-packages/prometheus_fastapi_instrumentator/middleware.py", line 240, in _get_handler
    route_name = routing.get_route_name(request)

File ".../site-packages/prometheus_fastapi_instrumentator/routing.py", line 75, in get_route_name
    route_name = _get_route_name(scope, routes)

File ".../site-packages/prometheus_fastapi_instrumentator/routing.py", line 55, in _get_route_name
    route_name = route.path

AttributeError: '_IncludedRouter' object has no attribute 'path'
```

This happens after the vLLM engine has initialized successfully. The model itself seems healthy:

```text
vLLM version: 0.23.0
Resolved architecture: MiniMaxM2ForCausalLM
Model: MiniMaxAI/MiniMax-M2.5
Tensor parallel size: 4
Quantization: fp8
KV cache initialized successfully
Application startup complete
```

The issue appears to be in the FastAPI / Starlette / Prometheus instrumentation layer rather than in model loading or CUDA execution.

### Minimal reproduction

Start vLLM 0.23.0 with MiniMax-M2.5 using the OpenAI-compatible API server:

```bash
vllm serve /path/to/MiniMaxAI__MiniMax-M2.5 \
  --trust-remote-code \
  --tensor-parallel-size 4 \
  --host 0.0.0.0 \
  --port <PORT> \
  --max-model-len 163840 \
  --gpu-memory-utilization 0.95 \
  --max-num-seqs 8 \
  --disable-custom-all-reduce \
  --enable-auto-tool-choice \
  --tool-call-parser minimax_m2 \
  --reasoning-parser minimax_m2_append_think \
  --compilation-config '{"mode":3}' \
  --served-model-name MiniMaxAI/MiniMax-M2.5 \
  --max-num-batched-tokens 32768 \
  --kv-cache-dtype auto
```

Then call:

```bash
curl -v http://127.0.0.1:<PORT>/v1/models
```

### Expected behavior

`/v1/models` should return HTTP 200 with the served model metadata.

### Actual behavior

`/v1/models` returns HTTP 500, and the API server logs:

```text
AttributeError: '_IncludedRouter' object has no attribute 'path'
```

The error is raised from:

```text
prometheus_fastapi_instrumentator/routing.py
```

### Additional notes

The same deployment shape works with vLLM 0.22.1.

In vLLM 0.23.0, the engine side appears healthy: the model loads, CUDA graph warmup completes, FP8 is detected, and the server reaches `Application startup complete`. The failure happens only when the HTTP API is accessed.

This may be related to the vLLM 0.23.0 API server / router structure interacting with `prometheus-fastapi-instrumentator==8.0.0`, where the instrumentation code expects route objects to expose `.path`, but encounters an `_IncludedRouter`.

Sensitive values such as internal paths, hostnames, internal IPs, user names, and private endpoints have been redacted.

[minimax-m25-v9-v0230_20260614.log](https://github.com/user-attachments/files/28931838/minimax-m25-v9-v0230_20260614.log)

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by avesed**
A fresh pip install pulls fastapi 0.137, whose new _IncludedRouter route type (a BaseRoute with no .path) breaks prometheus-fastapi-instrumentator's route iteration -> 'vllm serve' dies at startup with:
  AttributeError: '_IncludedRouter' object has no attribute 'path'

requirements/common.txt pinned fastapi[standard]>=0.115.0 with no upper bound. Cap to <0.137; lift once the instrumentator handles _IncludedRouter (https://github.com/trallnag/prometheus-fastapi-instrumentator/issues/370).

fix #45596 #45597

### CODE REVIEW

**Comment by somera** [comment]
The manual patch is working for me #45596

File: requirements/common.txt [hunk 1]
```diff
@@ -11,7 +11,7 @@ transformers >= 5.5.3
 tokenizers >= 0.21.1  # Required for fast incremental detokenization.
 safetensors >= 0.6.2  # MXFP4/MXFP6 dtype support (F8_E8M0, F4) added in 0.6.0: https://github.com/huggingface/safetensors/pull/611
 protobuf >= 5.29.6, !=6.30.*, !=6.31.*, !=6.32.*, !=6.33.0.*, !=6.33.1.*, !=6.33.2.*, !=6.33.3.*, !=6.33.4.* # Required by LlamaTokenizer, gRPC. CVE-2026-0994
-fastapi[standard] >= 0.115.0 # Required by FastAPI's form models in the OpenAI API server's audio transcriptions endpoint.
+fastapi[standard] >= 0.115.0, < 0.137 # >=0.115.0 required by FastAPI's form models in the OpenAI API server's audio transcriptions endpoint. <0.137 because 0.137 added the _IncludedRouter route type (a BaseRoute with no `.path`) which breaks prometheus-fastapi-instrumentator's route iteration at `vllm serve` startup (https://github.com/trallnag/prometheus-fastapi-instrumentator/issues/370).
```
Comment (njhill) [inline requirements/common.txt]: Could you make the comment more concise. See the other comments in this file. It does not need to go into so many details.

**Review by njhill — COMMENTED** [review]
Thanks @avesed

**Comment by avesed** [comment]
@njhill Looks good now?

**Comment by bbrowning** [comment]
This fix is good to get builds from main fixed and future releases, but we'll also have to figure out how we want to handle all the prior releases that are now broken on fresh installs as well. At least in my testing, the new fastapi 0.137.0 is being picked up when installed released vLLM versions in a fresh venv.

**Review by njhill — APPROVED** [review]
Like @bbrowning said, lets get this in to at least alleviate new builds

**Comment by avesed** [comment]
@njhill Really sorry for the churn — I force-pushed once only to correct the commit author email (DCO/attribution). The actual change remains the same.

**Comment by noooop** [comment]
prefer #45629

**Comment by khluu** [comment]
I cherry picked this into release branch and we will patch v0.23.0 on pypi with the dependency pinned. Thanks!

**Comment by njhill** [comment]
Closing since this was already included in main
