### PR TITLE
[CI] Skip Phi-MoE test due to old API util

### PR DESCRIPTION
**Pull request by AndreasKaratzas**
This PR addresses test failures in the **Language Models Test (Extended Generation)** test group on ROCm by:

1. Skipping `test_phimoe.py` due to a known upstream issue
2. Documenting a dependency on an upstream mamba-ssm fix for ROCm 7.0+
3. Fixing NomicBert max_model_len validation regression from #28454

#### 1. Skip PhiMoE Tests

Skipped all tests in `tests/models/language/generation/test_phimoe.py` due to a known issue where `AttributeError: 'DynamicCache' object has no attribute 'seen_tokens'` is raised.

- **Upstream issue**: https://huggingface.co/microsoft/Phi-3.5-MoE-instruct/discussions/58
- **Affected test**: `test_phimoe.py::test_models[5-64-bfloat16-microsoft/Phi-3.5-MoE-instruct]`
- This issue is platform-agnostic

#### 2. Mamba Installation on ROCm 7.0+ (Awaiting Upstream Fix)

Mamba-ssm currently fails to build and run correctly on ROCm 7.0+. We are awaiting the merge of an upstream fix:

- **Upstream PR**: https://github.com/state-spaces/mamba/pull/831

Then we are also going to update the version of the package.

#### 3. Fix NomicBert max_model_len Validation

After #28454, cached `derived_max_model_len_and_key` wasn't updated when `NomicBertModelConfig` restricted `max_position_embeddings`, causing validation to use stale values. Affects both ROCm and CUDA.
- **Test**: `pytest -s -v models/language/pooling/test_nomic_max_model_len.py::test_set_max_model_len_illegal`

### CODE REVIEW

File: tests/models/language/generation/test_phimoe.py [hunk 1]
```diff
@@ -8,6 +8,21 @@
...
+# This issue is being investigated and tracked in:
+#   https://huggingface.co/microsoft/Phi-3.5-MoE-instruct/discussions/58
+# It is platform-agnostic. Therefore, we skip this test on all platforms for now.
+pytest.skip(
+    "Skipping due to known issue: "
+    "'DynamicCache' object has no attribute 'seen_tokens'. See: "
+    "https://huggingface.co/microsoft/Phi-3.5-MoE-instruct/discussions/58 "
+    "for details.",
+    allow_module_level=True,
+)
```
[the remark this answers is not in the document]
Comment (AndreasKaratzas) [reply tests/models/language/generation/test_phimoe.py]: Done :)

File: .buildkite/test-amd.yaml [hunk 2]
```diff
@@ -912,7 +912,7 @@ steps:
     # Note: also needed to run plamo2 model in vLLM
     - uv pip install --system --no-build-isolation 'git+https://github.com/state-spaces/mamba@v2.2.5'
     - uv pip install --system --no-build-isolation 'git+https://github.com/Dao-AILab/causal-conv1d@v1.5.2'
-    - pytest -v -s models/language/generation -m '(not core_model) and (not hybrid_model)'
+    - pytest -v -rs models/language/generation -m '(not core_model) and (not hybrid_model)'
```
Comment (DarkLight1337) [inline .buildkite/test-amd.yaml]: Revert this? I think you only used this for debugging

Comment (AndreasKaratzas) [reply .buildkite/test-amd.yaml]: @DarkLight1337 done :)

**Comment by AndreasKaratzas** [comment]
I also modified the `mamba` package installation path until the PR gets merged so that the test turns green. Having green CI is critical for AMD and I will monitor my PR at `mamba` upstream and revert this change as soon as it gets merged, like I did with the `xgrammar` upstream.

**Comment by AndreasKaratzas** [comment]
@charlotte12l @hmellor @heheda12345 

Could you please review my last commit?

After [#28454](https://github.com/vllm-project/vllm/pull/28454), `_get_and_verify_max_len` uses a cached `derived_max_model_len_and_key` value from `model_arch_config`. However, `NomicBertModelConfig.verify_and_update_config` updates `hf_text_config.max_position_embeddings` to `max_trained_positions` (2048) without updating the cached value (which remains 8192 from the original HF config).

This causes `max_model_len=4096` to incorrectly pass validation because `4096 < 8192`, when it should fail because `4096 > 2048`. With my last commit, I introduce an update of `model_arch_config.derived_max_model_len_and_key` when `NomicBertModelConfig` restricts the max position embeddings to `max_trained_positions`. To test, run:

`pytest -s -v models/language/pooling/test_nomic_max_model_len.py::test_set_max_model_len_illegal` now passes. Before, it was failing on both ROCm and CUDA.

**Comment by AndreasKaratzas** [comment]
@noooop I just removed the logic for Nordic. But please if you can have the PR that you are working on merged quickly because it is important for the AMD CI. We would like to have this test green. Let me know if I can help in any way :)

**Review by noooop — APPROVED** [review]
Thanks for the fix.

**Comment by charlotte12l** [comment]
@noooop I'm okay with keeping those logics in vllm/model_executor/models/config.py for now, but in such case, we still need to update `model_arch_config.hidden_size` and `model_arch_config.num_hidden_layers ` .

I agree to avoid splitting across different locations. I propose to consolidate those into convertor in the future if you are okay with it.

**Comment by noooop** [comment]
> @noooop I'm okay with keeping those logics in vllm/model_executor/models/config.py for now, but in such case, we still need to update `model_arch_config.hidden_size` and `model_arch_config.num_hidden_layers ` .
> 
> I agree to avoid splitting across different locations. I propose to consolidate those into convertor in the future if you are okay with it.

**Comment by AndreasKaratzas** [comment]
Give me some time for that cause I just switched off my PC 😅
> @AndreasKaratzas 
> 
> I'm very sorry. Please submit an empty commit or anything to restart the Read the Docs build.

**Comment by noooop** [comment]
Wait a second, it looks like the CI has already recovered automatically. You don't need to do anything.
