### PR TITLE
[ROCm]: W8A8BlockFp8LinearOp should use AITER on MI355X

### LINKED ISSUE #26700: [Bug][ROCm]: W8A8BlockFp8LinearOp does not use AITER on MI355X
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 22.04.5 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version                : 20.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-7.0.0 25314 f4087f6b428f0e6f575ebac8a8a724dab123d06e)
CMake version                : version 3.31.6
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.8.0+gitb2fb688
Is debug build               : False
CUDA used to build PyTorch   : N/A
ROCM used to build PyTorch   : 7.0.51831-a3e329ad8

==============================
      Python Environment
==============================
Python version               : 3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0] (64-bit runtime)
Python platform              : Linux-5.15.0-70-generic-x86_64-with-glibc2.35

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : Could not collect
CUDA_MODULE_LOADING set to   : LAZY
GPU models and configuration :  (gfx950:sramecc+:xnack-)
Nvidia driver version        : Could not collect
cuDNN version                : Could not collect
HIP runtime version          : 7.0.51831
MIOpen runtime version       : 3.5.0
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          256
On-line CPU(s) list:             0-255
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 9575F 64-Core Processor
CPU family:                      26
Model:                           2
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
Stepping:                        1
Frequency boost:                 enabled
CPU max MHz:                     5008.0068
CPU min MHz:                     1500.0000
BogoMIPS:                        6599.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx_vnni avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid bus_lock_detect movdiri movdir64b overflow_recov succor smca fsrm avx512_vp2intersect flush_l1d
Virtualization:                  AMD-V
L1d cache:                       6 MiB (128 instances)
L1i cache:                       4 MiB (128 instances)
L2 cache:                        128 MiB (128 instances)
L3 cache:                        512 MiB (16 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-63,128-191
NUMA node1 CPU(s):               64-127,192-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

==============================
Versions of relevant libraries
==============================
[pip3] conch-triton-kernels==1.2.1
[pip3] numpy==2.2.6
[pip3] pyzmq==27.1.0
[pip3] torch==2.8.0+gitb2fb688
[pip3] torchvision==0.23.0a0+824e8c8
[pip3] transformers==4.57.0
[pip3] triton==3.4.0
[pip3] triton_kernels==1.0.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : 7.0.51831-a3e329ad8
vLLM Version                 : 0.1.dev10235+ge8b5a2fcc (git sha: e8b5a2fcc)
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled
GPU Topology:
  ============================ ROCm System Management Interface ============================
================================ Weight between two GPUs =================================
       GPU0         GPU1         GPU2         GPU3         GPU4         GPU5         GPU6         GPU7
GPU0   0            15           15           15           15           15           15           15
GPU1   15           0            15           15           15           15           15           15
GPU2   15           15           0            15           15           15           15           15
GPU3   15           15           15           0            15           15           15           15
GPU4   15           15           15           15           0            15           15           15
GPU5   15           15           15           15           15           0            15           15
GPU6   15           15           15           15           15           15           0            15
GPU7   15           15           15           15           15           15           15           0

================================= Hops between two GPUs ==================================
       GPU0         GPU1         GPU2         GPU3         GPU4         GPU5         GPU6         GPU7
GPU0   0            1            1            1            1            1            1            1
GPU1   1            0            1            1            1            1            1            1
GPU2   1            1            0            1            1            1            1            1
GPU3   1            1            1            0            1            1            1            1
GPU4   1            1            1            1            0            1            1            1
GPU5   1            1            1            1            1            0            1            1
GPU6   1            1            1            1            1            1            0            1
GPU7   1            1            1            1            1            1            1            0

=============================== Link Type between two GPUs ===============================
       GPU0         GPU1         GPU2         GPU3         GPU4         GPU5         GPU6         GPU7
GPU0   0            XGMI         XGMI         XGMI         XGMI         XGMI         XGMI         XGMI
GPU1   XGMI         0            XGMI         XGMI         XGMI         XGMI         XGMI         XGMI
GPU2   XGMI         XGMI         0            XGMI         XGMI         XGMI         XGMI         XGMI
GPU3   XGMI         XGMI         XGMI         0            XGMI         XGMI         XGMI         XGMI
GPU4   XGMI         XGMI         XGMI         XGMI         0            XGMI         XGMI         XGMI
GPU5   XGMI         XGMI         XGMI         XGMI         XGMI         0            XGMI         XGMI
GPU6   XGMI         XGMI         XGMI         XGMI         XGMI         XGMI         0            XGMI
GPU7   XGMI         XGMI         XGMI         XGMI         XGMI         XGMI         XGMI         0

======================================= Numa Nodes =======================================
GPU[0]          : (Topology) Numa Node: 0
GPU[0]          : (Topology) Numa Affinity: 0
GPU[1]          : (Topology) Numa Node: 0
GPU[1]          : (Topology) Numa Affinity: 0
GPU[2]          : (Topology) Numa Node: 0
GPU[2]          : (Topology) Numa Affinity: 0
GPU[3]          : (Topology) Numa Node: 0
GPU[3]          : (Topology) Numa Affinity: 0
GPU[4]          : (Topology) Numa Node: 1
GPU[4]          : (Topology) Numa Affinity: 1
GPU[5]          : (Topology) Numa Node: 1
GPU[5]          : (Topology) Numa Affinity: 1
GPU[6]          : (Topology) Numa Node: 1
GPU[6]          : (Topology) Numa Affinity: 1
GPU[7]          : (Topology) Numa Node: 1
GPU[7]          : (Topology) Numa Affinity: 1
================================== End of ROCm SMI Log ===================================

==============================
     Environment Variables
==============================
PYTORCH_TUNABLEOP_TUNING=0
VLLM_ROCM_USE_AITER_MHA=1
PYTORCH_TUNABLEOP_ENABLED=1
VLLM_V1_USE_PREFILL_DECODE_ATTENTION=1
VLLM_ROCM_QUICK_REDUCE_QUANTIZATION=FP
VLLM_ROCM_USE_AITER=1
PYTORCH_ROCM_ARCH=gfx942;gfx950
LD_LIBRARY_PATH=/opt/rocm/lib:/usr/local/lib:
VLLM_USE_TRITON_FLASH_ATTN=0
PYTORCH_TUNABLEOP_FILENAME=/app/afo_tune_device_%d_full.csv
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

</details>

### 🐛 Describe the bug

On MI355X, `W8A8BlockFp8LinearOp` chooses the fallback branch `_run_triton` instead of the more performant branch `_run_aiter`. This results in suboptimal performance.

## Root cause

Incorrect use of the `is_fp8_fnuz` condition.
The `is_fp8_fnuz` condition should only be used to check if FP8 indeed uses the FP8-FNUZ (Finite and NaN Only) format. It should not be used as generic condition to disable kernels on platforms older than MI300X.
MI355X does not use the FP8-FNUZ format, and thus `is_fp8_fnuz` returns False.
https://rocm.docs.amd.com/projects/HIP/en/latest/reference/low_fp_types.html#fp8-quarter-precision

The issue was introduced in PR #21242 commit [e626d28](https://github.com/vllm-project/vllm/commit/e626d286f5ac997bca5bd635c3db9e457fe91df9)
vllm/model_executor/layers/quantization/utils/fp8_utils.py line 86

## Proposed fix

Each kernel (ar at least each group of associated kernels) should have its own list of supported archs, making it straightforward to enable a kernel on new archs without affecting other code. It is not acceptable to make  `is_fp8_fnuz` return True on MI355X, as that would cause incorrect normalization and scaling of FP8.

```python
gcn_arch = torch.cuda.get_device_properties(0).gcnArchName
supported_archs = ["gfx94", "gfx95"]
return any(gfx in gcn_arch for gfx in supported_archs)
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by gronsti-amd**
## Purpose

Closes: #26700

On MI355X, `W8A8BlockFp8LinearOp` chooses the fallback branch `_run_triton` instead of the more performant branch `_run_aiter`. This results in suboptimal performance.

### Root cause

Incorrect use of the `is_fp8_fnuz` condition.
The `is_fp8_fnuz` condition should only be used to check if FP8 indeed uses the FP8-FNUZ (Finite and NaN Only) format. It should not be used as generic condition to disable kernels on platforms older than MI300X.
MI355X does not use the FP8-FNUZ format, and thus `is_fp8_fnuz` returns False.
https://rocm.docs.amd.com/projects/HIP/en/latest/reference/low_fp_types.html#fp8-quarter-precision

The issue was introduced in PR #21242 commit [e626d28](https://github.com/vllm-project/vllm/commit/                                  e626d286f5ac997bca5bd635c3db9e457fe91df9)
vllm/model_executor/layers/quantization/utils/fp8_utils.py line 86

## Implementation details

- Replaces use of `is_fp8_fnuz` with explicit architecture check.
- When the aiter code branch is enabled, a secondary issue is triggered: Torch Dynamo attempts to compile the AITER JIT wrapper, crashing with `Explanation: Dynamo does not know how to trace method __contains__  of class frozenset`. To prevent dynamo from trying to compile it, we register the aiter JIT:ed op `rocm_aiter_per1x128_quant` using `direct_register_custom_op`.
- Avoid using `functools.partial`, because direct_register_custom_op attempts to infer schema, leading to `AttributeError: 'functools.partial' object has no attribute '__globals__'`
- Rename `aiter_per1x128_quant` to `rocm_aiter_per1x128_quant` for consistency.
- Rename the kernel selection check `check_aiter_fp8_linear_support` to `use_aiter_fp8_linear`. The function checks whether FP8 is both supported and enabled by env flags. Renaming distinguishes from `current_platform.supports_aiter_w8a8_block_fp8_linear`  which only checks for support but does not check the env flags.

## Test Plan

```
export HIP_VISIBLE_DEVICES=0

export VLLM_ROCM_QUICK_REDUCE_QUANTIZATION=FP
export VLLM_V1_USE_PREFILL_DECODE_ATTENTION=1
export VLLM_USE_TRITON_FLASH_ATTN=0
export VLLM_ROCM_USE_AITER=1
export VLLM_ROCM_USE_AITER_MHA=1
export SAFETENSORS_FAST_GPU=1

vllm serve --no-enable-prefix-caching -tp 1 "Qwen/Qwen3-30B-A3B-Instruct-2507-FP8"
```

## Test Result

|    |   input_seq_length |   output_seq_length |   max_concurrency |   tensor_parallel | device   |   ('mean_e2el_ms', 'baseline') |   ('mean_e2el_ms', 'fix-fnuz') |   ('mean_itl_ms', 'baseline') |   ('mean_itl_ms', 'fix-fnuz') |   ('mean_tpot_ms', 'baseline') |   ('mean_tpot_ms', 'fix-fnuz') |   ('mean_ttft_ms', 'baseline') |   ('mean_ttft_ms', 'fix-fnuz') |   ('output_throughput', 'baseline') |   ('output_throughput', 'fix-fnuz') |
|---:|---------------------------:|----------------------------:|--------------------------:|--------------------------:|:-----------------|-------------------------------:|-------------------------------:|------------------------------:|------------------------------:|-------------------------------:|-------------------------------:|-------------------------------:|-------------------------------:|------------------------------------:|------------------------------------:|
|  0 |                       1000 |                         500 |                         1 |                         1 | MI355X           |                        4291.45 |                        3631.47 |                       7.74421 |                       6.54753 |                        7.74757 |                        6.55164 |                        39.3975 |                        36.4627 |                             128.168 |                             151.46  |
|  1 |                       1000 |                         500 |                         4 |                         1 | MI355X           |                        4631.57 |                        3911.22 |                       9.30521 |                       7.85047 |                        9.31005 |                        7.85374 |                        51.3681 |                        47.0733 |                             405.734 |                             480.557 |
|  2 |                       1000 |                         500 |                         8 |                         1 | MI355X           |                        5144.99 |                        4407.81 |                       9.95725 |                       8.52531 |                        9.9824  |                        8.54841 |                        54.6616 |                        49.5116 |                             723.618 |                             845.489 |
|  3 |                       1000 |                         500 |                        16 |                         1 | MI355X           |                        5982.12 |                        4949.31 |                      10.8214  |                       8.93642 |                       10.9008  |                        8.99791 |                        77.0072 |                        72.8162 |                            1322.58  |                            1596.36  |
|  4 |                       1000 |                         500 |                        32 |                         1 | MI355X           |                        6999.54 |                        5936.8  |                      12.9079  |                      10.9287  |                       12.9849  |                       10.9916  |                       142.539  |                       131.182  |                            2042.66  |                            2410.07  |
|  5 |                       1000 |                         500 |                        64 |                         1 | MI355X           |                        9123.87 |                        8111.46 |                      17.1726  |                      15.231   |                       17.7794  |                       15.763   |                       192.252  |                       189.664  |                            3154.04  |                            3566.56  |
|  6 |                       1000 |                         500 |                       128 |                         1 | MI355X           |                       13427.6  |                       12387.1  |                      25.854   |                      23.8544  |                       27.1634  |                       25.0466  |                       449.528  |                       412.507  |                            4081.78  |                            4455.09  |
|  7 |                      10000 |                        1000 |                         1 |                         1 | MI355X           |                        8997.24 |                        7713.68 |                       7.93931 |                       6.77895 |                        7.93079 |                        6.7713  |                       273.915  |                       265.307  |                             122.228 |                             142.566 |
|  8 |                      10000 |                        1000 |                         4 |                         1 | MI355X           |                       10680.6  |                        9223.76 |                      10.4663  |                       8.99885 |                       10.4429  |                        8.96562 |                       376.494  |                       365.231  |                             353.429 |                             409.812 |
|  9 |                      10000 |                        1000 |                         8 |                         1 | MI355X           |                       13416.7  |                       11882.2  |                      12.7211  |                      11.2308  |                       12.7905  |                       11.2978  |                       405.996  |                       395.786  |                             563.347 |                             637.685 |
| 10 |                      10000 |                        1000 |                        16 |                         1 | MI355X           |                       19008.1  |                       16842.2  |                      16.8767  |                      14.9087  |                       17.6137  |                       15.5733  |                       585.094  |                       565.107  |                             854.97  |                             967.078 |
| 11 |                      10000 |                        1000 |                        32 |                         1 | MI355X           |                       28084.1  |                       25756.5  |                      25.3686  |                      23.1897  |                       26.3407  |                       24.0103  |                      1138.13   |                      1113.81   |                            1090.52  |                            1196.1   |
| 12 |                      10000 |                        1000 |                        64 |                         1 | MI355X           |                       44788    |                       42010.9  |                      41.2436  |                      38.5243  |                       45.8095  |                       42.4373  |                      1864.18   |                      1917.11   |                            1373.15  |                            1471.11  |
| 13 |                      10000 |                        1000 |                       128 |                         1 | MI355X           |                       77734.9  |                       74216.8  |                      72.6504  |                      69.3913  |                       80.5413  |                       76.9592  |                      4759.14   |                      4514.68   |                            1520.69  |                            1599.34  |
---
<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [X] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [X] The test plan, such as providing test command.
- [x] The test results, such as pasting the results comparison before and after, or e2e results
- [ ] (Optional) The necessary documentation update, such as updating `supported_models.md` and `examples` for a new model.
- [ ] (Optional) Release notes update. If your change is user facing, please update the release notes draft in the [Google Doc](https://docs.google.com/document/d/1YyVqrgX4gHTtrstbq8oWUImOyPCKSGnJ7xtTpmXzlRs/edit?tab=t.0).
</details>

### CODE REVIEW

File: vllm/platforms/rocm.py [hunk 1]
```diff
@@ -455,7 +455,14 @@ def fp8_dtype(cls) -> torch.dtype:
...
+        gcn_arch = torch.cuda.get_device_properties(0).gcnArchName
+        supported_archs = ["gfx94", "gfx95"]
+        return any(gfx in gcn_arch for gfx in supported_archs)
+
+    @classmethod
+    def supports_aiter_w8a8_block_fp8_linear(cls) -> bool:
+        # Enable for MI300 and MI350 series
         gcn_arch = torch.cuda.get_device_properties(0).gcnArchName
         supported_archs = ["gfx94", "gfx95"]
         return any(gfx in gcn_arch for gfx in supported_archs)
```
[the remark this answers is not in the document]
Comment (gronsti-amd) [reply vllm/platforms/rocm.py:487]: Resolved in 07ccfb3637528ab824f4c578b5be03fb0d2180bd

**Review by SageMoore — APPROVED** [review]
Looks reasonable. Thanks for the contribution!

**Review by gshtras — APPROVED** [review]
