### PR TITLE
 [ModelScope] Support latest get_model_files AP

### PR DESCRIPTION
**Pull request by zihaomu**
## Summary

  Fix ModelScope repo file listing with newer `modelscope` releases.

  `modelscope==1.38.0` changed `HubApi.get_model_files()` so it no longer accepts the `revision` keyword argument, and its returned
  file entries may not include the older `Type` field. vLLM currently calls `get_model_files(model_id=..., revision=...,
  recursive=True)`, which causes `test_model_from_modelscope` to fail after `pip install modelscope` installs the latest release.

  This patch makes `modelscope_list_repo_files()` compatible with both API shapes:

  - older ModelScope versions that support `revision`
  - newer ModelScope versions whose `get_model_files()` only accepts `model_id` and `recursive`
  - newer returned entries without a `Type` field

  For newer ModelScope versions, non-`None` `revision` is rejected with a clear error instead of being silently ignored.

  ## Testing

  ```bash
  pre-commit run --hook-stage manual --files \
    vllm/transformers_utils/utils.py \
    tests/transformers_utils/test_utils.py

  python -m pytest -p no:cacheprovider \
    tests/transformers_utils/test_utils.py -q
```
  Manual compatibility checks:
```
  modelscope==1.38.0: modelscope_list_repo_files("qwen/Qwen1.5-0.5B-Chat") returns config.json
  modelscope==1.35.3: modelscope_list_repo_files("qwen/Qwen1.5-0.5B-Chat", revision="master") returns config.json
```
  ## Notes

  This addresses the regression failure:
```
  TypeError: LegacyHubApi.get_model_files() got an unexpected keyword argument 'revision
```

---
<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [ ] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [ ] The test plan, such as providing test command.
- [ ] The test results, such as pasting the results comparison before and after, or e2e results
- [ ] (Optional) The necessary documentation update, such as updating `supported_models.md` and `examples` for a new model.
</details>

### CODE REVIEW

**Review by AndreasKaratzas — COMMENTED** [review]
Tbh I find this a bit too hacky .. not sure if I'm the best person to review this ..

**Comment by zihaomu** [comment]
Closing this for now since the CI failure that motivated this PR was resolved after rebasing #47404 onto latest main. This
  ModelScope compatibility issue may still be worth addressing separately, but the current approach likely needs a cleaner design, so
  I don't want to keep this open as a blocker or distraction.
