### PR TITLE
[VLM] Fix paligemma, fuyu and persimmon with transformers 4.45 : use config.text_config.vocab_size

### PR DESCRIPTION
**Pull request by janimo**
In the latest transformers (4.45.0.dev0) the config.vocab_size accessor and  _vocab_size field in the config were removed from a few models.

https://github.com/huggingface/transformers/pull/33446

Running examples/offline_inference_vision_language.py results in an error

`AttributeError: 'PaliGemmaConfig' object has no attribute 'vocab_size'. Did you mean: '_vocab_size'?`

This changes the code to use config.text_config.vocab_size instead of config.vocab_size in paligemma, fuyu and persimmon.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Looks like the HF repos of those models still haven't updated their configs to work with transformers 4.45:

- Fuyu-8B: https://huggingface.co/adept/fuyu-8b/blob/main/config.json
- Persimmon-8B: https://huggingface.co/adept/persimmon-8b-base/blob/main/config.json
- PaliGemma-3B: https://huggingface.co/google/paligemma-3b-pt-224/blob/main/config.json

**Comment by janimo** [comment]
The paligemma config.json has vocab_size inside both as a top level config field and inside text_config so it should be good.

Fuyu seems to initialize text_config as a persimmon model:
https://github.com/huggingface/transformers/blob/78b2929c0554b79e0489b451ce4ece14d265ead2/src/transformers/models/fuyu/configuration_fuyu.py#L157
so its text_config will be a persimmon LLM config with a vocab_size inside it.

And Persimmon is a LLM not VLM so its config should be fine with just vocab_size at the top level ?

Anyway all changes I made were based on running the examples/offline_inference_vision_language.py scripts for paligemma and fuyu against transformers built from main. The fuyu test needed changes both to fuyu and its dependency persimmon.

**Comment by DarkLight1337** [comment]
Thanks for the explanation, you are right. Let me run the tests to be sure.

**Comment by janimo** [comment]
@DarkLight1337 thank you for the review, I will check the test. Is that the script I mentioned above or some other test?

**Comment by DarkLight1337** [comment]
You can check the logs [here](https://buildkite.com/vllm/fastcheck/builds/4653#01921977-73f0-4b48-91aa-42245324c2d9). It seems to be erroring out on the tokenizer config rather than model config.

**Comment by janimo** [comment]
With the patches applied, manually running pytest test_fuyu.py with transformers 4.44.2 installed passes here (same with 4.45.0.dev0)

Without the patch the test fails on 4.45 and passes on 4.44 but warns about deprecating vocab_size.

I wonder if running pytest manually is different from how fastcheck/CI is set up.

**Comment by DarkLight1337** [comment]
> With the patches applied, manually running pytest test_fuyu.py with transformers 4.44.2 installed passes here (same with 4.45.0.dev0)
> 
> Without the patch the test fails on 4.45 and passes on 4.44 but warns about deprecating vocab_size.
> 
> I wonder if running pytest manually is different from how fastcheck/CI is set up.

Based on this, I guess this patch is not backwards compatible. Since our CI installs vLLM according to its listed dependencies (i.e. transformers v4.44), it is expected that the tests will fail in this case. I suggest you modify this patch so that it works for both versions.

**Comment by janimo** [comment]
From the manual running of the test it looks it is backwards compatible since it works with both 4.44 and 4.45 (only 4.45 fails when unpatched).
I have rebased on main and it seems the decoder-only-multimodal-test passes, the one that was red before.
https://buildkite.com/vllm/fastcheck/builds/4689

I am not sure what the error was with the previous build since only 1 of 4 fuyu tests failed and without a conclusive error message.

**Comment by DarkLight1337** [comment]
> From the manual running of the test it looks it is backwards compatible since it works with both 4.44 and 4.45 (only 4.45 fails when unpatched). I have rebased on main and it seems the decoder-only-multimodal-test passes, the one that was red before. https://buildkite.com/vllm/fastcheck/builds/4689
> 
> I am not sure what the error was with the previous build since only 1 of 4 fuyu tests failed and without a conclusive error message.

I just ran the tests locally and they passed for both v4.44 and v4.45 as well. Maybe that was just a connection error...

**Review by DarkLight1337 — APPROVED** [review]
In that case, let's merge this. Thanks for your patience, sorry for causing any confusion!

**Comment by janimo** [comment]
Thanks for your review, and I am glad that there is such attention to detail and making sure nothing breaks!
