### ISSUE TITLE
[Installation]:  Could not find a version that satisfies the requirement xgrammar>=0.1.6; platform_machine == "x86_64" (from vllm) (from versions: none)

### ISSUE THREAD

**Issue by Xingkangze** [vllm-project/vllm#11886]
### Your current environment

```text
 # 创建环境
 conda create -n online_model_v4  python=3.10.13
 
 # 激活环境
 conda activate online_model_v4


pip install vllm==0.6.6.post1


```

### How you are installing vllm

```sh
pip install vllm==0.6.6.post1




问题
Collecting prometheus-fastapi-instrumentator>=7.0.0 (from vllm==0.6.6.post1)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/59/66/2e93a8f56adb51ede41d0ef5f4f0277522acc4adc87937f5457b7b5692a8/prometheus_fastapi_instrumentator-7.0.0-py3-none-any.whl (19 kB)
Collecting tiktoken>=0.6.0 (from vllm==0.6.6.post1)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2e/28/cf3633018cbcc6deb7805b700ccd6085c9a5a7f72b38974ee0bffd56d311/tiktoken-0.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
Collecting lm-format-enforcer<0.11,>=0.10.9 (from vllm==0.6.6.post1)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c1/01/e78fdf09de2b4e7750a402eaa4f6783c7215ededd4bc6fe4a3f6d69c49da/lm_format_enforcer-0.10.9-py3-none-any.whl (43 kB)
Collecting outlines==0.1.11 (from vllm==0.6.6.post1)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/13/b4/99ea4a122bef60e3fd6402d19665aff1f928e0daf8fac3044d0b73f72003/outlines-0.1.11-py3-none-any.whl (87 kB)
Collecting lark==1.2.2 (from vllm==0.6.6.post1)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2d/00/d90b10b962b4277f5e64a78b6609968859ff86889f5b898c1a778c06ec00/lark-1.2.2-py3-none-any.whl (111 kB)
INFO: pip is looking at multiple versions of vllm to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement xgrammar>=0.1.6; platform_machine == "x86_64" (from vllm) (from versions: none)
ERROR: No matching distribution found for xgrammar>=0.1.6; platform_machine == "x86_64"
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by VegetaPn** [comment]
+1

**Comment by suxuanning** [comment]
+1

**Comment by DarkLight1337** [comment]
cc @russellb

**Comment by russellb** [comment]
I wonder if it's an issue with this pypi mirror in China? xgrammar is up to 0.1.9 here: https://pypi.org/project/xgrammar/#history

**Comment by Li-Qingyun** [comment]
> I wonder if it's an issue with this pypi mirror in China? xgrammar is up to 0.1.9 here: https://pypi.org/project/xgrammar/#history

yes maybe,

but i tried 

pip install xgrammar --index-url https://pypi.org/simple

also does not work

**Comment by Li-Qingyun** [comment]
This issue work

https://github.com/vllm-project/vllm/issues/11542

upgrade your glibc is all required.

**Comment by russellb** [comment]
@Xingkangze can you confirm that you were able to get it working?

**Comment by Li-Qingyun** [comment]
@russellb I think it is. My cluster server got a lower version of glibc (<2). 
All the wheel for xgrammar [here](https://pypi.org/project/xgrammar/#files) are built with glibc>2.27.
I downloaded the wheel with wget and pip install the wheel, `ERROR: xgrammar-0.1.9-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl is not a supported wheel on this platform.` The platform is only mismatched on glibc version.
I patched my interpreter with patchelf on glibc 2.27 (because sudo/root is not available) and then just `pip install xgrammar`, it worked.
Hence, the installation error seems not from the f**king internet ''wall'' of china, but a mismatched version of glibc.

**Comment by Xingkangze** [comment]
@russellb I cannot upgrade to the glibc version, so it cannot work

**Comment by Li-Qingyun** [comment]
> [@russellb](https://github.com/russellb) I cannot upgrade to the glibc version, so it cannot work

The glibc in your enviroment have to be newer. The root/sudo is also not available to me. 

You are recommand to use patchelf to match your python interpreter with glibc 2.27.

Or you can also prepare your enviroment with docker.

**Comment by Li-Qingyun** [comment]
@russellb It can also be resolved by the release of xgrammar, if there will be wheels that will be build with glibc<2.0

**Comment by eduardzl** [comment]
Also not working for me on Amazon Linux 2. Trying to install vLLM 0.6.6.post1
The latest version of glibc available is 2.26.
When trying to compile glibc 2.29 from source, I am getting error that "make" is too old.

**Comment by russellb** [comment]
have you tried building xgrammar yourself instead of installing a wheel to see if you can build a version compatible with your environment?

**Comment by eduardzl** [comment]
Errror when compiling xgrammar.
`[11/30] Building CXX object CMakeFiles/xgrammar.dir/cpp/grammar_matcher_base.cc.o
FAILED: CMakeFiles/xgrammar.dir/cpp/grammar_matcher_base.cc.o
/usr/bin/c++  -I/home/ec2-user/SageMaker/vllm/xgrammar/3rdparty/picojson -I/home/ec2-user/SageMaker/vllm/xgrammar/3rdparty/dlpack/include -I/home/ec2-user/SageMaker/vllm/xgrammar/include -Wall -Wextra -Werror -Wno-pedantic -Wno-unused-parameter -Woverloaded-virtual -flto=auto -Ofast  -O2 -g -DNDEBUG -std=gnu++1z -fPIC -MD -MT CMakeFiles/xgrammar.dir/cpp/grammar_matcher_base.cc.o -MF CMakeFiles/xgrammar.dir/cpp/grammar_matcher_base.cc.o.d -o CMakeFiles/xgrammar.dir/cpp/grammar_matcher_base.cc.o -c /home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc
/home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc: In member function ‘bool xgrammar::GrammarMatcherBase::CheckIfAccepted(const xgrammar::StackElement&, uint8_t) const’:
/home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc:30:41: error: unused variable ‘codepoint’ [-Werror=unused-variable]
     auto [accepted, num_bytes, codepoint] = HandleUTF8FirstByte(char_value);
                                         ^
/home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc: In member function ‘xgrammar::StackElement xgrammar::GrammarMatcherBase::AdvanceStackElementWithChar(const xgrammar::StackElement&, uint8_t)’:
/home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc:79:43: error: unused variable ‘codepoint’ [-Werror=unused-variable]
       auto [accepted, num_bytes, codepoint] = HandleUTF8FirstByte(char_value);
                                           ^
/home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc:92:45: error: unused variable ‘codepoint’ [-Werror=unused-variable]
         auto [accepted, num_bytes, codepoint] = HandleUTF8FirstByte(char_value);
                                             ^
cc1plus: all warnings being treated as errors
[12/30] Building CXX object cpp/pybind/CMakeFiles/xgrammar_bindings.dir/__/grammar_matcher_base.cc.o
FAILED: cpp/pybind/CMakeFiles/xgrammar_bindings.dir/__/grammar_matcher_base.cc.o
/usr/bin/c++ -Dxgrammar_bindings_EXPORTS -I/home/ec2-user/SageMaker/vllm/xgrammar/3rdparty/picojson -I/home/ec2-user/SageMaker/vllm/xgrammar/3rdparty/dlpack/include -I/home/ec2-user/SageMaker/vllm/xgrammar/include -isystem /home/ec2-user/SageMaker/envs/conda_vllm_xgrammar/include/python3.10 -isystem /home/ec2-user/SageMaker/envs/conda_vllm_xgrammar/lib/python3.10/site-packages/pybind11/include -Wall -Wextra -Werror -Wno-pedantic -Wno-unused-parameter -Woverloaded-virtual -flto=auto -Ofast  -O2 -g -DNDEBUG -std=gnu++1z -fPIC -fvisibility=hidden -MD -MT cpp/pybind/CMakeFiles/xgrammar_bindings.dir/__/grammar_matcher_base.cc.o -MF cpp/pybind/CMakeFiles/xgrammar_bindings.dir/__/grammar_matcher_base.cc.o.d -o cpp/pybind/CMakeFiles/xgrammar_bindings.dir/__/grammar_matcher_base.cc.o -c /home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc
/home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc: In member function ‘bool xgrammar::GrammarMatcherBase::CheckIfAccepted(const xgrammar::StackElement&, uint8_t) const’:
/home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc:30:41: error: unused variable ‘codepoint’ [-Werror=unused-variable]
     auto [accepted, num_bytes, codepoint] = HandleUTF8FirstByte(char_value);
                                         ^
/home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc: In member function ‘xgrammar::StackElement xgrammar::GrammarMatcherBase::AdvanceStackElementWithChar(const xgrammar::StackElement&, uint8_t)’:
/home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc:79:43: error: unused variable ‘codepoint’ [-Werror=unused-variable]
       auto [accepted, num_bytes, codepoint] = HandleUTF8FirstByte(char_value);
                                           ^
/home/ec2-user/SageMaker/vllm/xgrammar/cpp/grammar_matcher_base.cc:92:45: error: unused variable ‘codepoint’ [-Werror=unused-variable]
         auto [accepted, num_bytes, codepoint] = HandleUTF8FirstByte(char_value);
                                             ^
cc1plus: all warnings being treated as errors
[28/30] Building CXX object cpp/pybind/CMakeFiles/xgrammar_bindings.dir/pybind.cc.o`

**Comment by hediyuan** [comment]
+1
i try to build xgrammar instead of whl，but it requires higher versions of cmake and gcc

**Comment by Li-Qingyun** [comment]
+1 , build xgrammar from source also does not work for me.

**Comment by pengwenzhi** [comment]
+1，the same problem happend for me

**Comment by russellb** [comment]
should probably open an issue against xgrammar. It doesn't sound like this is something vllm can address.

**Comment by Li-Qingyun** [comment]
> should probably open an issue against xgrammar. It doesn't sound like this is something vllm can address.

yes, i think so. or is this requirement not too essential? May this be optional?

**Comment by russellb** [comment]
> > should probably open an issue against xgrammar. It doesn't sound like this is something vllm can address.
> 
> yes, i think so. or is this requirement not too essential? May this be optional?

It looks like the code already treats it as optional. As a workaround for now, you can get the rest of the vllm dependencies installed, and then install vllm with `pip install --no-deps`

**Comment by russellb** [comment]
related issue: https://github.com/mlc-ai/xgrammar/issues/113

**Comment by nomadlx** [comment]
I also solved the problem by installing xgrammar from the source code. The main thing to note is that the versions of cmake and gcc need to be high enough. I used cmake-3.23 and gcc-12.1 respectively.
```
pip install pybind11
git clone --recursive https://github.com/mlc-ai/xgrammar.git
mkdir build && cd build/
cmake ..
make -j8
cd ../python/
pip install -e .
```

**Comment by juburr** [comment]
I was seeing this error in some container builds -- namely images that were inadvertently locked onto `:latest` and therefore pulling Python 3.13.1. It happened in both `docker.io/python:bullseye` and `cgr.dev/chainguard/python:latest-dev`. Easy fix for me: downgrade to Python 3.12 and the issue goes away.

**Comment by skytodmoon** [comment]
mark，I met the same problem

**Comment by cskkx1** [comment]
> pip install -e .

install camke  https://blog.csdn.net/qq_45505081/article/details/130573708
and then build locally.

**Comment by pengwenzhi** [comment]
> +1，the same problem happend for me

I find the method to resolve the problem，I install the newest vllm version in the centos system come out this problem，I exchage the os system to ubantu, the problem resolved

**Comment by lampsonSong** [comment]
I met the same problem. I solved the problem by installing xgrammar from source code.
1. update gcc to 9 in centos-7 (I use 'yum install -y centos-release-scl, yum install devtoolset-9-gcc devtoolset-9-gcc-c++ devtoolset-9-binutils, then update the soft link of gcc)
2. update cmake > 3.18
3. install dlpack from source code.
4. Download xgrammar source code. Checkout to tag v.0.1.11. Then cmake, make, and enter 'xgrammar/python' dir, run 'python setup.py install'

**Comment by russellb** [comment]
Can those facing this issue try xgrammar 0.1.14 to see if that resolves your issue?

**Comment by LALBJ** [comment]
> Can those facing this issue try xgrammar 0.1.14 to see if that resolves your issue?

My problem was resolved by installing vllm 0.7.3 with xgrammar 0.1.14, even though vllm 0.7.3 requires xgrammar version 0.1.11.

**Comment by russellb** [comment]
> > Can those facing this issue try xgrammar 0.1.14 to see if that resolves your issue?
> 
> My problem was resolved by installing vllm 0.7.3 with xgrammar 0.1.14, even though vllm 0.7.3 requires xgrammar version 0.1.11.

Thanks for confirming. We'll get the requirements updated soon.

**Comment by Wiselnn570** [comment]
> > > Can those facing this issue try xgrammar 0.1.14 to see if that resolves your issue?
> > 
> > 
> > My problem was resolved by installing vllm 0.7.3 with xgrammar 0.1.14, even though vllm 0.7.3 requires xgrammar version 0.1.11.
> 
> Thanks for confirming. We'll get the requirements updated soon.

Require updating to 0.1.14, too.

**Comment by Wiselnn570** [comment]
Same error encountered when upgrade vllm from version 0.7.2 to 0.7.3.
```bash
ERROR: Could not find a version that satisfies the requirement xgrammar==0.1.11; platform_machine == "x86_64" (from vllm) (from versions: 0.1.14, 0.1.15)
ERROR: No matching distribution found for xgrammar==0.1.11; platform_machine == "x86_64"
```

**Comment by ShadeCloak** [comment]
> > Can those facing this issue try xgrammar 0.1.14 to see if that resolves your issue?
> 
> My problem was resolved by installing vllm 0.7.3 with xgrammar 0.1.14, even though vllm 0.7.3 requires xgrammar version 0.1.11.

Even with xgrammar 0.1.15 installed, there is still an error: ERROR: No matching distribution found for xgrammar==0.1.11; platform_machine == 'x86_64'. Could you please provide a detailed explanation on how to resolve this issue?

**Comment by edibrq** [comment]
Same problem, does anyone know how to fix this error with xgrammar?

**Comment by russellb** [comment]
This should be resolved as of #14590.

The next release, v0.8.0, will include the fix.
