### ISSUE TITLE
[Bug]: Likely Regression - Was working in v0.6.3.post1, now using response_format parameter with "type": "bool" in v0.7.3: BadRequestError: Error code 400 - {'object': 'error', 'message': 'json_schema_converter.cc:595 Unsupported type bool in schema {type":"bool"}\n, 'type': 'BadRequestError', 'param': None, 'code': 400}

### ISSUE THREAD

**Issue by agm-eratosth** [vllm-project/vllm#13864]
### Your current environment

<details>
Using version vLLM v0.7.3 docker and OpenAI API creates the following issue for constrained output. Confirmed is not an issue on v0.6.3.post1 when defining a type as bool.

</details>

### 🐛 Describe the bug

Note code might have minor typos, could not copy paste.

```
from openai import OpenAI

client = OpenAI(
     api_key="API_KEY_HERE"
     base_url="vllm_hostname_or_IP_here:8000/v1"
)

messages = [ 
{"role": "system", "content": "is there a number in the following text?\n"},
{"role": "user", "content": "lets do a math problem 2 + 2 is equal to what?"}

]

model = llama3.3 #(any llama 3.3 model)



completion = client.chat.completions.create(
     model=model,
     messages=messages,
     stream=False,
     seed=1234,
     response_format={
          "type": "json_schema",
          "json_schema": {
               "name":"format_response",
               "schema": {
                    "contains_number": {"type":"bool"}
                    }
               }
          }
     }
)

print(completetion.choices[0].message.content)
```
Results in following error:

`BadRequestError: Error code 400 - {'object': 'error', 'message': 'json_schema_converter.cc:595 Unsupported type bool in schema {type":"bool"}\n, 'type': 'BadRequestError', 'param': None, 'code': 400}`

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by agm-eratosth** [comment]
So while the feature works in v0.6.3-post1 I started iterating through to figure out where this bug appears. It appears that there was a different bug in v0.6.4 running the above code I get the following error -

server side:
```
500 Internal Server Error
```

```
file "user/local/lib/python3.12/dist-packages/lmformatenforcer/external/jsonschemaobject.py", line 177, in validate_exclusive_maxiumum_and_exclusive_minimum 

exclusive_maximum: Union[float, bool, none] = values.get('exclusiveMaximum')
"AttributeError: 'list' object has no attribute 'get'
```

client side:
```
InternalServerError: Internal server error
```
