### PR TITLE
[Bugfix] Guard mm_token_type_ids kwarg in get_mrope_input_positions

### PR DESCRIPTION
**Pull request by AndreasKaratzas**
#35097 introduced passing `mm_token_type_ids` to `model.get_rope_index()` in the transformers multimodal backend. However, not all models accept this parameter. For example, `Qwen2_5_VLModel.get_rope_index()` does not have `mm_token_type_ids` in its signature nor `**kwargs`, causing a `TypeError` at inference time.

```log
TypeError: Qwen2_5_VLModel.get_rope_index() got an unexpected keyword argument 'mm_token_type_ids'
```

Reproduced via:
```bash
pytest -s -v tests/models/multimodal/generation/test_common.py::test_single_image_models[qwen2_5_vl-transformers-test_case53]
```

Bisected to fd6de37.

## Fix

Before passing `mm_token_type_ids` as a kwarg, inspect the signature of `model.get_rope_index()` to check whether it actually accepts the parameter (either explicitly or via `**kwargs`). If it doesn't, skip it.

cc @kenroche

### CODE REVIEW

File: vllm/model_executor/models/transformers/multimodal.py [hunk 1]
```diff
@@ -474,7 +474,14 @@ def get_mrope_input_positions(
...
         if mm_token_type_ids:
-            kwargs["mm_token_type_ids"] = torch.cat(mm_token_type_ids)
+            import inspect
+
+            sig = inspect.signature(self.model.get_rope_index)
+            params = sig.parameters
+            if "mm_token_type_ids" in params or any(
+                p.kind == inspect.Parameter.VAR_KEYWORD for p in params.values()
+            ):
+                kwargs["mm_token_type_ids"] = torch.cat(mm_token_type_ids)
```
[the remark this answers is not in the document]
Comment (AndreasKaratzas) [reply vllm/model_executor/models/transformers/multimodal.py]: Fair suggestion. Done :)

**Review by hmellor — APPROVED** [review]
Yeah this will work for now! I'm excited for the Transformers modelling backend to be tested more on AMD!
